export const enDashboardMessages = {
  "dashboard.analyticsEyebrow": "Quality operations",
  "dashboard.analyticsTitle": "Quality in motion",
  "dashboard.analyticsDescription": "Release flow, coverage, product risk, and defects in one operational view.",
  "dashboard.scope": "Scope",
  "dashboard.currentProject": "Current project",
  "dashboard.workspaceScope": "All projects",
  "dashboard.period": "Period",
  "dashboard.period7": "7 days",
  "dashboard.period30": "30 days",
  "dashboard.period90": "90 days",
  "dashboard.refresh": "Refresh analytics",
  "dashboard.summaryLoading": "Loading quality analytics…",
  "dashboard.summaryError": "Could not load quality analytics.",
  "dashboard.staleAnalytics": "Refresh failed; showing the last available snapshot.",
  "dashboard.currentCases": "Current test cases",
  "dashboard.createdPeriod": "+{count} created in period",
  "dashboard.launchedRuns": "Runs launched",
  "dashboard.activeRunHint": "{count} active now",
  "dashboard.completedHint": "{count} completed in period",
  "dashboard.reportedPeriod": "+{count} reported in period",
  "dashboard.linkedDefects": "Linked defects",
  "dashboard.linkCoverageHint": "{count}% of current defects",
  "dashboard.runFlow": "Run Flow",
  "dashboard.runFlowHint": "Launched runs, terminal outcomes, and pass-rate trend.",
  "dashboard.runFlowAria": "Run outcomes and pass rate over the selected period",
  "dashboard.bucket": "Drill window",
  "dashboard.wholePeriod": "Whole period",
  "dashboard.launched": "Launched",
  "dashboard.blocked": "Blocked",
  "dashboard.aborted": "Aborted",
  "dashboard.incomplete": "Incomplete",
  "dashboard.notStarted": "Not started",
  "dashboard.noRunFlow": "No run events in this period.",
  "dashboard.riskHotspots": "Risk hotspots",
  "dashboard.riskHint": "Ranked by failures, blockers, critical defects, and execution coverage.",
  "dashboard.project": "Project",
  "dashboard.component": "Component",
  "dashboard.risk": "Risk",
  "dashboard.failedRuns": "Failed runs",
  "dashboard.failedItems": "Failed items",
  "dashboard.blockedItems": "Blocked items",
  "dashboard.passRateShort": "Pass",
  "dashboard.coverageRateShort": "Coverage",
  "dashboard.failedItemsShort": "Failed",
  "dashboard.blockedItemsShort": "Blocked",
  "dashboard.defectsShort": "Defects",
  "dashboard.criticalDefects": "Critical defects",
  "dashboard.coverageRate": "Coverage",
  "dashboard.defects": "Defects",
  "dashboard.unavailable": "Not attributable",
  "dashboard.componentAttributionNote": "Local fallback data cannot attribute immutable run items or execution coverage; enable server analytics for these signals.",
  "dashboard.noHotspots": "No project or component signals yet.",
  "dashboard.byType": "Cases by type",
  "dashboard.byTypeHint": "Current non-archived repository.",
  "dashboard.byTag": "Top tags",
  "dashboard.byTagHint": "Cases may contribute to more than one tag.",
  "dashboard.noTags": "No tagged cases in this scope.",
  "dashboard.coverage": "Product coverage",
  "dashboard.coverageHint": "Current cases seen in runs started during the selected period, by project or component.",
  "dashboard.noCoverage": "Execution coverage is not available for this scope yet.",
  "dashboard.uncovered": "Uncovered cases",
  "dashboard.uncoveredShort": "Gap",
  "dashboard.automationCoverage": "Automated cases",
  "dashboard.tagCoverage": "Tagged cases",
  "dashboard.defectLinkCoverage": "Defects with links",
  "dashboard.coveredOfTotal": "{covered} of {total}",
  "dashboard.untagged": "Untagged cases",
  "dashboard.unlinkedDefects": "Defects without links",
  "dashboard.defectLifecycle": "Defect lifecycle",
  "dashboard.defectLifecycleHint": "Current defect inventory across every workflow state.",
  "dashboard.noDefects": "No current defects in this scope.",
  "dashboard.drillTitle": "Analytics detail",
  "dashboard.exactFilters": "Exact server filters",
  "dashboard.matches": "{count} matching records",
  "dashboard.drillLoading": "Loading matching records…",
  "dashboard.drillError": "Could not load this analytics slice.",
  "dashboard.retry": "Retry",
  "dashboard.drillEmpty": "No records match these filters.",
  "dashboard.loadMore": "Load more",
  "dashboard.externalLinks": "External links",
  "dashboard.openExternalLink": "Open {label}",
  "dashboard.sourceNote": "Loaded workspace data; server analytics will replace this adapter after the stable contract sync.",
} as const;
