export const enDashboardMessages = {
  "dashboard.analyticsTitle": "Quality in motion",
  "dashboard.analyticsDescription": "Runs, coverage, and defects.",
  "dashboard.scope": "Show",
  "dashboard.workspaceScope": "All projects",
  "dashboard.period": "Period",
  "dashboard.period7": "7 days",
  "dashboard.period30": "30 days",
  "dashboard.period90": "90 days",
  "dashboard.refresh": "Refresh",
  "dashboard.summaryLoading": "Loading data…",
  "dashboard.summaryError": "Could not load data.",
  "dashboard.staleAnalytics": "Refresh failed. Showing the latest available data.",
  "dashboard.currentCases": "Test cases",
  "dashboard.createdPeriod": "New: {count}",
  "dashboard.launchedRuns": "Runs launched",
  "dashboard.activeRunHint": "Active: {count}",
  "dashboard.completedHint": "Completed: {count}",
  "dashboard.reportedPeriod": "New: {count}",
  "dashboard.linkedDefects": "Linked defects",
  "dashboard.linkCoverageHint": "With links: {count}%",
  "dashboard.runFlow": "Run Flow",
  "dashboard.runFlowHint": "Runs and outcomes by date.",
  "dashboard.runFlowAria": "Run outcomes and pass rate over the selected period",
  "dashboard.bucket": "Date",
  "dashboard.wholePeriod": "Whole period",
  "dashboard.launched": "Launched",
  "dashboard.blocked": "Blocked",
  "dashboard.aborted": "Aborted",
  "dashboard.incomplete": "Incomplete",
  "dashboard.notStarted": "Not started",
  "dashboard.noRunFlow": "No run events in this period.",
  "dashboard.riskHotspots": "Risk hotspots",
  "dashboard.riskHint": "Components that need attention.",
  "dashboard.project": "Project",
  "dashboard.component": "Component",
  "dashboard.risk": "Risk",
  "dashboard.failedRuns": "Failed runs",
  "dashboard.failedItems": "Failed items",
  "dashboard.blockedItems": "Blocked items",
  "dashboard.passRateShort": "Success",
  "dashboard.coverageRateShort": "Coverage",
  "dashboard.failedItemsShort": "Failed",
  "dashboard.blockedItemsShort": "Blocked",
  "dashboard.defectsShort": "Defects",
  "dashboard.criticalDefects": "Critical defects",
  "dashboard.coverageRate": "Coverage",
  "dashboard.defects": "Defects",
  "dashboard.unavailable": "No data",
  "dashboard.componentAttributionNote": "Coverage appears after the first run.",
  "dashboard.noHotspots": "Nothing to compare yet.",
  "dashboard.byType": "Cases by type",
  "dashboard.byTag": "Top tags",
  "dashboard.noTags": "No tagged cases in this scope.",
  "dashboard.coverage": "Product coverage",
  "dashboard.coverageHint": "Cases that have already been run.",
  "dashboard.noCoverage": "Coverage appears after the first run.",
  "dashboard.uncovered": "Uncovered cases",
  "dashboard.uncoveredShort": "Not run",
  "dashboard.automationCoverage": "Automated cases",
  "dashboard.tagCoverage": "Tagged cases",
  "dashboard.defectLinkCoverage": "Defects with links",
  "dashboard.coveredOfTotal": "{covered} of {total}",
  "dashboard.untagged": "Untagged cases",
  "dashboard.unlinkedDefects": "Defects without links",
  "dashboard.defectLifecycle": "Defect lifecycle",
  "dashboard.defectLifecycleHint": "Current statuses.",
  "dashboard.noDefects": "No defects.",
  "dashboard.drillTitle": "Details",
  "dashboard.overview": "Overview",
  "dashboard.runs": "Runs",
  "dashboard.detailSections": "Detail sections",
  "dashboard.relatedUnavailable": "No data for this section",
  "dashboard.tab.test_case": "Test cases",
  "dashboard.tab.run": "Runs",
  "dashboard.tab.defect": "Defects",
  "dashboard.period.7d": "7 days",
  "dashboard.period.30d": "30 days",
  "dashboard.period.90d": "90 days",
  "dashboard.filter.type": "Type",
  "dashboard.filter.tag": "Tag",
  "dashboard.filter.coverage": "Coverage",
  "dashboard.filter.status": "Status",
  "dashboard.filter.outcome": "Outcome",
  "dashboard.filter.itemStatus": "Check result",
  "dashboard.filter.severity": "Severity",
  "dashboard.filter.component": "Component",
  "dashboard.filter.untagged": "Untagged",
  "dashboard.filter.activeOnly": "Active only",
  "dashboard.filter.componentEmpty": "No component",
  "dashboard.open.test_case": "Open in test cases",
  "dashboard.open.run": "Open in runs",
  "dashboard.open.defect": "Open in defects",
  "dashboard.openSection": "Go to section",
  "dashboard.createRunFromLoaded": "Create run",
  "dashboard.refineList": "Filters",
  "dashboard.searchRecords": "Search",
  "dashboard.searchPlaceholder": "Key, title, or component",
  "dashboard.allValues": "All values",
  "dashboard.type": "Type",
  "dashboard.status": "Status",
  "dashboard.priority": "Priority",
  "dashboard.record": "Record",
  "dashboard.updated": "Updated",
  "dashboard.openRecord": "Open record",
  "dashboard.localFilterEmpty": "Nothing found",
  "dashboard.loadedRecords": "Total found",
  "dashboard.visibleAfterRefine": "After filters",
  "dashboard.projectsRepresented": "Projects",
  "dashboard.visibleRecords": "{count} in list",
  "dashboard.sort": "Show first",
  "dashboard.sortRecent": "Newest",
  "dashboard.sortTitle": "By title",
  "dashboard.sortStatus": "By status",
  "dashboard.matches": "{count} matching records",
  "dashboard.drillLoading": "Loading…",
  "dashboard.drillError": "Could not load data.",
  "dashboard.retry": "Retry",
  "dashboard.drillEmpty": "No records match these filters.",
  "dashboard.loadMore": "Load more",
  "dashboard.externalLinks": "External links",
  "dashboard.openExternalLink": "Open {label}",
} as const;
