export const enDashboardMessages = {
  "dashboard.analyticsTitle": "Dashboard",
  "dashboard.analyticsDescription": "Current work and testing results.",
  "dashboard.scope": "Show",
  "dashboard.workspaceScope": "All projects",
  "dashboard.period": "Period",
  "dashboard.period7": "7 days",
  "dashboard.period30": "30 days",
  "dashboard.period90": "90 days",
  "dashboard.refresh": "Refresh",
  "dashboard.summaryLoading": "Loading data…",
  "dashboard.summaryError": "Could not load data.",
  "dashboard.staleAnalytics": "Refresh failed. Showing the latest available data.",
  "dashboard.currentCases": "Test cases",
  "dashboard.createdPeriod": "New: {count}",
  "dashboard.launchedRuns": "Runs launched",
  "dashboard.activeRunHint": "Active: {count}",
  "dashboard.completedHint": "Completed: {count}",
  "dashboard.reportedPeriod": "New: {count}",
  "dashboard.linkedDefects": "Linked defects",
  "dashboard.linkCoverageHint": "With links: {count}%",
  "dashboard.runFlow": "Run activity",
  "dashboard.runFlowHint": "Run launches and final outcomes over the selected period.",
  "dashboard.runFlowAria": "Run launches and outcomes over the selected period",
  "dashboard.bucket": "Date",
  "dashboard.wholePeriod": "Whole period",
  "dashboard.launched": "Launched",
  "dashboard.blocked": "Blocked",
  "dashboard.aborted": "Aborted",
  "dashboard.incomplete": "Incomplete",
  "dashboard.notStarted": "Not started",
  "dashboard.noRunFlow": "No run events in this period.",
  "dashboard.riskHotspots": "Projects and components",
  "dashboard.riskHint": "Checks in the selected period. Defects open right now.",
  "dashboard.project": "Project",
  "dashboard.component": "Component",
  "dashboard.risk": "Risk",
  "dashboard.failedRuns": "Failed runs",
  "dashboard.failedItems": "Failed items",
  "dashboard.blockedItems": "Blocked items",
  "dashboard.passRateShort": "Pass rate",
  "dashboard.coverageRateShort": "Reach",
  "dashboard.failedItemsShort": "Failed",
  "dashboard.blockedItemsShort": "Blocked",
  "dashboard.defectsShort": "Defects",
  "dashboard.criticalDefects": "Critical defects",
  "dashboard.coverageRate": "Cases in runs launched during the period",
  "dashboard.defects": "Defects",
  "dashboard.unavailable": "No data",
  "dashboard.componentAttributionNote": "Results cannot be attributed to components in this selection.",
  "dashboard.noHotspots": "Nothing to compare yet.",
  "dashboard.byType": "Cases by type",
  "dashboard.byTag": "Top tags",
  "dashboard.noTags": "No tagged cases in this scope.",
  "dashboard.coverage": "Run reach",
  "dashboard.coverageHint": "Cases included in runs launched during the period.",
  "dashboard.noCoverage": "No run reach data for the selected period.",
  "dashboard.uncovered": "Cases outside runs in this period",
  "dashboard.uncoveredShort": "Outside runs",
  "dashboard.automationCoverage": "Automated cases",
  "dashboard.tagCoverage": "Tagged cases",
  "dashboard.defectLinkCoverage": "Defects with links",
  "dashboard.coveredOfTotal": "{covered} of {total}",
  "dashboard.untagged": "Untagged cases",
  "dashboard.unlinkedDefects": "Defects without links",
  "dashboard.defectLifecycle": "Defect statuses",
  "dashboard.defectLifecycleHint": "Current statuses.",
  "dashboard.noDefects": "No defects.",
  "dashboard.drillTitle": "Details",
  "dashboard.overview": "Overview",
  "dashboard.runs": "Runs",
  "dashboard.detailSections": "Detail sections",
  "dashboard.relatedUnavailable": "No data for this section",
  "dashboard.tab.test_case": "Test cases",
  "dashboard.tab.run": "Runs",
  "dashboard.tab.defect": "Defects",
  "dashboard.period.7d": "7 days",
  "dashboard.period.30d": "30 days",
  "dashboard.period.90d": "90 days",
  "dashboard.filter.type": "Type",
  "dashboard.filter.tag": "Tag",
  "dashboard.filter.coverage": "Coverage",
  "dashboard.filter.status": "Status",
  "dashboard.filter.outcome": "Outcome",
  "dashboard.filter.itemStatus": "Check result",
  "dashboard.filter.severity": "Severity",
  "dashboard.filter.component": "Component",
  "dashboard.filter.untagged": "Untagged",
  "dashboard.filter.activeOnly": "Active only",
  "dashboard.filter.componentEmpty": "No component",
  "dashboard.open.test_case": "Open in test cases",
  "dashboard.open.run": "Open in runs",
  "dashboard.open.defect": "Open in defects",
  "dashboard.openSection": "Go to section",
  "dashboard.createRunFromLoaded": "Create run",
  "dashboard.refineList": "Filters",
  "dashboard.searchRecords": "Search",
  "dashboard.searchPlaceholder": "Key, title, or component",
  "dashboard.allValues": "All values",
  "dashboard.type": "Type",
  "dashboard.status": "Status",
  "dashboard.priority": "Priority",
  "dashboard.record": "Record",
  "dashboard.updated": "Updated",
  "dashboard.openRecord": "Open record",
  "dashboard.localFilterEmpty": "Nothing found",
  "dashboard.loadedRecords": "Total found",
  "dashboard.visibleAfterRefine": "After filters",
  "dashboard.projectsRepresented": "Projects",
  "dashboard.visibleRecords": "{count} in list",
  "dashboard.sort": "Show first",
  "dashboard.sortRecent": "Newest",
  "dashboard.sortTitle": "By title",
  "dashboard.sortStatus": "By status",
  "dashboard.matches": "{count} matching records",
  "dashboard.drillLoading": "Loading…",
  "dashboard.drillError": "Could not load data.",
  "dashboard.retry": "Retry",
  "dashboard.drillEmpty": "No records match these filters.",
  "dashboard.loadMore": "Load more",
  "dashboard.externalLinks": "External links",
  "dashboard.openExternalLink": "Open {label}",
  "dashboard.runCount": "Runs",
  "dashboard.casePassRate": "Case pass rate",
  "dashboard.showSeries": "Show series",
  "dashboard.hideSeries": "Hide series",
  "dashboard.currentActiveRuns": "Active runs",
  "dashboard.currentActiveRunsHint": "In progress right now",
  "dashboard.currentRetest": "Ready for retest",
  "dashboard.currentRetestHint": "Defects awaiting verification",
  "dashboard.currentBlocked": "Blocked checks",
  "dashboard.currentBlockedHint": "Checks in active runs",
  "dashboard.currentDefects": "Open defects",
  "dashboard.currentDefectsHint": "All unresolved statuses",
  "dashboard.currentSummary": "Current work in the selected environment and build",
  "dashboard.libraryTitle": "Library and statuses",
  "dashboard.libraryHint": "{cases} cases · {defects} defects · types, tags and reach",
  "dashboard.historyScope": "History · all environments and builds",
  "dashboard.historyPeriod": "Period for activity and reach",
  "dashboard.historicalUpdated": "History updated {date}",
  "dashboard.riskLimited": "Showing the first {count} areas. Choose a project for a more focused overview.",
} as const;
