export const ruDashboardMessages = {
  "dashboard.analyticsTitle": "Качество в динамике",
  "dashboard.analyticsDescription": "Прогоны, покрытие и дефекты.",
  "dashboard.scope": "Показать",
  "dashboard.workspaceScope": "Все проекты",
  "dashboard.period": "Период",
  "dashboard.period7": "7 дней",
  "dashboard.period30": "30 дней",
  "dashboard.period90": "90 дней",
  "dashboard.refresh": "Обновить",
  "dashboard.summaryLoading": "Загружаем данные…",
  "dashboard.summaryError": "Не удалось загрузить данные.",
  "dashboard.staleAnalytics": "Не удалось обновить. Показаны последние данные.",
  "dashboard.currentCases": "Тест-кейсы",
  "dashboard.createdPeriod": "Новые: {count}",
  "dashboard.launchedRuns": "Запущено ранов",
  "dashboard.activeRunHint": "Активны: {count}",
  "dashboard.completedHint": "Завершены: {count}",
  "dashboard.reportedPeriod": "Новые: {count}",
  "dashboard.linkedDefects": "Дефекты со ссылками",
  "dashboard.linkCoverageHint": "Со ссылками: {count}%",
  "dashboard.runFlow": "Поток ранов",
  "dashboard.runFlowHint": "Запуски и результаты по дням.",
  "dashboard.runFlowAria": "Исходы ранов и процент прохождения за выбранный период",
  "dashboard.bucket": "Дата",
  "dashboard.wholePeriod": "Весь период",
  "dashboard.launched": "Запущено",
  "dashboard.blocked": "Заблокировано",
  "dashboard.aborted": "Прервано",
  "dashboard.incomplete": "Не завершено",
  "dashboard.notStarted": "Не начато",
  "dashboard.noRunFlow": "За этот период событий ранов нет.",
  "dashboard.riskHotspots": "Где проседаем",
  "dashboard.riskHint": "Компоненты, которым нужно внимание.",
  "dashboard.project": "Проект",
  "dashboard.component": "Компонент",
  "dashboard.risk": "Риск",
  "dashboard.failedRuns": "Провалено ранов",
  "dashboard.failedItems": "Не пройдено",
  "dashboard.blockedItems": "Заблокировано",
  "dashboard.passRateShort": "Успех",
  "dashboard.coverageRateShort": "Покрытие",
  "dashboard.failedItemsShort": "Не пройдено",
  "dashboard.blockedItemsShort": "Заблокировано",
  "dashboard.defectsShort": "Дефекты",
  "dashboard.criticalDefects": "Критические дефекты",
  "dashboard.coverageRate": "Покрытие",
  "dashboard.defects": "Дефекты",
  "dashboard.unavailable": "Нет данных",
  "dashboard.componentAttributionNote": "Покрытие появится после первого прогона.",
  "dashboard.noHotspots": "Пока нечего сравнивать.",
  "dashboard.byType": "Кейсы по типу",
  "dashboard.byTag": "Популярные теги",
  "dashboard.noTags": "В этой области нет кейсов с тегами.",
  "dashboard.coverage": "Покрытие продукта",
  "dashboard.coverageHint": "Какие кейсы уже запускали.",
  "dashboard.noCoverage": "Покрытие появится после первого прогона.",
  "dashboard.uncovered": "Непокрытые кейсы",
  "dashboard.uncoveredShort": "Не запускали",
  "dashboard.automationCoverage": "Автоматизированные кейсы",
  "dashboard.tagCoverage": "Кейсы с тегами",
  "dashboard.defectLinkCoverage": "Дефекты со ссылками",
  "dashboard.coveredOfTotal": "{covered} из {total}",
  "dashboard.untagged": "Кейсы без тегов",
  "dashboard.unlinkedDefects": "Дефекты без ссылок",
  "dashboard.defectLifecycle": "Жизненный цикл дефектов",
  "dashboard.defectLifecycleHint": "Текущие статусы.",
  "dashboard.noDefects": "Дефектов нет.",
  "dashboard.drillTitle": "Детали",
  "dashboard.overview": "Обзор",
  "dashboard.runs": "Раны",
  "dashboard.detailSections": "Разделы детализации",
  "dashboard.relatedUnavailable": "Для этого раздела нет данных",
  "dashboard.tab.test_case": "Тест-кейсы",
  "dashboard.tab.run": "Раны",
  "dashboard.tab.defect": "Дефекты",
  "dashboard.period.7d": "7 дней",
  "dashboard.period.30d": "30 дней",
  "dashboard.period.90d": "90 дней",
  "dashboard.filter.type": "Тип",
  "dashboard.filter.tag": "Тег",
  "dashboard.filter.coverage": "Покрытие",
  "dashboard.filter.status": "Статус",
  "dashboard.filter.outcome": "Исход",
  "dashboard.filter.itemStatus": "Результат проверки",
  "dashboard.filter.severity": "Критичность",
  "dashboard.filter.component": "Компонент",
  "dashboard.filter.untagged": "Без тегов",
  "dashboard.filter.activeOnly": "Только активные",
  "dashboard.filter.componentEmpty": "Без компонента",
  "dashboard.open.test_case": "Открыть в тест-кейсах",
  "dashboard.open.run": "Открыть в ранах",
  "dashboard.open.defect": "Открыть в дефектах",
  "dashboard.createRunFromLoaded": "Создать ран",
  "dashboard.refineList": "Фильтры",
  "dashboard.searchRecords": "Поиск",
  "dashboard.searchPlaceholder": "Ключ, название или компонент",
  "dashboard.allValues": "Все значения",
  "dashboard.type": "Тип",
  "dashboard.status": "Статус",
  "dashboard.priority": "Приоритет",
  "dashboard.record": "Запись",
  "dashboard.updated": "Обновлено",
  "dashboard.openRecord": "Открыть запись",
  "dashboard.localFilterEmpty": "Ничего не найдено",
  "dashboard.loadedRecords": "Всего найдено",
  "dashboard.visibleAfterRefine": "После фильтров",
  "dashboard.projectsRepresented": "Проектов",
  "dashboard.visibleRecords": "{count} в списке",
  "dashboard.sort": "Сначала",
  "dashboard.sortRecent": "Новые",
  "dashboard.sortTitle": "По названию",
  "dashboard.sortStatus": "По статусу",
  "dashboard.matches": "Подходящих записей: {count}",
  "dashboard.drillLoading": "Загружаем…",
  "dashboard.drillError": "Не удалось загрузить данные.",
  "dashboard.retry": "Повторить",
  "dashboard.drillEmpty": "По этим фильтрам записей нет.",
  "dashboard.loadMore": "Загрузить ещё",
  "dashboard.externalLinks": "Внешние ссылки",
  "dashboard.openExternalLink": "Открыть {label}",
} as const;
