export const ruDashboardMessages = {
  "dashboard.analyticsEyebrow": "Управление качеством",
  "dashboard.analyticsTitle": "Качество в динамике",
  "dashboard.analyticsDescription": "Поток прогонов, покрытие, продуктовые риски и дефекты в одном рабочем представлении.",
  "dashboard.scope": "Область",
  "dashboard.currentProject": "Текущий проект",
  "dashboard.workspaceScope": "Все проекты",
  "dashboard.period": "Период",
  "dashboard.period7": "7 дней",
  "dashboard.period30": "30 дней",
  "dashboard.period90": "90 дней",
  "dashboard.refresh": "Обновить аналитику",
  "dashboard.summaryLoading": "Загружаем аналитику качества…",
  "dashboard.summaryError": "Не удалось загрузить аналитику качества.",
  "dashboard.staleAnalytics": "Обновление не удалось; показан последний доступный срез.",
  "dashboard.currentCases": "Актуальные тест-кейсы",
  "dashboard.createdPeriod": "+{count} создано за период",
  "dashboard.launchedRuns": "Запущено ранов",
  "dashboard.activeRunHint": "{count} активных сейчас",
  "dashboard.completedHint": "{count} завершено за период",
  "dashboard.reportedPeriod": "+{count} заведено за период",
  "dashboard.linkedDefects": "Дефекты со ссылками",
  "dashboard.linkCoverageHint": "{count}% актуальных дефектов",
  "dashboard.runFlow": "Поток ранов",
  "dashboard.runFlowHint": "Запуски, финальные исходы и динамика процента прохождения.",
  "dashboard.runFlowAria": "Исходы ранов и процент прохождения за выбранный период",
  "dashboard.bucket": "Интервал детализации",
  "dashboard.wholePeriod": "Весь период",
  "dashboard.launched": "Запущено",
  "dashboard.blocked": "Заблокировано",
  "dashboard.aborted": "Прервано",
  "dashboard.incomplete": "Не завершено",
  "dashboard.notStarted": "Не начато",
  "dashboard.noRunFlow": "За этот период событий ранов нет.",
  "dashboard.riskHotspots": "Где проседаем",
  "dashboard.riskHint": "Рейтинг по провалам, блокерам, критическим дефектам и покрытию прогонами.",
  "dashboard.project": "Проект",
  "dashboard.component": "Компонент",
  "dashboard.risk": "Риск",
  "dashboard.failedRuns": "Провалено ранов",
  "dashboard.failedItems": "Провалено кейсов",
  "dashboard.blockedItems": "Заблокировано кейсов",
  "dashboard.criticalDefects": "Критические дефекты",
  "dashboard.coverageRate": "Покрытие",
  "dashboard.defects": "Дефекты",
  "dashboard.unavailable": "Нет атрибуции",
  "dashboard.componentAttributionNote": "Локальный резервный срез не атрибутирует неизменяемые run-item и покрытие; эти сигналы предоставляет серверная аналитика.",
  "dashboard.noHotspots": "Сигналов по проектам или компонентам пока нет.",
  "dashboard.byType": "Кейсы по типу",
  "dashboard.byTypeHint": "Актуальный неархивный репозиторий.",
  "dashboard.byTag": "Популярные теги",
  "dashboard.byTagHint": "Один кейс может учитываться в нескольких тегах.",
  "dashboard.noTags": "В этой области нет кейсов с тегами.",
  "dashboard.coverage": "Покрытие продукта",
  "dashboard.coverageHint": "Актуальные кейсы в запущенных за период ранах — по проектам или компонентам.",
  "dashboard.noCoverage": "Для этой области пока нет данных о покрытии прогонами.",
  "dashboard.uncovered": "Непокрытые кейсы",
  "dashboard.uncoveredShort": "Пробел",
  "dashboard.automationCoverage": "Автоматизированные кейсы",
  "dashboard.tagCoverage": "Кейсы с тегами",
  "dashboard.defectLinkCoverage": "Дефекты со ссылками",
  "dashboard.coveredOfTotal": "{covered} из {total}",
  "dashboard.untagged": "Кейсы без тегов",
  "dashboard.unlinkedDefects": "Дефекты без ссылок",
  "dashboard.defectLifecycle": "Жизненный цикл дефектов",
  "dashboard.defectLifecycleHint": "Актуальный реестр дефектов по всем состояниям процесса.",
  "dashboard.noDefects": "В этой области нет дефектов.",
  "dashboard.drillTitle": "Детали аналитики",
  "dashboard.exactFilters": "Точные серверные фильтры",
  "dashboard.matches": "Подходящих записей: {count}",
  "dashboard.drillLoading": "Загружаем подходящие записи…",
  "dashboard.drillError": "Не удалось загрузить этот срез аналитики.",
  "dashboard.retry": "Повторить",
  "dashboard.drillEmpty": "По этим фильтрам записей нет.",
  "dashboard.loadMore": "Загрузить ещё",
  "dashboard.externalLinks": "Внешние ссылки",
  "dashboard.openExternalLink": "Открыть {label}",
  "dashboard.sourceNote": "Используются загруженные данные рабочей области; после стабилизации контракта адаптер заменит серверная аналитика.",
} as const;
