import { articles, bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";

export const settingsArticle: DocArticle = {
  id: "settings", title: "Project and interface settings", group: "reference",
  description: "Project settings, environments, case transfers, appearance, language, personal notifications, and your current session.",
  keywords: ["settings", "general", "general", "environments", "environments", "appearance", "appearance", "language", "language", "account", "session", "sign out", "settings", "notifications", "personal settings"],
  related: ["navigation", "workspace", "import-export", "permissions", "notifications"],
  sections: [
    section("open", "Open settings for the right project", paragraph("Click **Settings** near the bottom of the sidebar. For project settings, first select a project in Falcon's top bar: the **Project** group names the project your changes apply to. **Personal settings** contains appearance, notifications and your account; these sections are available without selecting a project."),
      table(["Section", "What you can configure"],
        ["General", "The project's name, description, and status, and its permanent key for reference."],
        ["Environments", "Test environment URLs and their status."],
        ["Import and export", "Open the import screen or export the project's test cases."],
        ["Appearance and language", "Your theme and interface language in this browser."],
        ["Notifications", "Your event categories, Telegram connection and browser notifications for this company."],
        ["Account and session", "Your current account and sign-out action."])),
    section("general", "Edit project settings", steps(
      ["Open General", "Check the selected project's name, description, key, and status."],
      ["Click Edit", "You can change the name and description, choose a portfolio, and assign a project owner. The portfolio and owner are optional."],
      ["Save your changes", "An existing project's key is locked: renaming the project does not change it. Save changes applies your edits; Cancel closes the form without saving."]),
      note("Project archive", "The bottom of the section offers Archive or Restore, depending on the project's status. Archiving preserves data and history. Coordinate with your team to finish ongoing work first.")),
    section("environments", "Create or edit an environment", paragraph("Click the environment in the top bar to open **Settings → Environments**. This opens the list, without starting creation. Search by name, key or URL."), steps(
      ["Click New environment", "The inline form expands at the top of the list. Enter a name, unique key, and full environment URL, such as https://staging.example.com. The description is optional. The URL must use HTTP(S) and must not contain a username or password."],
      ["Save the environment", "The saved environment appears in the project's list. Its row shows the name, default or archived badge, key, and URL. Choose Save to apply the form."],
      ["Edit as needed", "The pencil expands an inline edit form below that row. Cancel collapses it without saving. The icon next to the address copies the environment URL. If copying is unavailable, select and copy the address manually."],
      ["Retire an unused environment", "Choose Archive from the row’s more-actions menu; archived environments can be restored. Saved runs retain their context."]),
      note("Default environment", "The Default badge identifies the environment already set as the default. This form has no control for assigning a default. When creating a run, Falcon uses the project's active default environment if configured; existing runs keep their original settings.")),
    section("exchange", "Transfer test cases", paragraph("Open **Import and export** to go straight to the import screen. Click **Export test cases** at the top right to download the selected project's test cases as JSON. The action is disabled while the export is prepared. Falcon then reports how many cases were exported."),
      paragraph("Drop a JSON file into the upload area or click **Choose file**. Select the project and destination folder below, review the contents and start the import. Source file history is on the same screen. You do not need to return to Settings for each file. A server connection and permission for the action are required."),
      articles("import-export")),
    section("appearance", "Choose a light or dark theme", paragraph("Open **Appearance and language** and click the theme preview you want. The theme changes immediately, with no separate save action. Your choice applies to this browser and does not change the appearance for other members.")),
    section("language", "Change the interface language", paragraph("In the same section, under **Language**, choose **English** or **Russian**. The interface switches immediately. On first use without a saved choice, Falcon uses Russian for browsers set to Russian and English for other browser languages. Your manual choice is saved in this browser."),
      note("What gets translated", "Interface labels change. Project names, case text, comments, and other team data are not translated automatically. This edition of the guide is written in English and uses English control labels.")),
    section("session", "Check your account and sign out", paragraph("**Account and session** shows the name you are signed in under. Click **Sign out** to end the current session. Wait for the sign-in page; if Falcon reports a sign-out error, try again."),
      paragraph("This section does not list devices or let you change your name, photo, or password. If your account supports a personal profile, open it from your name or avatar at the bottom of the main menu. Company account devices and sessions are managed in that profile."),
      note("Personal preferences are saved separately", "Signing out does not delete projects or test results. The theme and language saved in your browser are separate from the sign-in session.")),
    section("permissions", "Required permissions", table(["Action", "Access"],
      ["Edit or archive a project", "Workspace administrator or QA manager."],
      ["Create, edit, or archive an environment", "Workspace administrator or QA manager."],
      ["Import cases", "Test case management permission: administrator, QA manager, or tester."],
      ["Export cases", "Permission to read the selected project's test cases."],
      ["Change theme, language or notification preferences, or sign out", "Personal actions for the current user."]),
      bullets("Having access to a form does not bypass server permission checks. If an action is denied, confirm the project and your role with an administrator.",
        "If another member changed the data and your save is rejected, reopen the form, review the latest values, and apply your changes again.")),
    section("notifications", "Configure personal notifications", paragraph("Under **Personal settings**, open **Notifications** to choose event categories and connect Telegram or browser notifications. Preferences apply to your account in the current company. The bell in the main sidebar opens the event feed beside the menu; its **Notification settings** gear returns to these preferences."),
      articles("notifications")),
  ],
};
