import { articles, bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";

export const notificationChannelArticles: DocArticle[] = [
  {
    id: "telegram-notifications",
    title: "Connect Telegram notifications",
    description: "Link your Falcon account to @Falcon_tms_bot and receive messages about selected company events.",
    group: "notifications",
    keywords: ["Telegram", "telegram", "bot", "Falcon_tms_bot", "Start", "connect", "notifications"],
    related: ["notifications", "browser-notifications", "company-access"],
    sources: [{ title: "Telegram: how bot start links work", url: "https://core.telegram.org/bots/features#deep-linking" }],
    sections: [
      section("before", "Before connecting", paragraph("Sign in to your company's Falcon with your own account and open **Notifications**. The bot connects to a personal Telegram chat. Groups and channels are not used for this subscription."),
        note("Start from Falcon", "Finding @Falcon_tms_bot in Telegram and pressing Start is not enough. Falcon's Open bot button contains a personal link that associates Telegram with your account and company.")),
      section("connect", "Connect the bot", steps(
        ["Get a link", "In the Telegram row, click Connect, then Open bot."],
        ["Press Start in Telegram", "Check that the correct Telegram profile and @Falcon_tms_bot are open. Press Start. The bot asks you to return to Falcon to confirm."],
        ["Return to Falcon", "On Notifications, click I pressed Start. Wait for the offer to connect the account bearing your Telegram name."],
        ["Confirm your account", "Check the name and click Confirm. The expanded section shows Telegram is connected, with Disconnect on the right. Clicking the Telegram heading expands or collapses its details."],
        ["Choose messages", "Enable the categories you want under Event preferences. These preferences are shared by Telegram and the browser."]),
        note("The link lasts 10 minutes", "Press Start and confirm the account in Falcon within that time. The link is single-use. Do not forward it to colleagues: everyone connects the bot from their own account.")),
      section("messages", "What messages look like", paragraph("A message contains an event heading, brief test or defect details, and a button to open Falcon. For example, when a fix is ready for retest, the bot offers to open the defect and verify it."),
        bullets("The button opens the TMS for the company where the event occurred. If your session expired, sign in first.",
          "Attachment files and internal logs are not forwarded into chat. Evidence and full details remain available in Falcon.",
          "Messages cover new events after connection. Earlier history is not sent."),
        articles("notifications")),
      section("disconnect", "Disconnect or change accounts", paragraph("Click **Disconnect** in the Telegram row. To use another account, connect again and choose the right profile in Telegram. Browser settings and the Falcon feed are preserved."),
        paragraph("If the bot is blocked in Telegram, unblock it first. Then check the connection in Falcon and reconnect if needed.")),
      section("problems", "If connection is incomplete", table(["What you see", "What to do"],
        ["The bot did not connect after search or a normal Start", "Return to Falcon and use Open bot from your connection flow. An ordinary chat without the personal link cannot identify your Falcon account."],
        ["The link expired", "Refresh Notifications and click Connect or New link. Open the new link and complete both confirmations within 10 minutes."],
        ["Start was pressed, but Falcon does not show a name yet", "Click I pressed Start. Check that you used the latest link from this company. Get a new link if it expired."],
        ["Falcon asks you to confirm someone else's name", "Do not confirm it. Wait until 10 minutes have passed since the link was issued, refresh the page, and reconnect from the correct Telegram profile."],
        ["The bot is not configured; the button is unavailable", "The server channel is not configured. Contact the Falcon administrator. Employees do not need to create a bot or enter a token."],
        ["Telegram is connected, but there are no messages", "Check categories and new company events. Make sure the bot is not blocked. If messages still do not arrive, follow Notifications and events troubleshooting."])),
    ],
  },
  {
    id: "browser-notifications",
    title: "Enable browser notifications",
    description: "Allow Falcon notifications in Chrome or Safari, check site settings, and manage the current browser's connection.",
    group: "notifications",
    keywords: ["browser", "push", "Chrome", "Safari", "permission", "notifications", "blocked"],
    related: ["notifications", "telegram-notifications", "company-access"],
    sources: [
      { title: "Chrome: manage site notifications", url: "https://support.google.com/chrome/answer/3220216?hl=ru" },
      { title: "Safari on Mac: website notifications", url: "https://support.apple.com/ru-ru/guide/safari/sfri40734/mac" },
    ],
    sections: [
      section("enable", "Enable on this device", steps(
        ["Open Falcon in a browser", "Sign in at your company's HTTPS address in a normal Chrome or Safari window and open Notifications."],
        ["Turn on the switch", "In **Browser notifications**, enable the switch on the right. It is available even when the section is collapsed. The permission request appears after your action."],
        ["Allow site notifications", "Allow notifications in the browser's system prompt. If permission was already granted, you may not see another prompt."],
        ["Check the connection", "Click the section heading and wait for **Notifications are enabled in this browser**. Choose categories in **Event preferences**. Both browser permission and the Falcon connection must be enabled."]),
        note("Separate for every browser", "The connection belongs to the current browser, profile, and company address. Repeat these steps on another computer or browser.")),
      section("permission", "If you previously blocked notifications", paragraph("Falcon cannot change a site's blocked permission itself. Change the browser permission first, then refresh Falcon and enable **Browser notifications** if needed."),
        table(["Browser", "Where to check permission"],
          ["Chrome", "Settings → Privacy and security → Site settings → Notifications. Find your company address and allow notifications. Use a normal window: notifications are unavailable in Incognito mode."],
          ["Safari on Mac", "Safari → Settings → Websites → Notifications. Check site permission and whether sites may ask for it. In macOS System Settings → Notifications, check notification permission and banner display for the site."])),
      section("session", "When notifications appear", bullets(
        "The event must occur after connection and belong to a selected category in this company.",
        "Falcon checks your active session before displaying a notification. Sign in again after signing out or session expiry: messages are not shown without a verified session.",
        "Clicking the notification opens the relevant Falcon record. Company and record access permissions still apply.",
        "Display while the tab is closed or in the background depends on the browser and operating system. Do Not Disturb, OS notification preferences, and connectivity can affect banners.")),
      section("disable", "Disable notifications", paragraph("Turn off **Browser notifications**. This disconnects the current browser. Telegram, other connected browsers, and the event feed remain available."),
        paragraph("You can disconnect an already connected browser in Falcon even after blocking site notifications. Restore site permission before reconnecting it.")),
      section("problems", "If no banner appears", table(["Situation", "What to check"],
        ["This browser does not support push notifications", "Open the company's HTTPS address directly in a normal window of a current Chrome or Safari version. Another app's embedded browser may not support notifications."],
        ["The server channel is not configured yet", "Send the message to the Falcon administrator. This is server channel configuration, not a problem with your site permission."],
        ["Permission is granted, but the switch is off", "Enable Browser notifications and wait for connection to complete. Site permission alone is not enough."],
        ["Falcon says notifications are enabled, but no banners appear", "Check the category, event time, company sign-in, site permission, and OS notification settings. To test, open Falcon and wait for the next normal work event."],
        ["You changed browser or profile, or cleared site data", "Sign in to Falcon and check the channel state. Reconnect if the connection is missing."]),
        paragraph("If the problem persists, give your administrator the browser name and version, device, company address, event time, and Falcon event link."),
        articles("notifications")),
    ],
  },
];
