import { articles, bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";
import { notificationPreferencesWalkthrough } from "../walkthroughs/notifications/preferences";

export const notificationsArticle: DocArticle = {
  id: "notifications",
  title: "Notifications and events",
  description: "Choose which changes to receive through Telegram and your browser, and view company events in Falcon.",
  group: "notifications",
  keywords: ["notifications", "events", "alerts", "notifications", "subscription", "retest"],
  related: ["telegram-notifications", "browser-notifications", "integration-overview", "retest"],
  sections: [
    section("start", "Where to configure notifications", steps(
      ["Open your company", "Sign in to Falcon with your own account. Choose Notifications in the main sidebar. These settings are in TMS; no admin panel access is required."],
      ["Connect a channel", "Enable browser notifications or connect Telegram. You can use both. Each employee connects their own channels."],
      ["Choose events", "Expand Event preferences and enable the categories you want. Changes save immediately; there is no separate Save button."]),
      note("Before your first connection", "All categories are selected by default, but no channel is enabled automatically. Detailed connection instructions follow below."),
      articles("telegram-notifications", "browser-notifications")),
    section("walkthrough", "Walkthrough: check preferences and the feed", notificationPreferencesWalkthrough),
    section("scope", "Who receives messages", bullets(
      "Preferences are personal and apply within the selected company. Administrators do not subscribe employees automatically.",
      "Events from all company projects are included. Switching the project in the header does not restrict the subscription to that project.",
      "The same category selection applies to Telegram and connected browsers. Separate category choices for each channel are not currently available.",
      "Mentions and assignments notify only the named employees. Selecting yourself also sends a notification. Other categories report shared company events.",
      "If you have accounts in several companies, configure notifications separately in each.",
      "After connection, new matching events are delivered. Earlier events are not sent again.")),
    section("categories", "Event preferences", table(["Category", "Changes reported"],
      ["Test runs", "Creation of a standard run or fix-verification run; starting, completing, and stopping a run; changing a test result and starting another attempt."],
      ["Defects", "Defect creation and updates, status changes, and fix confirmation. Also includes processed YouTrack updates to linked defects and tracker signals that a fix is ready for retest."],
      ["Test cases", "Creation, cloning, new revisions, archiving, restoration, and personal mentions."],
      ["Assignments", "Assignment as a case owner, run case executor, or assignee for a defect, project, or portfolio."],
      ["Test suites", "Creation, changes, and archiving of a suite. There is currently no separate suite restoration notification."],
      ["Integrations", "This category is already present in preferences. Separate personal messages for GitHub releases and GitHub Actions failures are not yet sent. Enable Test runs and Defects for runs created and defects updated by integrations."]),
      paragraph("To receive only defect-related messages, leave **Defects** enabled. Also enable **Test runs** to follow execution. Turning off every category stops messages through both channels while preserving Falcon's event feed.")),
    section("assignments", "Assignment notifications", paragraph("Enable **Assignments** to receive personal messages when assigned a case, a test within a run, a defect, a project, or a portfolio. Changing executors for selected run cases creates events for each changed test; a bulk assignment may produce several messages."),
      note("Run assignee is a separate field", "It does not replace case executors within the run. Changing it does not create a separate personal run-assignee notification."),
      paragraph("An unchanged assignee does not receive another notification. Changing the assignee notifies the new employee. Clearing an assignment cancels a notification that has not yet been sent. Delivered messages remain in history. Assigning yourself also sends a notification.")),
    section("integrations", "Events from integrations", paragraph("First configure the relevant service under **Hooks** for the selected project. Connecting Telegram alone does not link Falcon to a tracker or enable incoming status updates."),
      steps(
        ["Link the defect to an issue", "For YouTrack, Trello, Jira, or Linear, the Falcon defect must be linked to the external issue. Configure incoming events and status mapping in the integration."],
        ["Enable Defects", "When a configured integration sends fix readiness for retesting and Falcon accepts the change, a Fix ready for verification message is sent. Moving an unlinked card does not create this message."],
        ["Open the test", "The message button opens the linked defect in your company's Falcon. Retest and record the result; enable Test runs for messages about the run itself."]),
      paragraph("YouTrack updates belong to **Defects**. If GitHub creates a run through a configured rule, its creation message belongs to **Test runs**. Subscribing does not mean being notified about every action in an external service."),
      paragraph("Slack delivery and Confluence report publishing are configured separately in Hooks. Connecting Swagger does not create a personal alert. Enabling Integrations does not replace service configuration."),
      articles("youtrack", "trello", "jira", "linear", "github")),
    section("feed", "The Falcon event feed", bullets(
      "Expand Recent activity to view supported company events, even without Telegram or a connected browser.",
      "Categories control message delivery, not this feed. Disconnecting a channel does not remove events from it.",
      "Click an event title to open its run, defect, case, or suite. The event is marked read for your account.",
      "The checkmark marks an event read without opening it. This does not change its read status for other employees.",
      "Click Refresh for the latest list or Show more for earlier events.",
      "Opening a Telegram or browser notification does not mark the event read in Falcon's feed.")),
    section("mentions", "Mentions in comments", steps(
      ["Open case comments", "Write a message or click a comment's reply arrow. Replies use the shared field above the feed, with a quote of the original message inside."],
      ["Choose employees", "Click Mention and find colleagues by name or email. You can select up to 20 employees in your company."],
      ["Recipient notification", "A mention automatically sends a personal message through connected Telegram and permitted browser notifications if the recipient has Test cases enabled. Mentioning yourself works the same way. The Slack checkbox additionally posts to the shared project channel."],
      ["Post the comment", "Mentioned employees see the event in Falcon. Browser push requires both the channel and Test cases category to be enabled. Mentioning yourself also creates a personal notification. A normal reply without selecting an employee through Mention does not create a mention."]),
      articles("case-comments"),
      paragraph("The comment menu lets you edit your text or delete your message. Administrators and QA managers can also delete others' comments. Replies remain after the original message is deleted. Editing notifies only newly mentioned employees. Messages already sent to Telegram or Slack are not automatically deleted.")),
    section("delivery", "If a message does not arrive", steps(
      ["Check the company and time", "Make sure the event happened in the company where the channel is connected, after connection. Older events remain only in the feed."],
      ["Check the category", "For example, a defect becoming ready for retest belongs to Defects even when its status comes from an external tracker."],
      ["Check the channel state", "Expand Telegram and Browser notifications. Check for Telegram is connected and Notifications are enabled in this browser, and confirm that the browser switch is on. Start confirmation and site permission are required to finish connecting."],
      ["Check the event itself", "Click Refresh in the feed. If an expected tracker update is missing, check that integration's log in Hooks."],
      ["Contact your administrator", "If the event exists and its category is selected but the connected channel is silent, share the event time, link, company name, and channel. Do not send your password, bot token, or personal connection link."]),
      paragraph("Delivery runs in the background. Falcon retries temporary service failures, so a message may arrive later. An ambiguous Telegram network failure can cause a duplicate message for the same event."),
      articles("telegram-notifications", "browser-notifications", "integration-troubleshooting")),
  ],
};
