import { bullets, code, note, paragraph, section, steps, success, table, warning, type DocArticle } from "../../model/article";
import { createCaseWalkthrough, editCaseWalkthrough } from "../walkthroughs/cases/authoring";
import { archiveCaseWalkthrough } from "../walkthroughs/cases/archive";
import { archiveFoldersWalkthrough } from "../walkthroughs/folders/lifecycle";
export const caseAuthoring: DocArticle[] = [
  { id: "create-test-case", title: "Create a test case", group: "cases", description: "Describe a reproducible test: conditions, actions, and a specific expected result.",
    keywords: ["create", "test case", "test case", "scenario", "new case", "checklist", "fields", "product", "regression", "location"], related: ["edit-test-case", "custom-fields", "custom-field-values", "falcon-ai-writing", "shared-steps", "create-run"],
    sections: [
      section("open", "Open a new case", paragraph("Select a project. In **Test cases**, click the round **+** button to create a case. You can also open a folder's menu in the tree and choose **New test case** to fill in its location automatically. Every entry point opens the same editor with the same fields and save actions.")),
      section("from-portfolio", "From a portfolio to the shared editor", steps(
        ["Open the project", "In the main sidebar, choose **Portfolios and projects**, then the portfolio and project you need."],
        ["Open its cases", "In the project overview, open **Test cases**. Select an active folder in the tree; if it is empty, use **Create case** in the empty list."],
        ["Fill in the standard case form", "The **+** button, folder menu, and empty-folder action all open the same editor shown below. Selecting a folder fills in the location automatically; there is no separate portfolio or project case form."])),
      section("walkthrough", "Create a case step by step", createCaseWalkthrough),
      section("share-comment", "Share a comment", paragraph("In a comment's **⋯** menu, choose **Share**. Falcon copies a link to that specific message. Send it to a colleague with project access: the case opens, the reply thread expands, and the screen scrolls smoothly to the message. If the browser blocks copying, copy the link from the field that appears. The link itself does not grant project access.")),
      section("narrative-editing", "Description and preconditions", paragraph("Click the text, empty field, or pencil to start editing. Markdown controls appear below the heading on a transparent background. **Apply** finishes editing that section in the current draft; **Cancel** restores its previous value. To save a new case, click **Create** at the bottom right of the form. Links in the text open with a normal click.")),
      section("fields", "Fill in the case", table(["Field", "What to enter"],
        ["Title", "One testable behavior: Sign in with a valid password, rather than Authentication."],
        ["Description", "The test's purpose and business context, if not clear from the title."],
        ["Preconditions", "The system state before the test: a user exists, the cart is empty, or the required plan is active."],
        ["Location", "A repository folder. Select an existing path or prepare a new one in the folder selector."],
        ["Custom fields", "Product group, product, regression flag, and additional fields configured for the project."],
        ["Properties", "Readiness status, priority, type, and time estimate."],
        ["Additional details", "Test data, the case assignee, tags, and a revision comment."])),
      section("placement", "Location and folder path", paragraph("On the right of a new case, open **Location → Folder**. For an existing case, the folder selector appears while editing **Custom fields**. The path is shown as names separated by arrows; `/` means the root with no folder."),
        steps(["Find a folder", "Click Folder and type part of the path. Select a matching row."],
          ["Prepare a new folder if needed", "Enter a new path, such as Mobile/Android, and click the explicit Create folder action for that path. Typing alone does not change the location."],
          ["Save the case", "The new folder is created when the case is saved. Canceling the draft before saving does not create a folder from the entered path."]),
        paragraph("The up and down arrows move focus through options; Escape closes the list. Enter selects an exact path, or prepares a new one if nothing matches. If search matches only part of an existing path, Enter first focuses the matching option.")),
      section("custom-fields", "Product group, product, and regression", paragraph("In **Custom fields**, select **Product group** first, then **Product**. **Regression** accepts true or false and defaults to false when saved. Additional fields appear here after configuration in the project's catalog. Required fields have an asterisk."),
        paragraph("Every list supports search. With permission, you can add a new option through **Create “…”** directly in the list. Exact duplicates are not created; similar options require separate confirmation. Changing the group clears an incompatible product. Leave the group empty for a legacy ungrouped product."),
        note("Saving a value and saving a case", "Adding a value saves it to the catalog immediately. Selecting that value for a new case remains a draft until you click Create at the bottom right. Canceling the case does not delete the catalog value already added.")),
      section("additional-details", "Additional details", paragraph("On the right, under **Additional details**, enter test data, select the case assignee, add comma-separated tags, and optionally enter a revision comment. Test data supports Markdown. The case assignee does not replace the assignee for the entire run."),
        paragraph("In a saved case, this section also shows the case author and revision author. Changing the assignee does not rewrite authorship. Empty test data, tags, and comments appear as Not specified.")),
      section("scenario", "Build the scenario", steps(
        ["Add an action", "Add a step under Scenario. Describe an action a tester can perform without verbal explanation."],
        ["Describe the expected result", "Specify an observable outcome: a screen, value, message, or state change. Everything works is not specific enough."],
        ["Continue the scenario", "Use Add step for subsequent actions or insert a shared step. Use the editor's available actions to reorder or repeat steps."],
        ["Create the case", "Click Create at the bottom right and check that the case has a project key. It can now be included in suites and runs."])),
      section("api-steps", "Requests and code in steps", paragraph("Actions, expected results, and test data support Markdown. Click the text or pencil to edit a field. The compact toolbar offers bold, inline code, code blocks, and lists. Moving to another field or clicking the checkmark displays the formatted text."),
        paragraph("Use inline code for HTTP methods, paths, and statuses: `POST /v1/transfers`, `201 Created`. For JSON, SQL, or multiline requests, select the text and click **Code block**. You can also paste Markdown with triple backticks and a language such as json. A line break stays within the current step; use **Add step** for a new action. Formatting appears in both saved cases and runs."),
        paragraph("When you paste normally from a browser, Falcon converts headings, nested lists, links, tables, and code blocks to Markdown. Conversion happens immediately in the draft without sending text to an external service. Blur the field or click the checkmark to see the result. Undo with Ctrl+Z or ⌘Z. Pasting inside code preserves literal text. If the source provides plain text only, Falcon preserves it as supplied; to recover previously lost structure, copy it from the original source again.")),
      section("example", "Example of a clear test", code("text", "Example case content", "Title: Sign in with a valid password\nPrecondition: an active test user exists\n\n1. Open the sign-in page\n   Expected: username and password fields are available\n2. Enter valid credentials and submit the form\n   Expected: the user's workspace opens\n\nTags: auth, smoke\nEstimate: 3 minutes"),
        note("Test data", "Use dedicated test accounts and anonymized examples. Store real passwords and tokens in your team's approved secrets store; include instructions or a reference for obtaining access in the case.")),
      section("check", "Check before running", bullets("The scenario has a clear starting point and final outcome.", "Preconditions do not duplicate test actions.", "Expected results distinguish success from failure.", "Required fields are filled in and the product belongs to the selected group.", "The folder, product, regression flag, priority, and tags help place the case in the right suite.")),
    ] },
  { id: "edit-test-case", title: "Editing and revisions", group: "cases", description: "Maintain the test repository while distinguishing the current case from the snapshot in a run.",
    keywords: ["edit", "revision", "revision", "history", "markdown", "attachments", "fields"], related: ["create-test-case", "custom-fields", "custom-field-values", "falcon-ai-writing", "shared-steps", "retest"],
    sections: [
      section("edit", "Edit an existing case", steps(
        ["Open the case", "Find the case by ID or title and select its row. Expand the details to full screen if needed."],
        ["Edit the relevant section", "Click the edit icon beside the title, description, preconditions, scenario, or properties. Update the test's meaning and data in their corresponding sections."],
        ["Save and review", "Save your changes and reread the updated case. History shows linked bug reports and their events; it does not replace revision comparison. If saving fails, read the message and keep the unsaved text open."])),
      section("walkthrough", "Edit step by step", editCaseWalkthrough),
      section("custom-fields", "Edit fields on the right", paragraph("Click the pencil beside **Custom fields** to change the location, product group, product, regression flag, and other project fields. Search and value creation are available in the list beside the selected field. Changing the group clears an incompatible product; check your new selection before saving."),
        paragraph("The checkmark or section-level **Apply** finishes a local edit in the draft. The main **Save** button records a new case revision. Saving validates required fields and the product/group relationship even if your main edit only changed scenario text.")),
      section("format", "Formatting and evidence", paragraph("The description editor supports emphasis, lists, and links. Scenarios consist of individual steps with expected results. Attachments are available in the case details; comments help the team discuss changes."),
        note("Keep instructions and results separate", "A screenshot of an expected state can belong to the case. A screenshot of an actual failure belongs to step execution or a defect.")),
      section("snapshot", "What happens to an existing run", table(["Location", "Content shown"],
        ["Test case repository", "The current saved revision."], ["Existing run", "The revision snapshot recorded for that run."],
        ["New run", "The version selected by the system when assembling the new run."]),
        warning("Editing does not rewrite history", "If requirements change, create a new run with the current case. Do not treat an old passing result as verification of a new scenario.")),
    ] },
  { id: "archive-test-case", title: "Archive and restore a case", group: "cases", description: "Remove an outdated test from the active repository and bring it back when needed.",
    keywords: ["delete", "delete test case", "delete", "archive", "archive", "quarantine", "quarantine", "restore"], related: ["organize-cases", "edit-test-case"],
    sections: [
      section("meaning", "How deletion works in Falcon", paragraph("Test cases use **archiving**. It removes a case from the normal active list and new selections while preserving test history. The current case view has no permanent delete button.")),
      section("walkthrough", "Archive and restore step by step", archiveCaseWalkthrough),
      section("folder-walkthrough", "Walkthrough: multiple cases or an entire folder", archiveFoldersWalkthrough),
      section("archive", "Archive a case", steps(
        ["Check the project and case", "Open the case you need. Verify its key, title, and reason for retirement."],
        ["Archive it", "Click Quarantine at the top of the case details. This archives the case while preserving history. Follow any confirmation shown by the interface."],
        ["Check the list", "The case should no longer appear in the normal active selection. Enable archived records in the filters to verify the result."])),
      section("restore", "Restore a case", steps(
        ["Show archived records", "Open the list filters and include archived cases. Find the record by key or title."],
        ["Return it to active use", "Open the case and click Restore. Review the scenario for relevance before the next run."])),
      section("archived-view", "View an archived case", paragraph("An archived case opens in the same details view: you can read its scenario and history, copy its ID or link, and expand the view. Editing, running, and copying become available after restoration. You cannot create cases in an archived folder; restore the branch first.")),
      section("bulk", "Archive multiple cases", paragraph("Select cases in the tree or enable selection in the table. You can combine cases from different folders. In the selection toolbar, click **Archive**, check the count, and confirm. To restore individual cases, include archived records in the filters and use the standard case details view."),
        note("Remove from folder is a separate action", "**Remove from folder** moves cases to **No folder** and keeps them active. To retire an entire branch, open the folder menu and choose **Archive folder**. Restore such a branch from the folder archive, starting at its root.")),
      section("history", "What stays in history", success("Results are preserved", "Case snapshots in earlier runs and the context of registered defects are not replaced by a deleted row. The team can still review exactly what was tested."),
        paragraph("If you only want to delete a scenario action, use the step menu → Delete in the editor. This changes a revision rather than archiving the entire case.")),
    ] },
];
