import { folderWalkthrough } from "../walkthroughs/folders/create";
import { importFoldersWalkthrough } from "../walkthroughs/folders/lifecycle";
import { sharedStepsWalkthrough } from "../walkthroughs/shared/steps";
import { bullets, note, paragraph, section, steps, table, warning, type DocArticle } from "../../model/article";
export const caseOrganization: DocArticle[] = [
  { id: "shared-steps", title: "Shared steps", group: "cases", description: "Create reusable procedures once and insert them into project scenarios.",
    keywords: ["shared steps", "shared step", "reuse", "authentication", "template"], related: ["create-test-case", "edit-test-case"],
    sections: [
      section("walkthrough", "Walkthrough: a procedure with an image and a file", sharedStepsWalkthrough),
      section("use", "When to use shared steps", paragraph("Use a shared step for a procedure repeated across tests, such as signing in, preparing an order, or clearing test data. Shared steps belong to a project.")),
      section("create", "Create a procedure", steps(
        ["Open Shared steps", "Click Shared step at the top of the list."],
        ["Give it a clear name", "For example, Sign in as a user with an active subscription. The name should describe the procedure's outcome."],
        ["Add actions", "Fill in the action and expected result for each item. Saving requires a name and at least one completed step; empty expected results prevent saving."],
        ["Save", "Return to the list and check the version, step count, and usage count."])),
      section("attachments", "Images and files", paragraph("Click the paperclip below a step or paste an image from the clipboard into its action or expected result. Attachments appear with that same step when the block is used in a test case."),
        bullets("Up to 20 new files per save and up to 20 attachments per step.", "Images can be enlarged for viewing; files can be opened or downloaded.", "Removing a file in the editor excludes it from the new version. Earlier versions and run snapshots retain the attachment."),
        note("If an upload is interrupted", "Keep the editor open and click Save again. The saved block and files already uploaded will not be duplicated.")),
      section("insert", "Insert into a test case", steps(
        ["Open the scenario editor", "In the case details, edit the Scenario section."],
        ["Choose the procedure", "Open Add step and find the name under Shared step."],
        ["Check the inserted block", "Expand the block, review its actions, and save the case. You cannot insert nested shared steps into the procedure editor itself."])),
      section("remove", "Delete from the library", paragraph("On **Shared steps**, click the trash icon to the right of a block and confirm deletion. You do not need to open the editor."),
        note("Existing tests are preserved", "The block disappears from the list and from selection for new uses. Cases already using it, run history, and attachments remain available. Deleting from the library does not delete files or rewrite earlier results.")),
      section("change", "Updates and versions", paragraph("Open the procedure in Shared steps, edit its contents, and save a new version. Check the block version in cases that use it: an existing run keeps its own snapshot."),
        note("Review after changing a procedure", "After updating a shared procedure, open affected scenarios and make sure their preconditions and expected results are still consistent.")),
    ] },
  { id: "organize-cases", title: "Folders and case organization", group: "cases", description: "Build a project tree, select cases across folders, and move them while preserving history.",
    keywords: ["filter", "search", "folder", "tree", "subfolder", "product", "product group", "regression", "component", "tag", "QL", "selection", "move", "hold", "long press", "no folder"], related: ["create-test-case", "test-suites", "archive-test-case", "import-export"],
    sections: [
      section("portfolio-scope", "Project or portfolio", paragraph("On **Test cases**, click the project name in the global header. On **Projects**, select one or more projects; on **Portfolios**, select one or more portfolios. Click **Apply**. Portfolios show all their active projects. Both lists support search; click a selected item again to deselect it."),
        bullets("Within a portfolio, each project appears as a separate expandable branch with its own folder tree. Same-named folders from different projects are not merged.", "The arrow to the right of a branch name opens that project alone. Enter the relevant project for creation, import, and bulk actions.", "Search, QL, and filters apply across the portfolio's loaded cases. Large branches expand in batches through Show more; search also includes cases not yet displayed.", "Opening a case or reloading the page preserves the selected projects or portfolios. If a project fails to load, its branch shows an error and a retry action.")),
      section("assignee-filter", "Filter by assignee", paragraph("Click the filter button to the right of **QL**, then **Assignees**. Find members by name or email and select one or more. **Unassigned** shows cases without an assignee; **All assignees** removes the restriction. Clicking outside the menu closes it."),
        paragraph("This filter is also available in suite contents and settings, and when choosing cases for a new run. During execution, the filter uses assignments from that specific run.")),
      section("repository", "The project tree", paragraph("Open **Test cases** in the global sidebar or the tab of the same name on a project page. Both use the same repository and editor. The selected project's **Repository** appears on the left with folders, subfolders, and their cases. Initially, branches expand down to folders directly containing cases; those folders themselves stay collapsed. For example, with four nested levels and cases at the last level, the first three expand. Manual expansion or collapse is preserved when data refreshes; search and navigation to a case reveal the needed branch. A folder arrow expands its contents; a case name opens its details on the right. Vertical lines connect levels: click an expanded branch's line to collapse it. Until you select a case, the right pane shows a hint. On narrow screens, details fill the work area; close them to return to the tree."),
        bullets("The tree shows the current project's repository. **No folder** contains cases at the root, outside named folders.",
          "Empty folders remain in the tree after a page reload. You can prepare them before creating cases.",
          "Choose **New test case** in a folder menu to open the shared editor with the location already selected. Fields and saving work the same from every creation entry point.")),
      section("tree-width", "Adjust the tree width", paragraph("Drag the repository's right edge to make long names easier to read. The selected case retains space to the right of the tree. Double-click the divider to restore the default width; your chosen width is remembered.")),
      section("search", "Find a case", steps(
        ["Check the project", "Search works within the current repository. Switch projects if the key belongs to another product."],
        ["Enter a query", "Search finds records by ID, title, assignee name or email, folder, product, or tag."],
        ["Refine the selection", "Open Filters and choose assignees, folders, Product groups, Products, Regression, type, priority, or readiness status. Regression = false means cases without the regression flag; All removes that restriction. Before concluding a case is missing, clear unnecessary filters and check whether archived cases are shown."])),
      section("query", "QL: precise queries", paragraph("**QL** opens a query input with field and value suggestions. Queries support Russian and English and are case-insensitive; the two Russian variants of the letter e are equivalent. Search, QL, and selected filters apply together. Assignee names and emails are available after workspace members load."),
        table(["Query", "Matches"],
          ['assignee: "Anna" AND status: ready', "Ready cases assigned to a member named Anna."],
          ['owner IN ("anna@example.com", "john@example.com")', "Cases assigned to either of two people, matched by exact email."],
          ['priority: (high, critical) AND NOT tag: archived', "High or critical priority, excluding the archived tag."],
          ['(product: API OR product: Mobile) AND type: manual', "Manual cases for either of two products."],
          ['regression: false', "Cases with the regression flag turned off."],
          ['assignee: "Unassigned"', "Cases without an assignee."],
          ['title ~ "Sign in"', "Titles containing Sign in."]),
        bullets("Put phrases containing spaces in quotes. A colon or ~ searches for a substring; = and IN compare complete values. Status, priority, and type always compare catalog values.",
          "AND combines conditions, OR accepts either condition, and NOT excludes matches. Parentheses set evaluation order; without parentheses, AND is evaluated before OR.",
          "A suggestion replaces the condition at the cursor while preserving the rest of the query. Use arrows to select a suggestion, Enter to insert it, and Escape to close suggestions.",
          "The legacy component field still works for compatibility. Use product, productGroup, and regression in new queries.",
          "An incomplete or unknown query displays an error hint and an empty selection. Correct the condition or clear QL. The limit is 4,000 characters.")),
      section("folder", "Create a folder manually", steps(
        ["Open the form", "Click **New folder** in the repository header. To create a nested folder, open its parent's menu and choose **New subfolder**."],
        ["Enter a name", "Enter one folder name, such as Transfers. Use the parent selector for nesting rather than a slash in the name."],
        ["Choose a parent", "In the **Location** tree, expand branches or find a folder by name. Search shows nested matches with their location. Choose the project root for a top-level folder. Right and left arrows expand and collapse branches; up and down arrows move focus."],
        ["Check the path", "Review the parent folder chain and click **Create folder**. If the path already exists, change the name or parent. The folder is saved in the project even when empty."])),
      section("folder-walkthrough", "Folder walkthrough", folderWalkthrough),
      section("quick-add", "Add directly in the tree", paragraph("In normal repository mode, hover over a folder or focus it. Click **Add subfolder**, enter a name, and press Enter or the checkmark. That folder becomes the parent; Escape cancels creation. The **Add test case in this folder** plus button opens the case editor with its location prefilled."),
        note("If quick actions are missing", "Leave selection mode and finish any active edit or move. Creation requires project case management permission.")),
      section("change-folder", "Change the name or location", paragraph("In the folder menu, choose **Name and location**. Change the name or parent and save. The folder's contents move with it. You can also drag a folder into another folder; it cannot be placed inside itself or one of its descendants.")),
      section("structure", "Agree on a structure", table(["Tool", "Use it for"],
        ["Folder", "A scenario's location in the repository."], ["Product group and product", "Project catalog values that classify a test. Products belong to their group; legacy values may remain ungrouped."],
        ["Regression", "A true/false flag identifying regression tests. It does not add a case to a run automatically."],
        ["Tags", "Overlapping attributes: smoke, mobile, checkout."], ["Search and filters", "A temporary selection by relevant attributes without changing folders."],
        ["Test suite", "A repeatable run selection assembled manually or by rules."])),
      section("selection", "Select cases from several folders", steps(
        ["Select cases", "Click **Select** above the tree to show checkboxes beside folders and cases. A folder checkbox selects available cases throughout the branch, including subfolders."],
        ["Continue selecting", "Open another folder and select more cases. Existing selections are preserved when switching folders or changing filters within the project."],
        ["Review the selection", "The selection toolbar count covers the entire selected set, including cases hidden by the current folder or filter. Check the count before a bulk action; clear the selection if needed."])),
      section("move", "Move selected cases", steps(
        ["Choose the action", "After selecting one or more cases, click **Move** in the bulk actions toolbar."],
        ["Choose one destination folder", "Expand the destination tree or search for an active folder by name. Parent levels appear separately rather than as one slash-separated line. All selected cases, including those from different folders, move there."],
        ["Confirm the move", "Check the count and location, then click **Move**. Case keys, history, links, and run results are preserved."]),
        note("Drag and undo", "Drag with a normal mouse movement; no long press is needed. Dragging a selected case or a folder containing selected cases moves the entire selected set. The notification at the bottom right shows the number moved and offers **Undo** for 15 seconds. Undo restores each case to its original folder and does not overwrite newer edits by another person."),
        note("Remove from folder", "**Remove from folder** moves selected cases to **No folder**. They remain active in the same project. Use archiving to retire cases.")),
      section("bulk-actions", "Other selection actions", paragraph("A compact toolbar at the bottom shows the selected case count, **Move**, **Create test run**, **Status**, **Priority**, **Remove from folder**, and **Archive**. Actions depend on your permissions; the cross clears the selection."),
        note("Selection survives an error", "If an operation fails, read the message and retry after resolving the cause. While cases are selected, the floating Verify fixes button is hidden; clearing the selection brings it back if fixes are available for verification.")),
      section("drag", "Move by holding and dragging", steps(
        ["Hold a case", "Press and briefly hold a case row in the tree, then start dragging."],
        ["Check the count", "If the held case is already selected, the entire selection moves. If it is not selected, only that case moves; you do not need to check its box first."],
        ["Drop over a folder", "Hover over the destination folder. Pausing over a collapsed folder expands it so you can choose a subfolder. To move to the root, use the **Move to repository root** area that appears, then release. To choose a destination without dragging, use **Move** in the actions toolbar."])),
      section("folder-archive", "Archive and restore a branch", steps(
        ["Archive the folder", "Open the folder menu, choose **Archive folder**, and confirm. Its active subfolders and cases are archived with it; history and runs are preserved."],
        ["Open the folder archive", "Click the archive icon beside **Folders**. Select the root folder of the branch you archived."],
        ["Restore it", "Choose **Restore folder** in the menu. Folders and cases archived by that operation return; records archived separately before it remain archived."]),
        note("If restoration fails", "Start from the archived branch's root. If an active folder already occupies the same path, rename or move that folder first. Refresh the tree and retry restoration.")),
      section("access", "Permissions and concurrent changes", paragraph("Viewing the tree does not grant permission to change it. If actions are unavailable, check your project case permissions and finish editing any open case. If data has changed, refresh the tree and list, review the selection, and repeat the action.")),
      section("maintenance", "Maintain the repository", bullets("Use agreed product catalog values and tags.", "Split overly long scenarios into independent tests.", "Archive outdated cases and review suites before a release.", "For significant changes, leave a comment explaining the test's new purpose.")),
    ] },
  { id: "import-export", title: "Import and export cases", group: "cases", description: "Upload JSON and import cases with automatic folder preparation.",
    keywords: ["import", "export", "JSON", "v2", "folders", "file history", "download", "preview", "empty folder", "transfer", "continue import", "backup"], related: ["organize-cases", "create-test-case", "workspace"],
    sections: [
      section("walkthrough", "Walkthrough: project and folder", importFoldersWalkthrough),
      section("export", "Export a project", steps(
        ["Select the project", "Open **Settings → Import and export**."],
        ["Export the data", "Download JSON containing current case revisions, their paths, and the active folder structure, including empty folders. See Transfer scope below for what is included."],
        ["Check the file", "Verify the case count and project before using the file to transfer data."])),
      section("import", "Import cases", steps(
        ["Open the import page", "In **Test cases**, click import in the repository header or go through **Settings → Import and export**. A dedicated **Import test cases** page opens. Check the selected **Project**."],
        ["Choose a file", "Click **Choose file** or drag in JSON. You can use a Falcon export or external test case JSON. The limits are 5 MB and 2,000 recognized cases."],
        ["Choose the destination", "In **Folder**, expand the tree or search by folder name; choose **Project root** for the top level. Opening import from a selected folder prefills that destination; check it before starting."],
        ["Start the import", "Click **Import**. Falcon automatically recognizes external JSON, prepares folders, and creates cases. The server uses OpenAI if needed. A preparation error stops case creation. After completion, check the case count, expand the structure tree, and open a few scenarios."])),
      section("file-history", "Source file history", paragraph("Below the form is the selected project's **File history**. New imports retain the original JSON; each row shows the filename, size, author, time, and destination. Search with **Find a file**; click **Load more** for earlier records."),
        bullets("The file menu offers **Open**, **Download**, and **Copy link**. Open shows the source JSON; links lead into Falcon and still require access permission.",
          "**Delete file** requires case management permission. After confirmation, the source file becomes unavailable, but imported cases, folders, and the history record remain.",
          "Read permission allows viewing history and downloading available files. New imports require case management permission. File history does not prove every case in the file was imported successfully; check the operation's result.")),
      section("destination", "How the structure is added", table(["Path in file", "Selected destination", "Result"],
        ["/Transfers/Between accounts", "Project root", "/Transfers/Between accounts"],
        ["/Transfers/Between accounts", "Products", "Products → Transfers → Between accounts"],
        ["/", "Products", "The case is placed directly in Products"],
        ["/", "Project root", "The case is placed in No folder"]),
        note("Existing cases are preserved", "Import adds new records to the current project. It does not match cases by title or overwrite existing scenarios. A folder is reused only when its full path matches.")),
      section("format", "JSON v2 and empty folders", paragraph("The current export uses `saturnusgo.tms.test-cases.v2`. The document may contain a `folders` array with full paths, such as `/Transfers` and `/Transfers/Limit checks`. This preserves folders without cases. A file with an empty `testCases` array and populated `folders` can transfer just the structure."),
        bullets("Earlier v1 and v2 exports without `folders` are supported: the tree is built from case paths.",
          "Paths start with `/`. Empty segments, `.` and `..`, backslashes, and leading or trailing spaces in folder names are not allowed.",
          "A folder name can contain up to 120 characters; the full resulting path, including the import destination, can contain up to 500. Preview checks up to 2,000 folders, including intermediate ones.")),
      section("partial", "If import stops or completes partially", steps(
        ["Review the result", "**Cases completed** counts confirmed saves. Expand **Failed to import** to see original keys and error reasons."],
        ["Continue on this page", "Resolve the cause and click **Continue import**. The file and destination remain fixed; confirmed cases are skipped and unfinished steps are retried."],
        ["Check the repository", "After continuing, verify the result and project tree. If you leave or reload the page, first inspect saved folders and cases. Source file history does not restore the import's continuation point."]),
        note("Stopping does not undo saved work", "Import runs sequentially. **Stop** ends further processing, but created folders and cases remain in the project. Leaving the page stops an unfinished import; a request already sent may still finish saving. To start another import, click **Choose another file** once current processing ends.")),
      section("archive-state", "Archived cases during transfer", paragraph("Export includes archived case contents, but the exchange file does not carry archive state. Import creates active records. If part of the source repository should remain retired, review and archive those cases in the destination project.")),
      section("limits", "Transfer scope", paragraph("JSON transfers the title, description, preconditions, scenario or checklist, test data, type, readiness, priority, tags, time estimate, and location. The compatible text field component contains the product name."),
        warning("A case file is not a TMS backup", "Export does not transfer the custom field catalog, field identifiers and selected values, product/group relationships, regression flags, assignees, attachments, or earlier revisions. Users, integration secrets, runs, and defect history are also excluded. Review classification and assignments separately after transfer."),
        paragraph("CSV is not supported. External JSON structure is recognized automatically, but verify completeness when using a new format. Missing expected results are not generated: the source procedure is preserved in the description, and external cases are created as drafts.")),
    ] },
];
