import { articles, code, note, paragraph, section, steps, table, warning, type DocArticle } from "../../../model/article";
import { swaggerWalkthrough } from "./walkthrough";
export const swaggerArticle: DocArticle = {
  id: "swagger", title: "Swagger · connected APIs", group: "integrations",
  description: "Connect your OpenAPI specification, configure access, and test APIs in Falcon without a separate Swagger session.",
  keywords: ["Swagger", "OpenAPI", "API Testing", "JSON", "YAML", "Basic", "username", "password", "Bearer", "authorization", "docs-json"],
  related: ["api-testing", "integration-overview", "create-test-case"],
  sources: [{ title: "Swagger UI configuration", url: "https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/" }],
  sections: [
    section("purpose", "What connecting provides", paragraph("A **Swagger/OpenAPI** connection is stored at workspace level and can serve several projects. One connection with the relevant projects is enough for a shared backend; create separate connections for microservices. In **API Testing**, choose a project scope or portfolio, then the API. Reading a specification does not require hooks or events.")),
    section("prepare", "Prepare the specification URL", paragraph("Use a direct HTTPS link to **JSON or YAML**, not the HTML Swagger interface. Swagger **2.0**, OpenAPI **3.0**, and **3.1** are supported. Common paths include `/openapi.json`, `/swagger.json`, `/docs-json`, and `/v3/api-docs`. Check your API configuration for the exact path."),
      code("text", "Example URL", "https://api.company.com/openapi.json"),
      note("A public address can require authentication", "The server must be reachable by Falcon over HTTPS on standard port 443. Local addresses, private networks, and redirects are not supported. Enter credentials in the authorization fields, not the URL. For a multifile OpenAPI document, publish a bundled specification with local $ref references. The file limit is 8 MB.")),
    section("connect", "Connect an API", steps(
      ["Open connections", "Choose Swagger in Hooks or click Connections in API Testing. Configuration is available to administrators and QA managers."],
      ["Add the specification", "Click Connect API. Enter a name and direct link to OpenAPI JSON or YAML."],
      ["Configure document access", "Under Documentation access, choose No authorization, Username and password, or Bearer token. Fill in credentials only for a protected specification."],
      ["Choose projects", "Under Used in projects, select the relevant projects. For a shared API, choose All workspace projects."],
      ["Save the connection", "Leave API enabled on and click Save API in the panel header. If an error appears, check the address and access before saving again."],
      ["Open API Testing", "Choose the scope and API service. To execute requests, select Request server separately; operations are view-only until then."])),
    section("visual-flow", "Connection settings walkthrough", swaggerWalkthrough),
    section("access", "Two independent authorization layers", table(["Where", "Purpose", "How it works"],
      ["Hooks → Swagger", "Read protected JSON/YAML", "HTTP Basic uses a username and password; Bearer uses a token. Falcon stores them encrypted and sends them only to the specification server."],
      ["API Testing → Authorize", "Execute protected API operations", "Enter an API token or other credentials according to your specification's security scheme. Documentation credentials are not inserted into API requests."]),
      paragraph("Falcon has no mandatory 15-minute Swagger session. Reloading the specification uses saved connection settings. **Your API controls API token expiry**; the integration does not disable it. Request authorization is not preserved across page reloads.")),
    section("requests", "Execute a request and record the result", steps(
      ["Find an operation", "Use the Swagger filter and expand the required method."],
      ["Check the server", "Select **Request server** above the specification, even if only one address is available. Make sure the test data is appropriate for that environment."],
      ["Authorize with the API", "If the operation requires access, click Authorize and enter credentials for the API itself."],
      ["Fill in parameters", "Click Try it out, enter path/query parameters or a JSON body, then Execute. This sends a real request to the selected API server."],
      ["Review the response", "Check Server response for the actual HTTP status, response body, and execution time. The documented Responses section describes the contract, not the result of your request. Record the result and evidence in the relevant Falcon case or run step."]),
      warning("Execution from the browser", "For Execute, the API server must allow CORS from your Falcon origin, including the required methods and authorization headers. Falcon's HTTPS page sends requests to HTTPS APIs. A CORS error does not mean the specification connection is wrong. Swagger requests do not become run results automatically.")),
    section("manage", "Edit the connection and project scope", paragraph("**Refresh API** reloads the specification. To change the address, name, or access, open **Connections** and select the API. Changes apply to every linked project."),
      paragraph("To remove an API from just one project, deselect that project under **Used in projects** and save. To disable the entire connection, turn off **API enabled**. Do not duplicate a specification merely to switch projects. Cases and run results are preserved.")),
    section("troubleshooting", "If the connection fails", table(["What you see", "What to check"],
      ["The response is not a specification", "The link points to a Swagger HTML page or sign-in form. Use a direct JSON/YAML endpoint."],
      ["Swagger rejected access", "Check that authorization is enabled, the method is correct, and documentation credentials are valid."],
      ["The address redirects the request", "Copy the final address. Falcon does not forward passwords through redirects."],
      ["External references in the specification", "Publish bundled OpenAPI with local $ref references instead of separate-file links."],
      ["No response within 15 seconds", "Check server availability and retry. This is a download timeout, not a session lifetime."],
      ["No connection in the project", "Check the project scope, API assignments to those projects, and API enabled."])),
    section("next", "Related instructions", articles("api-testing", "create-test-case", "execute-run")),
  ],
};
