export interface Partner {
    id: string
    name: string
    logo: string
    category: "restaurants" | "hotels" | "cafes" | "events"
    description: string
    website: string
    partnership_type: "strategic" | "integration" | "preferred"
    established: string
    status: "active" | "pilot" | "expanding"
  }
  
  export const partners: Partner[] = [
    {
      id: "marriott",
      name: "Marriott International",
      logo: "/partners/marriott-logo.svg",
      category: "hotels",
      description: "Global luxury hotel chain offering premium accommodations and exclusive member benefits.",
      website: "https://marriott.com",
      partnership_type: "strategic",
      established: "2023",
      status: "active",
    },
    {
      id: "hilton",
      name: "Hilton Hotels",
      logo: "/partners/hilton-logo.svg",
      category: "hotels",
      description: "World-renowned hospitality brand providing exceptional hotel experiences worldwide.",
      website: "https://hilton.com",
      partnership_type: "strategic",
      established: "2023",
      status: "active",
    },
    {
      id: "starbucks",
      name: "Starbucks",
      logo: "/partners/starbucks-logo.svg",
      category: "cafes",
      description: "Leading coffeehouse chain offering premium coffee and café experiences.",
      website: "https://starbucks.com",
      partnership_type: "integration",
      established: "2024",
      status: "active",
    },
    {
      id: "mcdonalds",
      name: "McDonald's",
      logo: "/partners/mcdonalds-logo.svg",
      category: "restaurants",
      description: "Global fast-food restaurant chain with convenient dining and delivery options.",
      website: "https://mcdonalds.com",
      partnership_type: "integration",
      established: "2023",
      status: "active",
    },
    {
      id: "hyatt",
      name: "Hyatt Hotels",
      logo: "/partners/hyatt-logo.svg",
      category: "hotels",
      description: "Premium hotel brand focused on authentic hospitality and personalized service.",
      website: "https://hyatt.com",
      partnership_type: "strategic",
      established: "2024",
      status: "expanding",
    },
    {
      id: "subway",
      name: "Subway",
      logo: "/partners/subway-logo.svg",
      category: "restaurants",
      description: "Fresh sandwich chain offering customizable, healthy fast-casual dining options.",
      website: "https://subway.com",
      partnership_type: "integration",
      established: "2023",
      status: "active",
    },
    {
      id: "eventbrite",
      name: "Eventbrite Venues",
      logo: "/partners/eventbrite-logo.svg",
      category: "events",
      description: "Leading event venue booking platform connecting users with premium event spaces.",
      website: "https://eventbrite.com",
      partnership_type: "preferred",
      established: "2024",
      status: "pilot",
    },
    {
      id: "costa-coffee",
      name: "Costa Coffee",
      logo: "/partners/costa-logo.svg",
      category: "cafes",
      description: "British coffeehouse chain known for premium coffee blends and cozy café atmosphere.",
      website: "https://costa.co.uk",
      partnership_type: "integration",
      established: "2024",
      status: "active",
    },
    {
      id: "pizza-hut",
      name: "Pizza Hut",
      logo: "/partners/pizzahut-logo.svg",
      category: "restaurants",
      description: "International pizza restaurant chain offering dine-in, takeout, and delivery services.",
      website: "https://pizzahut.com",
      partnership_type: "integration",
      established: "2023",
      status: "active",
    },
    {
      id: "intercontinental",
      name: "InterContinental Hotels",
      logo: "/partners/intercontinental-logo.svg",
      category: "hotels",
      description: "Luxury hotel brand providing sophisticated accommodations in prime global locations.",
      website: "https://ihg.com",
      partnership_type: "strategic",
      established: "2024",
      status: "expanding",
    },
    {
      id: "pret-a-manger",
      name: "Pret A Manger",
      logo: "/partners/pret-logo.svg",
      category: "cafes",
      description: "Fresh food and coffee chain specializing in handmade sandwiches and organic coffee.",
      website: "https://pret.com",
      partnership_type: "integration",
      established: "2024",
      status: "active",
    },
    {
      id: "venue-collective",
      name: "The Venue Collective",
      logo: "/partners/venue-collective-logo.svg",
      category: "events",
      description: "Premium event venue network offering unique spaces for corporate and private events.",
      website: "https://venuecollective.com",
      partnership_type: "preferred",
      established: "2024",
      status: "active",
    },
  ]
  