export function administrationCopy(locale: "ru" | "en") {
  return locale === "ru" ? {
    companies: "Компании", employees: "Сотрудники", profile: "Мой профиль", admin: "Управление компанией", sandbox: "Sandbox",
    newCompany: "Создать компанию", newMember: "Добавить сотрудника", back: "Назад", save: "Сохранить", create: "Создать",
    cancel: "Отмена", retry: "Повторить", more: "Показать ещё", search: "Найти по названию, адресу или ИНН", memberSearch: "Найти сотрудника",
    name: "Название компании", personName: "Имя", login: "Логин", email: "Email", phone: "Телефон", role: "Роль", status: "Статус",
    seats: "Участники", address: "Адрес Falcon", contact: "Email для обращений по доступу", contactHelp: "Виден на странице входа вашей компании.",
    companyDetails: "Компания", legalDetails: "Юридические данные", access: "Доступ", administrator: "Главный администратор",
    legalName: "Юридическое название", countryCode: "Код страны", legalForm: "Организационная форма", taxId: "ИНН / налоговый номер",
    registrationId: "ОГРН / регистрационный номер", taxBranchId: "КПП", legalAddress: "Юридический адрес", capabilities: "Возможности Falcon",
    temporaryHelp: "Falcon создаст временный пароль. Передайте его сотруднику лично; при первом входе он установит свой.",
    handoff: "Данные для первого входа", handoffHelp: "Сохраните и передайте эти данные лично. Пароль показывается только сейчас.",
    temporaryPassword: "Временный пароль", copied: "Скопировано", copy: "Скопировать", done: "Готово", noCompanies: "Компаний пока нет",
    noMembers: "Сотрудники не найдены", noResults: "Ничего не найдено", provisioning: "Подключаем адрес", pending: "Ожидает первого входа",
    active: "Активна", suspended: "Приостановлена", archived: "В архиве", blocked: "Заблокирован", revoked: "Доступ отозван",
    verified: "Подключён", failed: "Требуется действие", reserved: "Адрес зарезервирован", verifying: "Проверяем HTTPS", retired: "Отключён",
    memberActive: "Активен", owner: "Главный администратор", mfa: "Двухэтапный вход", enabled: "Включён", notEnabled: "Не настроен",
    resetPassword: "Выдать временный пароль", resetMfa: "Сбросить аутентификатор", block: "Заблокировать", unblock: "Разблокировать",
    revoke: "Отозвать доступ", suspend: "Приостановить доступ", resume: "Возобновить доступ", archive: "Архивировать компанию",
    retryDomain: "Повторить подключение", confirmation: "Подтвердите действие", confirm: "Подтвердить", security: "Безопасность",
    sessions: "Устройства и сессии", currentSession: "Текущая сессия", endSession: "Завершить", logout: "Выйти", openFalcon: "Открыть Falcon",
    oldPassword: "Текущий пароль", newPassword: "Новый пароль", repeatPassword: "Повторите новый пароль", updatePassword: "Изменить пароль",
    mfaCode: "Код из приложения или резервный код", useRecovery: "Резервный код", profileSaved: "Изменения сохранены", passwordSaved: "Пароль изменён. Остальные сессии завершены.",
    loginHint: "Логин изменяет администратор компании.", emailHint: "Для смены email обратитесь к администратору.",
    noPermission: "Этот раздел доступен администратору компании.", returnToFalcon: "Вернуться в Falcon", limit: "Лимит участников",
    requestFailed: "Не удалось выполнить действие. Попробуйте ещё раз.", ownerTransfer: "Передать управление", identityId: "ID нового администратора",
  } : {
    companies: "Companies", employees: "People", profile: "My profile", admin: "Company administration", sandbox: "Sandbox",
    newCompany: "Create company", newMember: "Add person", back: "Back", save: "Save", create: "Create",
    cancel: "Cancel", retry: "Try again", more: "Load more", search: "Find by name, address or tax ID", memberSearch: "Find a person",
    name: "Company name", personName: "Name", login: "Username", email: "Email", phone: "Phone", role: "Role", status: "Status",
    seats: "Members", address: "Falcon address", contact: "Access support email", contactHelp: "Visible on your company’s sign-in page.",
    companyDetails: "Company", legalDetails: "Legal details", access: "Access", administrator: "Primary administrator",
    legalName: "Legal name", countryCode: "Country code", legalForm: "Legal form", taxId: "Tax ID",
    registrationId: "Registration number", taxBranchId: "Tax branch ID", legalAddress: "Registered address", capabilities: "Falcon capabilities",
    temporaryHelp: "Falcon generates a temporary password. Share it privately; the person sets their own password at first sign-in.",
    handoff: "First sign-in details", handoffHelp: "Save these details and share them privately. This password is only shown now.",
    temporaryPassword: "Temporary password", copied: "Copied", copy: "Copy", done: "Done", noCompanies: "No companies yet",
    noMembers: "No people found", noResults: "No results", provisioning: "Connecting address", pending: "Awaiting first sign-in",
    active: "Active", suspended: "Suspended", archived: "Archived", blocked: "Blocked", revoked: "Access revoked",
    verified: "Connected", failed: "Action needed", reserved: "Address reserved", verifying: "Checking HTTPS", retired: "Disconnected",
    memberActive: "Active", owner: "Primary administrator", mfa: "Two-step sign-in", enabled: "Enabled", notEnabled: "Not set up",
    resetPassword: "Issue temporary password", resetMfa: "Reset authenticator", block: "Block", unblock: "Unblock",
    revoke: "Revoke access", suspend: "Suspend access", resume: "Resume access", archive: "Archive company",
    retryDomain: "Retry connection", confirmation: "Confirm this action", confirm: "Confirm", security: "Security",
    sessions: "Devices and sessions", currentSession: "Current session", endSession: "End session", logout: "Sign out", openFalcon: "Open Falcon",
    oldPassword: "Current password", newPassword: "New password", repeatPassword: "Confirm new password", updatePassword: "Change password",
    mfaCode: "Authenticator or recovery code", useRecovery: "Recovery code", profileSaved: "Changes saved", passwordSaved: "Password changed. Other sessions have ended.",
    loginHint: "Your company administrator manages your username.", emailHint: "Contact your administrator to change your email.",
    noPermission: "This section is available to company administrators.", returnToFalcon: "Back to Falcon", limit: "Member limit",
    requestFailed: "Could not complete the action. Please try again.", ownerTransfer: "Transfer ownership", identityId: "New administrator ID",
  };
}
export type AdministrationCopy = ReturnType<typeof administrationCopy>;
