export const enDashboardLayoutMessages = {
  "dashboardLayout.emptyTitle": "Your project. Your perspective.",
  "dashboardLayout.emptyText": "Build a dashboard around what matters to your team. Choose widgets, arrange them, and keep the project’s quality in view.",
  "dashboardLayout.create": "Create dashboard", "dashboardLayout.edit": "Customize",
  "dashboardLayout.add": "Add widgets", "dashboardLayout.addAll": "Add all widgets",
  "dashboardLayout.save": "Save", "dashboardLayout.cancel": "Cancel",
  "dashboardLayout.saving": "Saving…", "dashboardLayout.name": "Dashboard name",
  "dashboardLayout.project": "Shared with the project team", "dashboardLayout.defaultName": "Project overview",
  "dashboardLayout.emptyDraft": "Start with what matters", "dashboardLayout.emptyDraftText": "Add your first widget. You can move and resize everything later.",
  "dashboardLayout.search": "Find a widget", "dashboardLayout.catalog": "Widget library",
  "dashboardLayout.catalogHint": "Pick the signals your team needs. Every widget can be moved independently.",
  "dashboardLayout.live": "Current work", "dashboardLayout.history": "Activity over time", "dashboardLayout.library": "Test library",
  "dashboardLayout.all": "All widgets", "dashboardLayout.added": "Added", "dashboardLayout.close": "Close widget library",
  "dashboardLayout.move": "Move {name}", "dashboardLayout.remove": "Remove {name}",
  "dashboardLayout.up": "Move {name} earlier", "dashboardLayout.down": "Move {name} later",
  "dashboardLayout.size": "Width of {name}", "dashboardLayout.small": "Compact", "dashboardLayout.medium": "Half width", "dashboardLayout.large": "Full width",
  "dashboardLayout.editHint": "Drag the handle to rearrange. Changes appear for the team after saving.",
  "dashboardLayout.dragHelp": "Press Space to pick up a widget, arrow keys to move it, Space to drop or Escape to cancel.",
  "dashboardLayout.picked": "Picked up {name}.", "dashboardLayout.dropped": "Moved {name} to position {position}.",
  "dashboardLayout.dragCancelled": "Move cancelled.", "dashboardLayout.loading": "Loading your dashboard…",
  "dashboardLayout.permission": "You do not have permission to change this project’s dashboard.",
  "dashboardLayout.readOnlyEmpty": "A project administrator or QA manager can create a dashboard for the team.",
  "dashboardLayout.unavailable": "Could not reach the server. Your changes are still here. Retry to safely finish saving.",
  "dashboardLayout.loadError": "Could not load the dashboard. Retry to get the saved version.",
  "dashboardLayout.conflict": "Someone updated this dashboard. Your draft is preserved; load the saved version before editing again.",
  "dashboardLayout.invalid": "The dashboard could not be saved. Check its name and widget configuration.",
  "dashboardLayout.reload": "Load saved version", "dashboardLayout.retry": "Retry",
  "dashboardLayout.noMatches": "No matching widgets", "dashboardLayout.unknown": "This widget is not supported in this version. You can remove it while customizing.",
  "dashboardLayout.outcomes": "Run outcomes", "dashboardLayout.unavailableValue": "No data for this scope",
  "dashboardLayout.metricKind": "Metric",
  "dashboardLayout.visualKind": "Visualization",
  "dashboardLayout.install": "Add",
} as const;
