export const ruDashboardLayoutMessages = {
  "dashboardLayout.emptyTitle": "Ваш проект. Ваш взгляд.",
  "dashboardLayout.emptyText": "Соберите дашборд под задачи команды. Выберите виджеты, расположите их по-своему и следите за качеством проекта.",
  "dashboardLayout.create": "Создать дашборд", "dashboardLayout.edit": "Настроить",
  "dashboardLayout.add": "Добавить виджеты", "dashboardLayout.addAll": "Добавить все виджеты",
  "dashboardLayout.save": "Сохранить", "dashboardLayout.cancel": "Отмена",
  "dashboardLayout.saving": "Сохраняем…", "dashboardLayout.name": "Название дашборда",
  "dashboardLayout.project": "Общий для команды проекта", "dashboardLayout.defaultName": "Обзор проекта",
  "dashboardLayout.emptyDraft": "Начните с главного", "dashboardLayout.emptyDraftText": "Добавьте первый виджет. Положение и ширину каждого можно изменить в любой момент.",
  "dashboardLayout.search": "Найти виджет", "dashboardLayout.catalog": "Библиотека виджетов",
  "dashboardLayout.catalogHint": "Добавьте нужные показатели, затем вернитесь к настройке, чтобы расположить их на дашборде.",
  "dashboardLayout.live": "Текущая работа", "dashboardLayout.history": "Динамика", "dashboardLayout.library": "База тестов",
  "dashboardLayout.all": "Все виджеты", "dashboardLayout.added": "Добавлено", "dashboardLayout.close": "Закрыть библиотеку виджетов",
  "dashboardLayout.move": "Переместить: {name}", "dashboardLayout.remove": "Убрать: {name}",
  "dashboardLayout.size": "Ширина: {name}", "dashboardLayout.small": "Компактный", "dashboardLayout.medium": "Половина ширины", "dashboardLayout.large": "Вся ширина",
  "dashboardLayout.editHint": "Перетаскивайте за ручку, чтобы изменить порядок. Команда увидит изменения после сохранения.",
  "dashboardLayout.dragHelp": "Пробел — взять виджет, стрелки — переместить, пробел — разместить, Escape — отменить.",
  "dashboardLayout.picked": "Перемещается: {name}.", "dashboardLayout.dropped": "{name}: позиция {position}.",
  "dashboardLayout.dragCancelled": "Перемещение отменено.", "dashboardLayout.loading": "Загружаем дашборд…",
  "dashboardLayout.permission": "У вас нет прав на изменение дашборда проекта.",
  "dashboardLayout.readOnlyEmpty": "Администратор проекта или QA-менеджер может создать дашборд для команды.",
  "dashboardLayout.unavailable": "Сервер не ответил. Изменения сохранены в редакторе. Повторите попытку, чтобы завершить сохранение.",
  "dashboardLayout.loadError": "Не удалось загрузить дашборд. Повторите попытку, чтобы получить сохранённую версию.",
  "dashboardLayout.conflict": "Кто-то уже изменил дашборд. Ваш черновик остаётся в редакторе; загрузите сохранённую версию перед новой настройкой.",
  "dashboardLayout.invalid": "Не удалось сохранить дашборд. Проверьте название и настройки виджетов.",
  "dashboardLayout.reload": "Загрузить сохранённую версию", "dashboardLayout.retry": "Повторить",
  "dashboardLayout.noMatches": "Виджеты не найдены", "dashboardLayout.unknown": "Виджет не поддерживается в этой версии. Его можно убрать в режиме настройки.",
  "dashboardLayout.outcomes": "Результаты прогонов", "dashboardLayout.unavailableValue": "Нет данных для выбранных условий",
  "dashboardLayout.metricKind": "Показатель",
  "dashboardLayout.visualKind": "Визуализация",
  "dashboardLayout.install": "Добавить",
  "dashboardLayout.back": "К настройке",
  "dashboardLayout.categories": "Категории",
  "dashboardLayout.selectedCount": "Выбрано: {count}",
  "dashboardLayout.currentValue": "Сейчас", "dashboardLayout.periodValue": "За период",
} as const;
