import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    defaultName: "Release smoke",
    defaultDescription: "Critical checks for the current build",
    error: "The suite was not accepted by the TMS API. Review the selected cases and try again.",
    configureTitle: "Configure test suite",
    createTitle: "Create test suite",
    subtitle: "Save a reusable group of cases for future test runs.",
    name: "Suite name",
    description: "Description",
    mode: "How to choose cases",
    staticMode: "Choose exact cases",
    staticModeHint: "You control the saved list",
    dynamicMode: "Keep updated by tags",
    dynamicModeHint: "Matching cases join automatically",
    tags: "Required tags",
    tagsPlaceholder: "smoke, mobile",
    scope: "in scope",
    dynamicHint: "Updates automatically when matching tags change",
    staticHint: "Exact list maintained by this suite",
    selectVisible: "Select visible",
    clearVisible: "Clear visible",
    reviewCases: "Review cases",
    hideCases: "Hide cases",
    searchAria: "Search cases for suite",
    searchPlaceholder: "Search by key, title, folder, or tag",
    noMatching: "No matching test cases",
    cancel: "Cancel",
    saving: "Saving…",
    save: "Save suite",
    create: "Create suite",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
  },
  ru: {
    defaultName: "Смоук релиза",
    defaultDescription: "Критические проверки для текущей сборки",
    error: "TMS API не принял сьют. Проверьте выбранные кейсы и повторите попытку.",
    configureTitle: "Настроить тест-сьют",
    createTitle: "Создать тест-сьют",
    subtitle: "Сохраните набор кейсов, чтобы быстро запускать его снова.",
    name: "Название сьюта",
    description: "Описание",
    mode: "Как собирать кейсы",
    staticMode: "Выбрать точные кейсы",
    staticModeHint: "Список меняется только вручную",
    dynamicMode: "Обновлять по тегам",
    dynamicModeHint: "Подходящие кейсы добавляются сами",
    tags: "Обязательные теги",
    tagsPlaceholder: "smoke, mobile",
    scope: "в наборе",
    dynamicHint: "Обновляется автоматически при изменении подходящих тегов",
    staticHint: "Точный список поддерживается этим сьютом",
    selectVisible: "Выбрать видимые",
    clearVisible: "Снять видимые",
    reviewCases: "Проверить кейсы",
    hideCases: "Скрыть кейсы",
    searchAria: "Найти кейсы для сьюта",
    searchPlaceholder: "Поиск по ключу, названию, папке или тегу",
    noMatching: "Подходящие тест-кейсы не найдены",
    cancel: "Отмена",
    saving: "Сохранение…",
    save: "Сохранить сьют",
    create: "Создать сьют",
    low: "Низкий",
    medium: "Средний",
    high: "Высокий",
    critical: "Критический",
  },
} as const;

export const getSuiteDialogCopy = (locale: TmsLocale) => copies[locale];
