import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    defaultName: "Release smoke",
    defaultDescription: "Critical checks for the current build",
    error: "The suite was not accepted by the TMS API. Review the selected cases and try again.",
    configureTitle: "Configure test suite",
    createTitle: "Create test suite",
    subtitle: "Define a reusable scope now; every run can still adjust its final case selection.",
    name: "Suite name",
    description: "Description",
    mode: "Selection mode",
    staticMode: "Static case selection",
    dynamicMode: "Dynamic by tags",
    tags: "Required tags",
    tagsPlaceholder: "smoke, mobile",
    scope: "in scope",
    dynamicHint: "Updates automatically when matching tags change",
    staticHint: "Exact list maintained by this suite",
    selectVisible: "Select visible",
    clearVisible: "Clear visible",
    searchAria: "Search cases for suite",
    searchPlaceholder: "Search by key, title, folder, or tag",
    noMatching: "No matching test cases",
    cancel: "Cancel",
    saving: "Saving…",
    save: "Save suite",
    create: "Create suite",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
  },
  ru: {
    defaultName: "Смоук релиза",
    defaultDescription: "Критические проверки для текущей сборки",
    error: "TMS API не принял сьют. Проверьте выбранные кейсы и повторите попытку.",
    configureTitle: "Настроить тест-сьют",
    createTitle: "Создать тест-сьют",
    subtitle: "Определите переиспользуемый набор; перед каждым раном итоговый выбор кейсов можно изменить.",
    name: "Название сьюта",
    description: "Описание",
    mode: "Режим выбора",
    staticMode: "Статический набор кейсов",
    dynamicMode: "Динамически по тегам",
    tags: "Обязательные теги",
    tagsPlaceholder: "smoke, mobile",
    scope: "в наборе",
    dynamicHint: "Обновляется автоматически при изменении подходящих тегов",
    staticHint: "Точный список поддерживается этим сьютом",
    selectVisible: "Выбрать видимые",
    clearVisible: "Снять видимые",
    searchAria: "Найти кейсы для сьюта",
    searchPlaceholder: "Поиск по ключу, названию, папке или тегу",
    noMatching: "Подходящие тест-кейсы не найдены",
    cancel: "Отмена",
    saving: "Сохранение…",
    save: "Сохранить сьют",
    create: "Создать сьют",
    low: "Низкий",
    medium: "Средний",
    high: "Высокий",
    critical: "Критический",
  },
} as const;

export const getSuiteDialogCopy = (locale: TmsLocale) => copies[locale];
