import { bullets, note, paragraph, section, steps, table, warning, type DocArticle } from "../../../model/article";
export const troubleshootingArticle: DocArticle = {
  id: "integration-troubleshooting", title: "Integration logs and errors", group: "integrations", description: "Check the full chain: event, delivery, external record, incoming update, and result confirmation.",
  keywords: ["error", "not working", "log", "delivery", "401", "403", "webhook", "retry", "uncertain", "retry"],
  related: ["integration-overview", "link-defect", "retest"],
  sections: [
    section("first", "Start with the log", steps(
      ["Open the relevant connection", "Check the current project, service, and saved enabled state."],
      ["Open Log and links", "Click Refresh. Find the event by time, direction, type, and destination record."],
      ["Compare the outcome", "Check delivery state and the external record. A successful webhook response alone does not prove that the expected run was created or status changed."])),
    section("statuses", "What states mean", table(["State", "What to do"],
      ["Queued / Processing", "Wait for processing and refresh the log."], ["Delivered", "Open the linked record and check its contents."],
      ["Error", "Read the reason, fix access or configuration, then use Retry."],
      ["Needs reconciliation", "Check whether a record was created in the external service; restore its link by ID."],
      ["Skipped by rule", "Check the enabled event, scope, and rule filters."],
      ["Canceled", "Check the connection lifecycle; for example, disconnecting cancels pending events."])),
    section("diagnosis", "Common causes", table(["Symptom", "Check"],
      ["No access / 401 / 403", "Token expiry, owner, scopes, and permissions for the specific resource."],
      ["No new event", "Were changes saved? Is the event enabled? Does it belong to the selected project?"],
      ["No incoming status", "Is the webhook active? Do URL and secret match? Is the relevant status selected as ready for retest?"],
      ["Jira does not change status", "Is the transition available in the workflow and permitted for the token owner?"],
      ["GitHub did not create a run", "Is the PR out of draft? Do event and branch match? Is the suite nonempty? Does the path filter match?"],
      ["Slack did not send a message", "Is the bot in the channel? Is the channel ID correct? Does it have chat:write and read permissions?"],
      ["Confluence did not create a report", "Is the run complete? Is the parent page in the right space? Are publishing permissions available?"])),
    section("recover", "Recover without duplicates", warning("Do not blindly recreate the same record", "If the service response was lost, the operation may already have succeeded. First find the external record by contents and time, then use Restore link → ID → Check and link."),
      paragraph("For Confluence, also check the page contents and version. Restoring a link does not automatically republish. For an already linked report, use the separate **Update report** action when available.")),
    section("handoff", "What to send your administrator", bullets("Falcon project, service, and event time with time zone.", "Defect or run key, delivery direction, and error text.",
      "External record link and expected outcome.", "Reproduction steps. Exclude tokens and webhook secrets from the report."),
      note("YouTrack", "For YouTrack, check its own synchronization status screen, available projects and statuses, and the Webhook Triggers URL, header, and token.")),
  ],
};
