export function hooksCopy(russian: boolean) {
  return russian ? {
    workspaceSettings: "Настройки рабочего пространства",
    integrations: "Интеграции",
    integrationsHint: "Подключайте трекеры, репозитории и сервисы команды. Настройки действуют только в этом рабочем пространстве.",
    groups: { tracker: "Задачи и планирование", delivery: "Код и сборки", communication: "Коммуникация и знания" },
    groupHints: { tracker: "Дефекты и рабочие процессы", delivery: "Репозитории и CI", communication: "Уведомления и документация" },
    statuses: { connected: "Подключён", available: "Доступен", attention: "Требует внимания", checking: "Проверяем", planned: "Скоро" },
    refresh: "Обновить",
    retry: "Повторить",
    back: "Назад к интеграциям",
    loading: "Загрузка настроек YouTrack",
    loadError: "Не удалось получить конфигурацию YouTrack",
    loadErrorHint: "Проверьте доступ к рабочему пространству и повторите запрос.",
    openYouTrack: "Открыть YouTrack",
    checkConnection: "Проверить подключение",
    checking: "Проверяем",
    save: "Сохранить",
    saving: "Сохраняем",
    saved: "Настройки YouTrack сохранены.",
    stale: "Настройки уже изменились в другой сессии. Загружена актуальная версия.",
    saveFailure: "Не удалось сохранить настройки. Проверьте поля и попробуйте снова.",
    connectionSuccess: (count: number) => `Подключение работает. Доступно проектов: ${count}.`,
    connectionFailure: "YouTrack не ответил. Проверьте адрес и токен.",
    connection: "Подключение",
    connectionHint: "Адрес сервера и постоянный токен YouTrack.",
    enabled: "Использовать интеграцию",
    enabledHint: "Falcon будет создавать задачи и синхронизировать их статусы.",
    baseUrl: "Адрес YouTrack",
    apiToken: "Постоянный токен",
    tokenStored: "Токен сохранён — оставьте поле пустым",
    tokenPlaceholder: "Вставьте токен YouTrack",
    tokenHint: "Токен хранится зашифрованным и не возвращается в браузер.",
    showToken: "Показать токен",
    hideToken: "Скрыть токен",
    routing: "Маршрутизация",
    routingHint: "Выберите очередь YouTrack для каждого направления Falcon.",
    falconArea: "Направление",
    youTrackProject: "Проект / очередь",
    projectKey: "Ключ",
    targets: { android: "Android", ios: "iOS", backend: "Backend" },
    projectDiscoveryHint: "Список обновляется при проверке подключения.",
    workflow: "Статусы",
    workflowHint: "Определите, когда задача готова к тестированию и когда работа принята.",
    readyStatuses: "Готово к тестированию",
    acceptedStatus: "Принято",
    acceptedStatusHint: "Этот статус завершает обратную синхронизацию дефекта.",
    syncState: "Синхронизация",
    linked: "Связано задач",
    pending: "Ожидают",
    failed: "Ошибки",
    connectionDetails: "Состояние подключения",
    lastCheck: "Последняя проверка",
    lastSync: "Последняя синхронизация",
    configurationSource: "Источник настроек",
    runtimeSource: "Конфигурация сервера",
    workspaceSource: "Рабочее пространство",
    tenantSource: "Настройки тенанта",
    validation: {
      baseUrl: "Укажите корневой HTTPS-адрес YouTrack без параметров.",
      token: "Для первого подключения или другого адреса нужен постоянный токен от 32 символов.",
      connection: "Сначала проверьте подключение, затем выберите проекты для нового адреса.",
      targets: "Выберите проекты для Android, iOS и Backend.",
      readyStatuses: "Выберите хотя бы один статус готовности.",
    },
  } : {
    workspaceSettings: "Workspace settings",
    integrations: "Integrations",
    integrationsHint: "Connect the trackers, repositories, and team services used by this workspace.",
    groups: { tracker: "Issues and planning", delivery: "Code and builds", communication: "Communication and knowledge" },
    groupHints: { tracker: "Defects and workflows", delivery: "Repositories and CI", communication: "Notifications and documentation" },
    statuses: { connected: "Connected", available: "Available", attention: "Needs attention", checking: "Checking", planned: "Coming soon" },
    refresh: "Refresh",
    retry: "Try again",
    back: "Back to integrations",
    loading: "Loading YouTrack settings",
    loadError: "Could not load the YouTrack configuration",
    loadErrorHint: "Check workspace access and try the request again.",
    openYouTrack: "Open YouTrack",
    checkConnection: "Test connection",
    checking: "Checking",
    save: "Save",
    saving: "Saving",
    saved: "YouTrack settings saved.",
    stale: "These settings changed in another session. The latest version has been loaded.",
    saveFailure: "Could not save the settings. Check the fields and try again.",
    connectionSuccess: (count: number) => `Connection works. ${count} projects available.`,
    connectionFailure: "YouTrack did not respond. Check the address and token.",
    connection: "Connection",
    connectionHint: "Your YouTrack server address and permanent token.",
    enabled: "Use this integration",
    enabledHint: "Falcon will create issues and keep their statuses in sync.",
    baseUrl: "YouTrack address",
    apiToken: "Permanent token",
    tokenStored: "Token saved — leave blank to keep it",
    tokenPlaceholder: "Paste a YouTrack token",
    tokenHint: "The token is encrypted at rest and is never returned to the browser.",
    showToken: "Show token",
    hideToken: "Hide token",
    routing: "Routing",
    routingHint: "Choose the YouTrack project used for each Falcon area.",
    falconArea: "Area",
    youTrackProject: "Project / queue",
    projectKey: "Key",
    targets: { android: "Android", ios: "iOS", backend: "Backend" },
    projectDiscoveryHint: "The list refreshes when you test the connection.",
    workflow: "Statuses",
    workflowHint: "Define when an issue is ready for testing and when the work is accepted.",
    readyStatuses: "Ready for testing",
    acceptedStatus: "Accepted",
    acceptedStatusHint: "This status completes reverse defect synchronization.",
    syncState: "Synchronization",
    linked: "Linked issues",
    pending: "Pending",
    failed: "Errors",
    connectionDetails: "Connection status",
    lastCheck: "Last checked",
    lastSync: "Last synchronized",
    configurationSource: "Settings source",
    runtimeSource: "Server configuration",
    workspaceSource: "Workspace",
    tenantSource: "Tenant defaults",
    validation: {
      baseUrl: "Enter a root HTTPS YouTrack address without parameters.",
      token: "A permanent token of at least 32 characters is required for a first connection or a different address.",
      connection: "Test the connection first, then choose projects for the new address.",
      targets: "Choose projects for Android, iOS, and Backend.",
      readyStatuses: "Choose at least one ready status.",
    },
  };
}

export type HooksCopy = ReturnType<typeof hooksCopy>;
