import { dashboardCustomizationSections } from "../dashboard/customization";
import { dashboardWalkthrough } from "../walkthroughs/start/context";
import { bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";

export const dashboardArticle: DocArticle = {
  id: "dashboard", title: "Dashboard setup and monitoring", group: "start",
  description: "Build a shared project dashboard from 29 widgets, set your personal context, and open the work behind each metric.",
  keywords: ["dashboard", "dashboard", "metrics", "coverage", "pass rate", "chart", "blocked", "widgets", "customization", "pencil", "drag and drop", "add widget", "remove widget", "width", "save", "cancel", "sections", "freshness", "product", "product group", "regression"],
  related: ["execute-run", "retest", "workspace"],
  sections: [
    section("sections", "Four sections and a combined view",
      paragraph("Widgets belong to four sections. Select a section above the board or **All sections** to see the entire saved collection. The combined view shows those same widgets; it does not need a separate layout."),
      table(["Section", "What to look for"],
        ["Work now", "The work queue, fixes awaiting verification, and seven freshness indicators."],
        ["Runs and risks", "Run trends and results, success rates, and component risks."],
        ["Defects", "Current statuses, tracker links, and new defects during the selected period."],
        ["Test repository", "Case composition, types and tags, new cases, and run coverage."]),
      note("The catalog contains 29 widgets", "Seven indicators of current work are grouped in Test freshness. The separate Awaiting verification card provides quick access to fixes.")),
    ...dashboardCustomizationSections,
    section("walkthrough", "Walkthrough: from setup to verification", dashboardWalkthrough),
    section("context", "Check the context before reading the numbers",
      steps(
        ["Select a project", "Use the global project selector. The name above the dashboard identifies the project whose layout and data you are viewing."],
        ["Set the current-work selection", "Under **Current work**, choose an environment and build, then click **Apply**. These conditions apply to the work queue, Awaiting verification, and Test freshness."],
        ["Choose a period", "The **7, 30, or 90 days** period sets the window for historical metrics, trends, and coverage. Check each widget's label: historical runs include all environments and builds."]),
      table(["Context", "How to interpret it"],
        ["Current work", "Active runs and unresolved defects in the selected environment and build. The historical period does not limit this selection."],
        ["Current project state", "Total cases, repository composition, and defect statuses cover the entire selected project. The current environment filter does not reduce this repository."],
        ["Changes during the period", "New cases, new defects, starts, and completions fall within the selected time window."],
        ["Components and risks", "The current repository and open project defects are compared with run results for the period."]),
      paragraph("For example, **Awaiting verification** uses the current-work selection, while **Defects: awaiting verification** counts all project defects with that status. Different values on these cards can both be correct.")),
    section("metrics", "Work queue and fixes",
      table(["Widget", "Next action"],
        ["Work queue · Active runs", "Each row shows the run key, abbreviated name, count of tests with final results, and their distribution. Check the environment and build in the project header and current-work filter. Click the row, Continue, or Open with the chevron to enter the run, where the full name is available."],
        ["Work queue · Ready for retest", "Open a fix ready for QA verification."],
        ["Awaiting verification", "Click the number on the blue card to see fixes in the current-work selection."]),
      paragraph("A run's progress bar counts tests with final results: passed, failed, blocked, and skipped. Tests that have not started or are in progress have no final result. A full bar alone therefore does not mean the run succeeded.")),
    section("drill", "From a metric to a record",
      paragraph("In normal view, click a widget's number, row, or segment to open matching records. From the list, open a specific run, test, or defect. In **Customize** mode, first save or cancel your layout changes."),
      bullets("Click a chart series name to show or hide it; available numbers and elements open detailed records.",
        "In Components and risks, open the component metric you need: coverage, results, or defects.",
        "In a detailed list, load more records if they do not all fit on the first page.",
        "Check the last refresh time. If refresh fails, read the message and click **Retry**; the last available snapshot may remain visible.")),
    section("detail-pages", "From a metric to a dedicated page",
      paragraph("Details open in Falcon's work area. You do not need to resize the view; global navigation stays available. Opening a component result metric adds a **Tests** tab whose count refers to individual tests, not runs. **Dashboard** above the heading returns to the board and original widget. The browser's **Back** button also works."),
      table(["Page", "How to use it"],
        ["Defects", "Read the title, component, status, and priority in one row. Click the title or the arrow on the right to open the defect. The soft Ready for retest badge identifies a fix awaiting another test."],
        ["Test freshness", "Switch between Not started, In progress, New revisions, No build, and Blocked. Tests are grouped by run: the chevron collapses a group, Open run opens the full run, and a case row opens that specific test."],
        ["Products and tests", "Refine the selection in **Test case fields**, then choose Test cases, Completed runs, or Defects. History includes completed and aborted runs within the selected period that contain matching tests. On the cases tab, select the rows you need and click **Create run**. The standard creation form opens with your selection; nothing starts without confirmation."]),
      bullets("Search, filters, and sorting apply to loaded records. If another page is available, click Show more. The list reports how many rows are displayed; an unknown total is not shown as zero.",
        "The address preserves the original metric, product group, product, regression setting, tab, and period or environment/build context. Reloading restores that context. Older links with a text component filter still work. Search text and selected cases are not included in the link.",
        "Progress in a group heading refers to the entire run when its data is available. The count beside the group name refers to loaded tests in the current selection. These numbers may differ.",
        "An empty selection shows a simple message without a Retry button. Network errors are shown separately; retrying the next page preserves rows already loaded.")),
    section("product-filters", "Product group, product, and regression",
      paragraph("For a single project's details, **Test case fields** offers searchable **Product group** and **Product** values. Choosing another group clears the selected product. A product belongs to its group; values migrated from the old field may remain ungrouped."),
      bullets("For **Regression**, choose **Yes**, **No**, or **All**. No specifically selects tests without the regression flag; All removes the restriction.",
        "**Reset** clears this panel's restrictions. When an older link is opened, its condition appears as **Saved product filter**.",
        "Case classification uses current case revisions. Tests, runs, and related defects use the tested case's snapshot. Renaming a catalog value does not rewrite labels in historical snapshots."),
      note("Case fields and defect details", "The product filter in analytics finds defects through linked tests. It does not replace the separate component field in the defect editor.")),
    section("interpretation", "Success and coverage answer different questions",
      table(["Metric", "Meaning"],
        ["Successful run rate", "Successful runs as a share of runs completed during the period. For example, 5 successful runs out of 6 completed runs is 83.3%. The unit is an entire run."],
        ["Case pass rate", "The share of passed tests within runs. A run with many cases affects this metric differently from a short run."],
        ["Run coverage", "The share of the current repository included in runs started during the period. A case may be included in a run without having a result yet."]),
      note("A completed run may contain failures", "Consider success, coverage, failed areas, and open defects together. Full coverage confirms that cases were included in runs; use results to determine whether they passed.")),
    section("freshness", "Test freshness: two pages",
      paragraph("One widget contains seven indicators for the current context. Switch pages using the arrows at the bottom corners of the card; when focus is inside it, the keyboard arrows, Home, and End also work. Pages change only when you choose to switch them."),
      table(["Page", "Indicators and actions"],
        ["1 of 2", "Not started: begin testing; In progress: continue work; New revisions: compare the case with the run snapshot; No build: identify the version under test."],
        ["2 of 2", "Active runs: open ongoing work; Blocked: find the reason testing stopped; Open defects: review unresolved problems."]),
      paragraph("Clicking a row opens records for that specific indicator using the current filters. The footer shows **1 of 2** or **2 of 2**. Do not add these values together: runs, tests, and defects use different counting units, and some tests belong to multiple groups."),
      note("A new revision does not change the run snapshot", "Updating a case does not rewrite a test already created in a run. Open the record and compare revisions before deciding whether a new run is needed."),
      note("Zero and missing data are different", "Zero means there are no matching records. A dash means the value is unavailable. An empty current queue can coexist with nonempty history. If the result is unexpected, check the project, filters, and refresh status.")),
  ],
};
