import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    error: "The integration case was not saved. Check the system names and API response.",
    title: "Create integration test",
    subtitle: "Capture the systems, contract, happy path, and failure handling in one executable case.",
    source: "Source system",
    sourcePlaceholder: "Web client",
    target: "Target system",
    targetPlaceholder: "Account API",
    name: "Test name",
    namePlaceholder: "Ride request is synchronized to operations",
    contract: "Contract",
    eventStream: "Event stream",
    deepLink: "Deep link",
    databaseSync: "Database sync",
    endpoint: "Endpoint / topic",
    purpose: "Purpose and risk",
    purposePlaceholder: "What must stay consistent across both systems?",
    generated: "Four executable steps are generated",
    generatedHint: "Valid payload, delivery, target state, and controlled failure handling.",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create integration test",
  },
  ru: {
    error: "Не удалось сохранить интеграционный кейс. Проверьте названия систем и ответ API.",
    title: "Создать интеграционный тест",
    subtitle: "Зафиксируйте системы, контракт, успешный сценарий и обработку ошибок в одном исполняемом кейсе.",
    source: "Исходная система",
    sourcePlaceholder: "Веб-клиент",
    target: "Целевая система",
    targetPlaceholder: "API аккаунтов",
    name: "Название теста",
    namePlaceholder: "Запрос поездки синхронизируется с операционной системой",
    contract: "Контракт",
    eventStream: "Поток событий",
    deepLink: "Диплинк",
    databaseSync: "Синхронизация БД",
    endpoint: "Эндпоинт / топик",
    purpose: "Цель и риск",
    purposePlaceholder: "Что должно оставаться согласованным между системами?",
    generated: "Будут созданы четыре исполняемых шага",
    generatedHint: "Валидный payload, доставка, состояние цели и контролируемая обработка ошибки.",
    cancel: "Отмена",
    creating: "Создание…",
    create: "Создать интеграционный тест",
  },
} as const;

export const getIntegrationDialogCopy = (locale: TmsLocale) => copies[locale];
