import { bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";

export const companyAccessArticles: DocArticle[] = [
  { id: "company-access", adminOnly: true, title: "Sign-in and personal profile", group: "start",
    description: "Your first company sign-in, password, two-step verification, photo, and session management.",
    keywords: ["username", "password", "sign in", "avatar", "photo", "profile", "MFA", "recover access"],
    related: ["company-administration", "permissions", "quick-start"], sections: [
      section("visual-access", "Find your account settings", table(["Task", "Where to go"],
        ["Open your personal profile", "In TMS, select your name or avatar at the bottom of the sidebar. In the admin panel, select your account name and choose My profile."],
        ["Update personal details", "Use the profile's name, phone, and photo controls. Your login and email are shown separately from editable fields; see Name and photo below."],
        ["Change your password or end a session", "Open Change password or the Devices and sessions list in your profile. The instructions below explain second-factor confirmation and which sessions end."],
        ["Change language, theme, or sign out", "Use the account menu in the admin panel, or Settings in TMS. Opening your profile does not end your session."])),
      section("address", "Your company's address", paragraph("Ask your administrator for your **Falcon address**, **username**, and **temporary password**. Open the company address directly or click Sign in to company on the landing page. Enter the supplied address or the company's short name. Falcon does not offer public registration."),
        note("Company accounts are separate", "Using the same email in two companies does not merge the accounts. Use the address, username, and password for the company you want to work in.")),
      section("first-login", "Sign in for the first time", steps(
        ["Enter your credentials", "On your company's sign-in page, enter your username or email and temporary password. If they are not accepted, check the company address and contact your administrator."],
        ["Set your own password", "After your first sign-in, Falcon asks you to replace the temporary password. Work sections remain unavailable until you do. Use at least 12 characters and a password different from your username or email."],
        ["Set up a second factor", "The primary administrator and company administrators add Falcon to an authenticator app using the QR code, then enter a one-time code. Store the displayed recovery codes separately from your password."],
        ["Open a project", "After signing in, select an available project. You can sign in to the company and manage employees even if no projects have been created yet."])),
      section("profile", "Name and photo", steps(
        ["Open your profile", "Click your photo and name at the bottom of the main sidebar. In the collapsed sidebar, the circular avatar also opens your profile. The profile opens inside TMS with the main sidebar; you do not need to visit the admin panel. Use Back to return to the previous screen."],
        ["Change your name", "Enter your display name and, optionally, a phone number in international format. Click Save. Changing your name does not change your username."],
        ["Add a photo", "Click Add photo or Change photo. Choose a JPEG, PNG, or static WebP. Falcon resizes large photos before upload; you do not need to compress the file to 1 MB manually. Source images up to 25 MB are supported. Falcon prepares a square avatar; use the separate button beside the photo to remove it."])),
      section("password", "Password and devices", paragraph("In your profile, click **Change password** to open a separate screen inside Falcon. Enter your current password, new password, and confirmation. **Back to profile** returns to your personal details and devices. If a second factor is enabled, enter an unused authenticator code or recovery code. Changing the password refreshes your current session and ends all others."),
        paragraph("In Devices and sessions, you can end an individual session. Ending the current session requires signing in again. Do not share passwords or one-time codes in comments, test cases, or screenshots.")),
      section("recovery", "If you cannot sign in", table(["Situation", "What to do"],
        ["Temporary password expired or lost", "Ask your administrator to issue a new temporary password."],
        ["No access to your authenticator app", "Use an unused recovery code. If none remain, contact your administrator."],
        ["Account blocked or access revoked", "Use the contact information on your company's sign-in page."],
        ["Need to change your email", "Contact your administrator. Self-service email changes and email-based recovery are not yet available."]),
        paragraph("The Falcon owner can help a primary administrator who has lost access. In Sandbox, open the company and choose **Issue temporary password** under **Primary administrator**. If confirmation is required, enter **your current Sandbox password** and your own authenticator code, not the employee's password. A used code is not accepted; wait for the next one. After confirmation, the new password appears automatically and can be copied separately from the username. The administrator's previous sessions end. Resetting the second factor is a separate option, when one was configured.")),
    ] },
  { id: "company-administration", title: "Company employees and access", group: "reference",
    description: "Add employees, assign roles, recover or revoke access, and preserve testing history.",
    keywords: ["employee", "user", "admin panel", "member", "role", "limit", "block", "temporary password"],
    related: ["company-access", "permissions", "workspace"], sections: [
      section("visual-members", "Find company administration tasks", table(["Task", "Where to go"],
        ["Find an employee", "Open Admin panel → Employees and search by name or email. Rows show the employee's name, email, role, and account state; open a row to inspect the details."],
        ["Add or update an employee", "Use Add employee for a new account, or open an existing employee's side panel. Security and photo controls have their own sections. Follow the creation and access instructions below."],
        ["Review the primary administrator", "Open their employee record. The primary administrator's role and login cannot be changed there; use the ownership transfer process below when handing over the company."],
        ["Check your company address", "Open Company in the admin panel. It shows the Falcon address, access support contact, and company registration details. Use that company's address when sharing sign-in instructions."])),
      section("open", "Open company administration", paragraph("In TMS, click **Admin panel** near the bottom of the main sidebar, above your profile photo. This button is available only to company administrators. The primary administrator receives a dedicated company address. Open **/admin/** at that address or use **Admin panel**. Only your company's employees and administrative data are available here.")),
      section("create", "Add an employee", steps(
        ["Enter the details", "Open Employees → Add employee. In the side panel, enter a name, work email, and role. Click Create. You can add a phone number and photo in the employee's profile. If you reach the employee limit, Falcon explains why creation is unavailable."],
        ["Share sign-in details", "After creation, Falcon shows the temporary password once. Save the company address, username, and password and give them directly to the employee. A repeat request does not reveal the previously issued password."],
        ["Add a photo", "Open the new employee's profile and upload a photo. The employee can also change it in their own profile."])),
      section("roles", "Choose a role", table(["Role", "Purpose"],
        ["Administrator", "Admin panel, employee management, and hook configuration; a second factor is required."],
        ["QA manager", "Organize testing and configure hooks. No access to the admin panel."],
        ["Tester", "Prepare and execute tests. No access to the admin panel or hook configuration."],
        ["Reporter", "Work with defect reports within the assigned permissions."],
        ["Viewer", "View available material without changing data. No access to the admin panel or hook configuration."]),
        note("Primary administrator", "The company must retain an active primary administrator. You cannot block, delete, or demote them if that would leave the company without an owner.")),
      section("ownership", "Transfer company ownership", paragraph("The primary administrator opens another active administrator's profile, checks that a second factor is configured, and chooses **Transfer ownership**. Confirm the transfer. If your sign-in is no longer recent, Falcon asks for your password and code again. Repeat the action after verification."),
        paragraph("The recipient becomes the primary administrator, and the previous owner remains an administrator. Both users' sessions end and they must sign in again. The transfer is recorded in the audit log. If the current owner has lost access, contact the Falcon owner.")),
      section("lifecycle", "Change or revoke access", bullets(
        "Open the employee, edit their name, contact details, or role, and save. If there is a version conflict, refresh the profile: another administrator's changes are not silently overwritten.",
        "Block temporarily suspends access. Unblock restores it if there are enough available seats.",
        "Revoke access disables the account in the company. Authorship of test cases, runs, defects, and comments is preserved.",
        "Permission changes, blocking, and revoking access end the employee's active sessions. Hiding a button does not itself grant or revoke permission.",
        "Issue a new temporary password if the employee loses theirs. Resetting the second factor is separate; use it only if the employee has lost both the authenticator and recovery codes.")),
      section("people", "Authors and assignees", paragraph("In projects, portfolios, test cases, runs, and defects, the assignee appears with a name and photo, or initials if no photo is available. When creating a project, portfolio, case, run, or defect, choose an employee in **Assignee**; search works by name and email. In the case editor, you can change the assignee and save a new revision. This does not change the test case author, who is determined by the first revision. The author of a later revision is shown separately. Only active members of your company are available for assignment; disabled employees retain authorship of their work.")),
      section("journal", "Review changes", paragraph("The company audit log shows administrative actions, their time, and who performed them. Passwords, codes, and personal file contents are excluded. Contact the Falcon owner to change the employee limit, enabled features, or domain.")),
    ] },
];
