import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    projectError: "Check the project key and the TMS API response, then try again.",
    environmentError: "The project was created, but its default environment was not. Retry to resume safely.",
    title: "Create project",
    editTitle: "Edit project",
    subtitle: "A project keeps its own repository, suites, environments, runs, and reports.",
    name: "Project name",
    namePlaceholder: "Mobile App",
    key: "Project key",
    keyPlaceholder: "MOBILE",
    environment: "Default environment",
    description: "Description",
    descriptionPlaceholder: "What product or service does this project cover?",
    baseUrl: "Base URL",
    ready: "Ready to test immediately",
    readyHint: "An empty repository and your configured environment are created together.",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create project",
    save: "Save changes",
  },
  ru: {
    projectError: "Проверьте ключ проекта и ответ TMS API, затем повторите попытку.",
    environmentError: "Проект создан, но окружение по умолчанию — нет. Повторите, чтобы безопасно продолжить.",
    title: "Создать проект",
    editTitle: "Изменить проект",
    subtitle: "У каждого проекта свой репозиторий, сьюты, окружения, раны и отчёты.",
    name: "Название проекта",
    namePlaceholder: "Мобильное приложение",
    key: "Ключ проекта",
    keyPlaceholder: "MOBILE",
    environment: "Окружение по умолчанию",
    description: "Описание",
    descriptionPlaceholder: "Какой продукт или сервис покрывает этот проект?",
    baseUrl: "Базовый URL",
    ready: "Можно тестировать сразу",
    readyHint: "Пустой репозиторий и настроенное окружение создаются вместе.",
    cancel: "Отмена",
    creating: "Создание…",
    create: "Создать проект",
    save: "Сохранить изменения",
  },
} as const;

export const getProjectDialogCopy = (locale: TmsLocale) => copies[locale];
