export const enDashboardWorkbenchMessages = {
  "dashboardWorkbench.context": "Current work",
  "dashboardWorkbench.contextHint": "Environment and build filter the current metrics, work queues and freshness checks.",
  "dashboardWorkbench.environment": "Environment",
  "dashboardWorkbench.allEnvironments": "All environments",
  "dashboardWorkbench.selectedEnvironment": "Selected environment",
  "dashboardWorkbench.build": "Build",
  "dashboardWorkbench.allBuilds": "All builds",
  "dashboardWorkbench.apply": "Apply",
  "dashboardWorkbench.reset": "Reset",
  "dashboardWorkbench.exactBuild": "Exact build reference",
  "dashboardWorkbench.choicesLimited": "Showing the first available contexts. Choose a project to narrow the list; you can enter an exact build.",
  "dashboardWorkbench.title": "Workbench",
  "dashboardWorkbench.activeRuns": "Active runs",
  "dashboardWorkbench.readyForRetest": "Ready for retest",
  "dashboardWorkbench.blockedItems": "Blocked in active runs",
  "dashboardWorkbench.openDefects": "Open defects",
  "dashboardWorkbench.notRunItems": "Not started",
  "dashboardWorkbench.inProgressItems": "In progress",
  "dashboardWorkbench.outdatedItems": "Newer case revision",
  "dashboardWorkbench.runsWithoutBuild": "Runs without a build",
  "dashboardWorkbench.freshness": "Freshness checks",
  "dashboardWorkbench.freshnessHint": "Current active runs in this context.",
  "dashboardWorkbench.notRunHint": "Cases waiting to be started",
  "dashboardWorkbench.inProgressHint": "Cases being executed",
  "dashboardWorkbench.outdatedHint": "A newer case revision exists. The run keeps its original snapshot.",
  "dashboardWorkbench.noBuildHint": "Active runs with no build reference",
  "dashboardWorkbench.viewAll": "View records",
  "dashboardWorkbench.open": "Open {key}",
  "dashboardWorkbench.totalRows": "{shown} of {total}",
  "dashboardWorkbench.loadedRows": "Loaded: {shown} · matching now: {total}",
  "dashboardWorkbench.loadMore": "Load more",
  "dashboardWorkbench.refreshList": "Refresh list",
  "dashboardWorkbench.livePages": "Records can change while you browse. Refresh the list to start with the latest state.",
  "dashboardWorkbench.empty": "No records match this context.",
  "dashboardWorkbench.loading": "Loading current work…",
  "dashboardWorkbench.refreshing": "Updating…",
  "dashboardWorkbench.updated": "Updated {date}",
  "dashboardWorkbench.retry": "Retry",
  "dashboardWorkbench.stale": "Refresh failed. Showing the latest available snapshot.",
  "dashboardWorkbench.disabled": "Connect to Falcon to load current work.",
  "dashboardWorkbench.error.authentication": "Sign in again to load current work.",
  "dashboardWorkbench.error.permission": "You do not have access to these reports.",
  "dashboardWorkbench.error.scope": "This project or environment is unavailable. Choose another context.",
  "dashboardWorkbench.error.scopeTooLarge": "This selection is too large. Choose a project or narrower context.",
  "dashboardWorkbench.error.unavailable": "Current work is temporarily unavailable.",
  "dashboardWorkbench.error.error": "Could not load current work.",
  "dashboardWorkbench.requestId": "Request: {id}",
  "dashboardWorkbench.noEnvironment": "No environment context",
  "dashboardWorkbench.noBuild": "No build",
  "dashboardWorkbench.passedCount": "{count} passed",
  "dashboardWorkbench.failedCount": "{count} failed",
  "dashboardWorkbench.blockedCount": "{count} blocked",
  "dashboardWorkbench.itemCount": "{count} cases",
  "dashboardWorkbench.attempt": "Attempt {count}",
  "dashboardWorkbench.revision": "Snapshot r{snapshot} · current r{current}",
  "dashboardWorkbench.currentSnapshot": "Current state · environment and build filters applied",
} as const;
