export const ruDashboardWorkbenchMessages = {
  "dashboardWorkbench.context": "Текущая работа",
  "dashboardWorkbench.contextHint": "Окружение и сборка фильтруют текущие показатели, рабочие очереди и проверки актуальности.",
  "dashboardWorkbench.environment": "Окружение",
  "dashboardWorkbench.allEnvironments": "Все окружения",
  "dashboardWorkbench.selectedEnvironment": "Выбранное окружение",
  "dashboardWorkbench.build": "Сборка",
  "dashboardWorkbench.allBuilds": "Все сборки",
  "dashboardWorkbench.apply": "Применить",
  "dashboardWorkbench.reset": "Сбросить",
  "dashboardWorkbench.exactBuild": "Точное название сборки",
  "dashboardWorkbench.choicesLimited": "Показаны первые доступные значения. Выберите проект, чтобы сузить список; точное название сборки можно ввести вручную.",
  "dashboardWorkbench.title": "Рабочая очередь",
  "dashboardWorkbench.activeRuns": "Активные прогоны",
  "dashboardWorkbench.readyForRetest": "К ретесту",
  "dashboardWorkbench.blockedItems": "Заблокированы в активных прогонах",
  "dashboardWorkbench.openDefects": "Открытые дефекты",
  "dashboardWorkbench.notRunItems": "Не начаты",
  "dashboardWorkbench.inProgressItems": "Выполняются",
  "dashboardWorkbench.outdatedItems": "Есть новая редакция кейса",
  "dashboardWorkbench.runsWithoutBuild": "Прогоны без сборки",
  "dashboardWorkbench.freshness": "Актуальность проверок",
  "dashboardWorkbench.freshnessHint": "Текущие активные прогоны в выбранном контексте.",
  "dashboardWorkbench.notRunHint": "Кейсы, которые ещё не начали",
  "dashboardWorkbench.inProgressHint": "Кейсы в процессе выполнения",
  "dashboardWorkbench.outdatedHint": "У кейса появилась новая редакция. Прогон сохраняет исходный снимок.",
  "dashboardWorkbench.noBuildHint": "Активные прогоны без указанной сборки",
  "dashboardWorkbench.viewAll": "Открыть записи",
  "dashboardWorkbench.open": "Открыть {key}",
  "dashboardWorkbench.totalRows": "{shown} из {total}",
  "dashboardWorkbench.loadedRows": "Загружено: {shown} · сейчас в выборке: {total}",
  "dashboardWorkbench.loadMore": "Загрузить ещё",
  "dashboardWorkbench.refreshList": "Обновить список",
  "dashboardWorkbench.livePages": "Записи могут измениться во время просмотра. Обновите список, чтобы начать с актуального состояния.",
  "dashboardWorkbench.empty": "В этом контексте записей нет.",
  "dashboardWorkbench.loading": "Загружаем текущую работу…",
  "dashboardWorkbench.refreshing": "Обновляем…",
  "dashboardWorkbench.updated": "Обновлено {date}",
  "dashboardWorkbench.retry": "Повторить",
  "dashboardWorkbench.stale": "Не удалось обновить данные. Показан последний доступный снимок.",
  "dashboardWorkbench.disabled": "Подключитесь к Falcon, чтобы загрузить текущую работу.",
  "dashboardWorkbench.error.authentication": "Войдите снова, чтобы загрузить текущую работу.",
  "dashboardWorkbench.error.permission": "У вас нет доступа к этим отчётам.",
  "dashboardWorkbench.error.scope": "Проект или окружение недоступны. Выберите другой контекст.",
  "dashboardWorkbench.error.scopeTooLarge": "Выборка слишком большая. Выберите проект или уточните контекст.",
  "dashboardWorkbench.error.unavailable": "Текущая работа временно недоступна.",
  "dashboardWorkbench.error.error": "Не удалось загрузить текущую работу.",
  "dashboardWorkbench.requestId": "Запрос: {id}",
  "dashboardWorkbench.noEnvironment": "Окружение не определено",
  "dashboardWorkbench.noBuild": "Без сборки",
  "dashboardWorkbench.passedCount": "Пройдено: {count}",
  "dashboardWorkbench.failedCount": "Провалено: {count}",
  "dashboardWorkbench.blockedCount": "Заблокировано: {count}",
  "dashboardWorkbench.itemCount": "Кейсов: {count}",
  "dashboardWorkbench.attempt": "Попытка {count}",
  "dashboardWorkbench.revision": "Снимок r{snapshot} · текущая r{current}",
  "dashboardWorkbench.currentSnapshot": "Текущее состояние · с учётом окружения и сборки",
} as const;
