export const enShellMessages = {
  "language.label": "Language",
  "language.english": "English",
  "language.russian": "Russian",
  "language.switchTo": "Switch language to {language}",
  "common.actions": "Actions",
  "common.active": "Active",
  "common.archived": "Archived",
  "common.assignee": "Assignee",
  "common.back": "Back",
  "common.cancel": "Cancel",
  "common.clear": "Clear",
  "common.close": "Close",
  "common.configure": "Configure",
  "common.create": "Create",
  "common.creating": "Creating…",
  "common.default": "Default",
  "common.edit": "Edit",
  "common.archive": "Archive",
  "common.restore": "Restore",
  "common.loading": "Loading…",
  "common.more": "More",
  "common.open": "Open",
  "common.owner": "Owner",
  "common.remove": "Remove",
  "common.retry": "Retry",
  "common.save": "Save",
  "common.saving": "Saving…",
  "common.search": "Search",
  "common.status": "Status",
  "common.unassigned": "Unassigned",
  "attachments.removeConfirm": "Remove this attachment? The private file will be deleted and only an audit tombstone will remain.",
  "nav.ariaLabel": "TMS sections",
  "nav.dashboard": "Dashboard",
  "nav.cases": "Test cases",
  "nav.integrations": "Integration testing",
  "nav.runs": "Test runs",
  "nav.suites": "Suites",
  "nav.hooks": "Hooks",
  "nav.reports": "Reports",
  "nav.config": "Config",
  "header.openDashboard": "Open dashboard",
  "header.toggleNavigation": "Toggle navigation",
  "header.dashboard": "Dashboard",
  "header.dashboardAria": "TMS dashboard",
  "header.project": "Project",
  "header.currentProject": "Current project",
  "header.createFirstProject": "Create first project",
  "header.createProject": "Create project",
  "header.searchCases": "Search test cases",
  "header.searchPlaceholder": "Search test cases…",
  "header.createProjectToBegin": "Create a project to begin",
  "header.environment": "Environment",
  "header.build": "Build",
  "header.apiConnected": "TMS API connected",
  "header.developmentDemo": "Development demo",
  "header.apiUnavailable": "TMS API unavailable",
  "auth.account": "Account",
  "auth.configurationTitle": "Authentication is not configured",
  "auth.configurationDescription": "The required public Auth0 settings are missing or invalid. Contact the TMS administrator.",
  "auth.loadingTitle": "Verifying your session",
  "auth.loadingDescription": "Securely connecting to the TMS identity provider.",
  "auth.signInTitle": "Sign in to TMS",
  "auth.signInDescription": "Use your authorized organization account to open this workspace.",
  "auth.signIn": "Sign in",
  "auth.errorTitle": "Authentication failed",
  "auth.errorDescription": "Your session could not be verified. No workspace data was loaded.",
  "auth.retry": "Try again",
  "auth.signOut": "Sign out",
  "auth.signedInAs": "Signed in as {name}",
  "auth.logoutError": "Sign out could not be completed. Try again.",
  "workspace.demoNotice": "Development demo · changes stay in this browser",
  "workspace.title": "TMS workspace",
  "workspace.loading": "Loading workspace…",
  "workspace.loadingDescription": "Connecting to the TMS API and loading the latest project state.",
  "workspace.connectionRequired": "Connection required",
  "workspace.unavailable": "Workspace unavailable",
  "workspace.noLocalReplacement": "No workspace data was replaced or saved locally.",
  "workspace.openDemo": "Open development demo",
  "workspace.productionProtected": "Production data remains protected",
  "workspace.editingDisabled": "Editing is disabled until the API connection is restored.",
  "workspace.createFirstProject": "Create your first project",
  "workspace.loadingLatest": "Loading the latest workspace state.",
  "workspace.projectDescription": "Projects keep test cases, environments, suites, runs, and defects isolated. Start with a real project—no sample records will be added.",
  "workspace.buildRepository": "Build the repository",
  "workspace.buildRepositoryDescription": "Create folders, manual cases, and checklists.",
  "workspace.defineCoverage": "Define coverage",
  "workspace.defineCoverageDescription": "Group exact cases into smoke or regression suites.",
  "workspace.runAndReport": "Run and report",
  "workspace.runAndReportDescription": "Execute every step and capture defects with evidence.",
  "status.notRun": "Not run",
  "status.inProgress": "In progress",
  "status.passed": "Passed",
  "status.failed": "Failed",
  "status.blocked": "Blocked",
  "status.skipped": "Skipped",
  "status.completed": "Completed",
  "status.draft": "Draft",
  "status.ready": "Ready",
  "status.deprecated": "Deprecated",
  "status.archived": "Archived",
  "priority.low": "Low",
  "priority.medium": "Medium",
  "priority.high": "High",
  "priority.critical": "Critical",
  "severity.critical": "Critical",
  "severity.major": "Major",
  "severity.minor": "Minor",
  "severity.low": "Low",
  "runType.smoke": "Smoke",
  "runType.regression": "Regression",
  "runType.acceptance": "Acceptance",
  "runType.adHoc": "Ad hoc",
} as const;

export type ShellMessages = typeof enShellMessages;
