import type { ShellMessages } from "./en";

export const ruShellMessages = {
  "language.label": "Язык",
  "language.english": "English",
  "language.russian": "Русский",
  "language.switchTo": "Переключить язык на {language}",
  "common.actions": "Действия",
  "common.active": "Активно",
  "common.archived": "В архиве",
  "common.assignee": "Исполнитель",
  "common.back": "Назад",
  "common.cancel": "Отмена",
  "common.clear": "Очистить",
  "common.close": "Закрыть",
  "common.configure": "Настроить",
  "common.create": "Создать",
  "common.creating": "Создание…",
  "common.default": "По умолчанию",
  "common.edit": "Изменить",
  "common.archive": "Архивировать",
  "common.restore": "Восстановить",
  "common.loading": "Загрузка…",
  "common.more": "Ещё",
  "common.open": "Открыть",
  "common.owner": "Ответственный",
  "common.remove": "Удалить",
  "common.retry": "Повторить",
  "common.save": "Сохранить",
  "common.saving": "Сохранение…",
  "common.search": "Поиск",
  "common.status": "Статус",
  "common.unassigned": "Не назначен",
  "attachments.removeConfirm": "Удалить это вложение? Приватный файл будет удалён, останется только запись для аудита.",
  "nav.ariaLabel": "Разделы TESSIQ",
  "nav.dashboard": "Дашборд",
  "nav.cases": "Тест-кейсы",
  "nav.integrations": "Интеграционное тестирование",
  "nav.apiTesting": "API Testing",
  "nav.runs": "Тест-раны",
  "nav.suites": "Тест-сьюты",
  "nav.hooks": "Хуки",
  "nav.reports": "Отчёты",
  "nav.config": "Настройки",
  "nav.create": "Создать",
  "nav.createCase": "Новый тест-кейс",
  "nav.createCaseHint": "Добавить проверку в текущий проект",
  "nav.createDefect": "Новый баг-репорт",
  "nav.createDefectHint": "Зафиксировать дефект и контекст",
  "nav.help": "Помощь",
  "nav.notifications": "Уведомления",
  "nav.expandSidebar": "Раскрыть навигацию",
  "nav.collapseSidebar": "Свернуть навигацию",
  "nav.expandSidebarShort": "Раскрыть",
  "nav.collapseSidebarShort": "Свернуть",
  "header.openDashboard": "Открыть дашборд",
  "header.toggleNavigation": "Свернуть или раскрыть навигацию",
  "header.dashboard": "Дашборд",
  "header.dashboardAria": "Дашборд TESSIQ",
  "header.project": "Проект",
  "header.currentProject": "Текущий проект",
  "header.createFirstProject": "Создать первый проект",
  "header.createProject": "Создать проект",
  "header.searchCases": "Найти тест-кейсы",
  "header.searchPlaceholder": "Поиск тест-кейсов…",
  "header.createProjectToBegin": "Сначала создайте проект",
  "header.environment": "Окружение",
  "header.build": "Сборка",
  "header.apiConnected": "TMS API подключён",
  "header.developmentDemo": "Демо-режим разработки",
  "header.apiUnavailable": "TMS API недоступен",
  "auth.account": "Аккаунт",
  "auth.configurationTitle": "Авторизация не настроена",
  "auth.configurationDescription": "Обязательные публичные параметры Auth0 отсутствуют или некорректны. Обратитесь к администратору TESSIQ.",
  "auth.loadingTitle": "Проверяем сессию",
  "auth.loadingDescription": "Устанавливаем защищённое соединение с провайдером идентификации TESSIQ.",
  "auth.signInTitle": "Вход в TESSIQ",
  "auth.signInDescription": "Используйте разрешённый аккаунт организации, чтобы открыть рабочее пространство.",
  "auth.signIn": "Войти",
  "auth.errorTitle": "Ошибка авторизации",
  "auth.errorDescription": "Не удалось проверить сессию. Данные рабочего пространства не загружались.",
  "auth.retry": "Повторить",
  "auth.signOut": "Выйти",
  "auth.signedInAs": "Выполнен вход: {name}",
  "auth.logoutError": "Не удалось выйти. Повторите попытку.",
  "workspace.demoNotice": "Демо-режим · изменения сохраняются только в этом браузере",
  "workspace.title": "Рабочее пространство TESSIQ",
  "workspace.loading": "Загрузка рабочего пространства…",
  "workspace.loadingDescription": "Подключаемся к TMS API и загружаем актуальное состояние проекта.",
  "workspace.connectionRequired": "Требуется подключение",
  "workspace.unavailable": "Рабочее пространство недоступно",
  "workspace.noLocalReplacement": "Данные рабочего пространства не были заменены или сохранены локально.",
  "workspace.openDemo": "Открыть демо-режим",
  "workspace.productionProtected": "Продакшен-данные защищены",
  "workspace.editingDisabled": "Редактирование отключено до восстановления подключения к API.",
  "workspace.createFirstProject": "Создайте первый проект",
  "workspace.loadingLatest": "Загружаем актуальное состояние рабочего пространства.",
  "workspace.projectDescription": "Проекты изолируют тест-кейсы, окружения, сьюты, раны и дефекты. Начните с реального проекта — демо-данные не добавляются.",
  "workspace.buildRepository": "Соберите репозиторий",
  "workspace.buildRepositoryDescription": "Создайте папки, ручные тест-кейсы и чек-листы.",
  "workspace.defineCoverage": "Определите покрытие",
  "workspace.defineCoverageDescription": "Объединяйте выбранные кейсы в смоук- и регресс-сьюты.",
  "workspace.runAndReport": "Запускайте и фиксируйте",
  "workspace.runAndReportDescription": "Проходите каждый шаг и создавайте дефекты с доказательствами.",
  "status.notRun": "Не запускался",
  "status.inProgress": "В процессе",
  "status.passed": "Пройден",
  "status.failed": "Провален",
  "status.blocked": "Заблокирован",
  "status.skipped": "Пропущен",
  "status.completed": "Завершён",
  "status.draft": "Черновик",
  "status.ready": "Готов",
  "status.deprecated": "Устарел",
  "status.archived": "В архиве",
  "priority.low": "Низкий",
  "priority.medium": "Средний",
  "priority.high": "Высокий",
  "priority.critical": "Критический",
  "severity.critical": "Критическая",
  "severity.major": "Серьёзная",
  "severity.minor": "Незначительная",
  "severity.low": "Низкая",
  "runType.smoke": "Смоук",
  "runType.regression": "Регресс",
  "runType.acceptance": "Приёмочный",
  "runType.adHoc": "Разовый",
} satisfies Record<keyof ShellMessages, string>;
