import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    failsOn: "fails on",
    testEnvironment: "test environment",
    defaultActual: "Observed result differs from the expected behavior.",
    error: "The bug report was not saved. Check the TMS API and retry.",
    title: "Report a bug",
    subtitle: "Create a defect and add execution context.",
    summary: "Summary",
    component: "Component",
    severity: "Severity",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    reproducibility: "Reproducibility",
    always: "Always",
    sometimes: "Sometimes",
    once: "Once",
    description: "Description",
    expected: "Expected result",
    actual: "Actual result",
    deepLink: "Deep link",
    linkPlaceholder: "app://path or https://…",
    addEvidence: "Add screenshots or screencasts",
    removeFile: "Remove file",
    evidenceFormats: "PNG, JPG, MP4, MOV, logs, PDF",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create bug report",
  },
  ru: {
    failsOn: "не проходит в",
    testEnvironment: "тестовом окружении",
    defaultActual: "Фактический результат отличается от ожидаемого поведения.",
    error: "Не удалось сохранить баг-репорт. Проверьте TMS API и повторите попытку.",
    title: "Сообщить о дефекте",
    subtitle: "Создайте дефект и добавьте контекст выполнения.",
    summary: "Краткое описание",
    component: "Компонент",
    severity: "Серьёзность",
    low: "Низкая",
    medium: "Средняя",
    high: "Высокая",
    critical: "Критическая",
    reproducibility: "Воспроизводимость",
    always: "Всегда",
    sometimes: "Иногда",
    once: "Один раз",
    description: "Описание",
    expected: "Ожидаемый результат",
    actual: "Фактический результат",
    deepLink: "Диплинк",
    linkPlaceholder: "app://path или https://…",
    addEvidence: "Добавить скриншоты или скринкасты",
    removeFile: "Удалить файл",
    evidenceFormats: "PNG, JPG, MP4, MOV, логи, PDF",
    cancel: "Отмена",
    creating: "Создание…",
    create: "Создать баг-репорт",
  },
} as const;

export const getDefectDialogCopy = (locale: TmsLocale) => copies[locale];

const russianComponentLabels: Record<string, string> = {
  About: "О приложении",
  Access: "Доступ",
  Accessibility: "Доступность",
  "Account Settings": "Настройки аккаунта",
  "Active Orders": "Активные заказы",
  Appearance: "Внешний вид",
  Archives: "Архивы",
  "Assignment Preferences": "Настройки назначений",
  Authentication: "Авторизация",
  Automation: "Автоматизация",
  "Automation Payments": "Автоматизация платежей",
  "Cleaning Preferences": "Настройки уборки",
  Contacts: "Контакты",
  "Core product": "Основной продукт",
  "Deep Links": "Диплинки",
  "Help Center": "Центр помощи",
  "Host Calendar": "Календарь хоста",
  "Host Dashboard": "Дашборд хоста",
  "Host Entry": "Вход хоста",
  "Host Menu": "Меню хоста",
  "Host Profile": "Профиль хоста",
  "Host Shell": "Оболочка хоста",
  Instructions: "Инструкции",
  "Laundry Preferences": "Настройки стирки",
  Legal: "Юридическая информация",
  "Local Protection": "Локальная защита",
  Localization: "Локализация",
  Messages: "Сообщения",
  Motion: "Анимации",
  Notifications: "Уведомления",
  "Order History": "История заказов",
  "Payment Methods": "Способы оплаты",
  "Private Media": "Приватные материалы",
  "Process Restoration": "Восстановление процесса",
  Properties: "Объекты",
  "Property Detail": "Карточка объекта",
  "Property Lifecycle": "Жизненный цикл объекта",
  "Property Settings": "Настройки объекта",
  "Property Setup": "Настройка объекта",
  "Service Launch Bridge": "Переход к запуску услуги",
  "Service Onboarding": "Онбординг услуги",
  "Service Preferences": "Настройки услуги",
  Support: "Поддержка",
  Templates: "Шаблоны",
  Translation: "Перевод",
  Units: "Помещения",
};

export const localizedComponentLabel = (locale: TmsLocale, component: string) =>
  locale === "ru" ? russianComponentLabels[component] ?? component : component;
