import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    failsOn: "fails on",
    testEnvironment: "test environment",
    defaultActual: "Observed result differs from the expected behavior.",
    error: "The bug report was not saved. Check the TMS API and retry.",
    title: "New bug report",
    subtitle: "Create a defect and add execution context.",
    summary: "Defect title",
    component: "Component",
    routingLabel: "Delivery",
    youTrackPlaceholder: "Choose a route",
    youTrackLoading: "Loading…",
    youTrackUnavailable: "Could not load delivery options",
    youTrackRequired: "Choose a defect route.",
    projectIntegrations: "Automatic",
    severity: "Severity",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    reproducibility: "Reproducibility",
    always: "Always",
    sometimes: "Sometimes",
    once: "Once",
    description: "Description",
    expected: "Expected result",
    actual: "Actual result",
    deepLink: "Link",
    linkPlaceholder: "app://path or https://…",
    addEvidence: "Add screenshots or screencasts",
    removeFile: "Remove file",
    evidenceFormats: "PNG, JPG, MP4, MOV, logs, PDF",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create bug report",
  },
  ru: {
    failsOn: "не проходит в",
    testEnvironment: "тестовом окружении",
    defaultActual: "Фактический результат отличается от ожидаемого поведения.",
    error: "Не удалось сохранить баг-репорт. Проверьте TMS API и повторите попытку.",
    title: "Новый баг-репорт",
    subtitle: "Создайте дефект и добавьте контекст выполнения.",
    summary: "Название дефекта",
    component: "Компонент",
    routingLabel: "Передача",
    youTrackPlaceholder: "Выбрать маршрут",
    youTrackLoading: "Загрузка…",
    youTrackUnavailable: "Не удалось загрузить варианты",
    youTrackRequired: "Выберите маршрут дефекта.",
    projectIntegrations: "Автоматически",
    severity: "Серьёзность",
    low: "Низкая",
    medium: "Средняя",
    high: "Высокая",
    critical: "Критическая",
    reproducibility: "Воспроизводимость",
    always: "Всегда",
    sometimes: "Иногда",
    once: "Один раз",
    description: "Описание",
    expected: "Ожидаемый результат",
    actual: "Фактический результат",
    deepLink: "Ссылка",
    linkPlaceholder: "app://path или https://…",
    addEvidence: "Добавить скриншоты или скринкасты",
    removeFile: "Удалить файл",
    evidenceFormats: "PNG, JPG, MP4, MOV, логи, PDF",
    cancel: "Отмена",
    creating: "Создание…",
    create: "Создать баг-репорт",
  },
} as const;

export const getDefectDialogCopy = (locale: TmsLocale) => copies[locale];
