import type { TmsLocale } from "../../../localization/model/locale";

const copies = {
  en: {
    failsOn: "fails on",
    testEnvironment: "test environment",
    defaultActual: "Observed result differs from the expected behavior.",
    error: "The bug report was not saved. Check the TMS API and retry.",
    title: "Report a bug",
    subtitle: "Create a defect and add execution context.",
    summary: "Summary",
    component: "Component",
    routingLabel: "Defect routing",
    youTrackPlaceholder: "Choose a route",
    youTrackLoading: "Loading YouTrack routes…",
    youTrackUnavailable: "YouTrack routes are unavailable",
    youTrackRequired: "Choose a defect route.",
    projectIntegrations: "Project integrations",
    routingHint: "Project integrations send the defect to enabled Jira, Trello and Linear connections according to project settings. Automatic YouTrack routing also follows workspace rules when configured. Selecting a specific YouTrack project routes the defect there.",
    severity: "Severity",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    reproducibility: "Reproducibility",
    always: "Always",
    sometimes: "Sometimes",
    once: "Once",
    description: "Description",
    expected: "Expected result",
    actual: "Actual result",
    deepLink: "Deep link",
    linkPlaceholder: "app://path or https://…",
    addEvidence: "Add screenshots or screencasts",
    removeFile: "Remove file",
    evidenceFormats: "PNG, JPG, MP4, MOV, logs, PDF",
    cancel: "Cancel",
    creating: "Creating…",
    create: "Create bug report",
  },
  ru: {
    failsOn: "не проходит в",
    testEnvironment: "тестовом окружении",
    defaultActual: "Фактический результат отличается от ожидаемого поведения.",
    error: "Не удалось сохранить баг-репорт. Проверьте TMS API и повторите попытку.",
    title: "Сообщить о дефекте",
    subtitle: "Создайте дефект и добавьте контекст выполнения.",
    summary: "Краткое описание",
    component: "Компонент",
    routingLabel: "Маршрут дефекта",
    youTrackPlaceholder: "Выбрать маршрут",
    youTrackLoading: "Загружаем маршруты YouTrack…",
    youTrackUnavailable: "Маршруты YouTrack недоступны",
    youTrackRequired: "Выберите маршрут дефекта.",
    projectIntegrations: "Интеграции проекта",
    routingHint: "Интеграции проекта отправляют дефект во включённые Jira, Trello и Linear согласно настройкам проекта. Если настроена автоматическая маршрутизация YouTrack, действуют и её правила. При выборе конкретного проекта YouTrack дефект направляется в него.",
    severity: "Серьёзность",
    low: "Низкая",
    medium: "Средняя",
    high: "Высокая",
    critical: "Критическая",
    reproducibility: "Воспроизводимость",
    always: "Всегда",
    sometimes: "Иногда",
    once: "Один раз",
    description: "Описание",
    expected: "Ожидаемый результат",
    actual: "Фактический результат",
    deepLink: "Диплинк",
    linkPlaceholder: "app://path или https://…",
    addEvidence: "Добавить скриншоты или скринкасты",
    removeFile: "Удалить файл",
    evidenceFormats: "PNG, JPG, MP4, MOV, логи, PDF",
    cancel: "Отмена",
    creating: "Создание…",
    create: "Создать баг-репорт",
  },
} as const;

export const getDefectDialogCopy = (locale: TmsLocale) => copies[locale];
