export const documentationCopy = {
  en: {
    workspace: "Falcon documentation",
    hideTree: "Hide article tree",
    showTree: "Show article tree",
    documentation: "Documentation",
    search: "Search",
    notFound: "Article not found",
    darkTheme: "Switch to dark theme",
    lightTheme: "Switch to light theme",
    guide: "Falcon guide",
    outdatedLink: "This link may be outdated. Select an article in the tree or use search.",
    openGuide: "Open the guide",
    onThisPage: "On this page",
    guideNote: "This is the guide.",
    workspaceNote: "Make changes in the Falcon workspace.",
    userGuide: "User guide",
    searchDocumentation: "Search documentation",
    searchPlaceholder: "Search the guide…",
    clearSearch: "Clear search",
    guideArticles: "Guide articles",
    comingSoon: "Coming soon",
    currentVersion: "Current version",
    previousArticle: "Previous article",
    nextArticle: "Next article",
    minRead: "min read",
    comingToFalcon: "Coming to Falcon",
    articleLink: "Article link",
    articleContents: "Article contents",
    sectionLink: "Link to section",
    officialDocumentation: "Official documentation",
    serviceSetup: "Service setup and current access requirements.",
    relatedArticles: "Related articles",
    adjacentArticles: "Adjacent articles",
    updated: "Updated September 28, 2026",
    searchResults: "Search results",
    searchGuide: "Search the guide",
    articlesFound: "Articles found",
    noMatches: "No matches",
    trySearch: "Try another search",
    searchExamples: "Try “delete case”, “start run”, “Slack”, or “signing secret”.",
    backToArticle: "Back to article",
    copyExample: "Copy example",
    copied: "Copied",
    copyFailed: "Could not copy. Select the text or copy the address from your browser.",
    walkthroughIntro: "A step-by-step example in Falcon. Select a screenshot to explore the interface.",
    enlargeScreenshot: "Enlarge screenshot",
    enlarge: "Enlarge",
    result: "Result.",
    step: "Step",
    of: "of",
    closeScreenshot: "Close screenshot",
    screenshotRegion: "Interface screenshot; scroll to see details",
    panHint: "Pan the image to see details.",
    walkthroughSteps: "Walkthrough steps",
    previousScreenshot: "Previous screenshot",
    nextScreenshot: "Next screenshot",
  },
  ru: {
    workspace: "Документация Falcon",
    hideTree: "Скрыть дерево статей",
    showTree: "Показать дерево статей",
    documentation: "Документация",
    search: "Поиск",
    notFound: "Статья не найдена",
    darkTheme: "Включить тёмную тему",
    lightTheme: "Включить светлую тему",
    guide: "Руководство Falcon",
    outdatedLink: "Возможно, ссылка устарела. Выберите статью в дереве или воспользуйтесь поиском.",
    openGuide: "Открыть руководство",
    onThisPage: "На этой странице",
    guideNote: "Здесь — инструкция.",
    workspaceNote: "Все изменения выполняются в рабочих разделах Falcon.",
    userGuide: "Руководство пользователя",
    searchDocumentation: "Поиск по документации",
    searchPlaceholder: "Найти в руководстве…",
    clearSearch: "Очистить поиск",
    guideArticles: "Статьи руководства",
    comingSoon: "Скоро",
    currentVersion: "Актуальная версия",
    previousArticle: "Предыдущая статья",
    nextArticle: "Следующая статья",
    minRead: "мин чтения",
    comingToFalcon: "Скоро в Falcon",
    articleLink: "Ссылка на статью",
    articleContents: "Содержание статьи",
    sectionLink: "Ссылка на раздел",
    officialDocumentation: "Официальная документация",
    serviceSetup: "Настройка сервиса и актуальные требования к доступу.",
    relatedArticles: "Связанные статьи",
    adjacentArticles: "Соседние статьи",
    updated: "Обновлено 28 сентября 2026",
    searchResults: "Результаты поиска",
    searchGuide: "Поиск по руководству",
    articlesFound: "Найдено статей",
    noMatches: "Ничего не найдено",
    trySearch: "Попробуйте другой запрос",
    searchExamples: "Попробуйте «удалить кейс», «запустить прогон», «Slack» или «signing secret».",
    backToArticle: "Вернуться к статье",
    copyExample: "Скопировать пример",
    copied: "Скопировано",
    copyFailed: "Не удалось скопировать. Выделите текст или скопируйте адрес из браузера.",
    walkthroughIntro: "Пошаговый пример в Falcon. Нажмите на снимок, чтобы рассмотреть интерфейс.",
    enlargeScreenshot: "Увеличить снимок",
    enlarge: "Увеличить",
    result: "Результат.",
    step: "Шаг",
    of: "из",
    closeScreenshot: "Закрыть снимок",
    screenshotRegion: "Снимок интерфейса; прокрутите для просмотра деталей",
    panHint: "Сдвиньте изображение, чтобы рассмотреть детали.",
    walkthroughSteps: "Шаги инструкции",
    previousScreenshot: "Предыдущий снимок",
    nextScreenshot: "Следующий снимок",
  },
};
