import { CheckCircle2, Copy, FlaskConical, Plus, Settings } from "lucide-react";
import type { Environment, Project } from "../../../../core/tms/contracts/legacy-contract";
import { useTmsLocale } from "../../localization/context/useTmsLocale";
import { SectionHeading } from "../common/heading/SectionHeading";
import styles from "../../tms.module.css";
export function ConfigView({ environments, project, onCreate }: { environments: Environment[]; project?: Project; onCreate: () => void }) {
  const { t } = useTmsLocale();
  return <div className={styles.pageScroll}><SectionHeading eyebrow={t("config.eyebrow")} title={t("config.title")} description={t("config.description")} action={<button className={styles.primaryButton} onClick={onCreate} data-testid="new-environment"><Plus size={16} /> {t("config.newEnvironment")}</button>} /><div className={styles.environmentGrid}>{environments.map((environment) => <article className={styles.environmentCard} key={environment.id}><div className={styles.environmentTop}><span><FlaskConical size={19} /></span>{environment.isDefault && <b>{t("common.default")}</b>}<button className={styles.iconButton} title={t("config.copyBaseUrl")} aria-label={`${t("config.copyBaseUrl")}: ${environment.name}`} onClick={() => navigator.clipboard?.writeText(environment.baseUrl)}><Copy size={16} /></button></div><h2>{environment.name}</h2><code>{environment.baseUrl}</code><p>{environment.description}</p><div><small>{project?.key}</small><strong>{environment.key}</strong></div></article>)}</div><section className={`${styles.panel} ${styles.configPanel}`}><div><Settings size={20} /><span><strong>{t("config.executionDefaults")}</strong><small>{t("config.executionDefaultsHint")}</small></span></div><span className={`${styles.statusPill} ${styles.status_passed}`}><CheckCircle2 size={15} /> {t("common.active")}</span></section></div>;
}
