import type { components } from "../../../../core/tms/generated/tms-api";
type Schema = components["schemas"];
export type Provider = Schema["ConnectorProvider"];
export type Connection = Schema["ConnectorConfiguration"];
export type ConnectionInput = Schema["ConnectorConfigurationRequest"];
export type Settings = Schema["ConnectorSettings"];
export type RunRule = Schema["ConnectorRunRule"];
export type Discovery = Schema["ConnectorDiscovery"];
export type Catalog = Schema["ConnectorCatalog"];
export type Delivery = Schema["ConnectorDelivery"];
export type Link = Schema["ConnectorLink"];
export type Webhook = Schema["ConnectorWebhookSetup"];
export type RemoteOption = Schema["ConnectorRemoteOption"];
export type ReportRepublish = Schema["ConfluenceReportRepublishEnvelope"]["data"];
export type Scope = Readonly<{ workspaceId: string; projectId: string }>;
export type Snapshot = Readonly<{ connection: Connection | null; etag: string | null;
  catalog: Catalog; deliveries: readonly Delivery[]; links: readonly Link[]; webhook: Webhook;
  nextCursor: string | null }>;
export const providers: readonly Provider[] = ["jira", "trello", "linear", "github", "slack", "confluence", "swagger"];
export const isProvider = (value: string): value is Provider => providers.includes(value as Provider);
