export const guideChatCopy = {
  en: {
    title: "Falcon AI chat", heading: "How can I help with Falcon?",
    introduction: "Ask about a workflow. I'll explain it and link to the guide.",
    suggestions: ["How do I edit a test run and replace its build?", "How do product groups and custom fields work?", "How do I verify a fix from YouTrack?"],
    placeholder: "Ask Falcon…", question: "Your question about Falcon", send: "Send message", stop: "Stop response",
    newChat: "New chat", conversation: "Conversation with Falcon AI", assistant: "Falcon AI", you: "You", sources: "In the guide",
    preparing: "Checking the Falcon guide…", retry: "Try again", dismiss: "Dismiss error", copy: "Copy answer", copied: "Copied",
    responding: "Falcon AI is responding…", visuals: "Illustrated guide", gallery: "Guide screenshots. Scroll horizontally to see more.", moreSteps: "Show remaining steps", fewerSteps: "Show fewer steps",
    footer: "Answers use the Falcon guide. Check the linked instructions when needed.",
    offline: "Connect to your workspace to ask Falcon AI. You can still read the guide.",
    limit: "Keep your question under 8,000 characters. Your text has been preserved.",
    dictate: "Dictate a question", stopDictation: "Stop dictation", cancelDictation: "Cancel dictation",
    recording: "Connecting microphone…", transcribing: "Transcribing…", review: "Review the text before sending.",
    unavailable: "Falcon AI is unavailable. Your question is saved here. Try again.",
    forbidden: "You no longer have access to this workspace. Your question is saved here.",
    signedOut: "Sign in again to ask Falcon AI. Your question is saved here.",
    limited: "The AI request limit was reached. Try again later. Your question is saved here.",
    invalid: "Could not prepare an answer. Try making your question more specific.",
  },
  ru: {
    title: "Falcon AI чат", heading: "Чем помочь в Falcon?",
    introduction: "Спросите о работе с Falcon. Объясню порядок действий и найду нужную статью.",
    suggestions: ["Как отредактировать прогон и заменить сборку?", "Как работают группы продуктов и кастомные поля?", "Как проверить исправление из YouTrack?"],
    placeholder: "Спросите Falcon…", question: "Ваш вопрос о Falcon", send: "Отправить сообщение", stop: "Остановить ответ",
    newChat: "Новый чат", conversation: "Диалог с Falcon AI", assistant: "Falcon AI", you: "Вы", sources: "В руководстве",
    preparing: "Проверяю руководство Falcon…", retry: "Повторить", dismiss: "Закрыть ошибку", copy: "Скопировать ответ", copied: "Скопировано",
    responding: "Falcon AI отвечает…", visuals: "Иллюстрации из руководства", gallery: "Снимки руководства. Прокрутите по горизонтали, чтобы увидеть остальные.", moreSteps: "Показать остальные шаги", fewerSteps: "Свернуть шаги",
    footer: "Ответы основаны на руководстве Falcon. При необходимости сверяйтесь с указанными статьями.",
    offline: "Подключитесь к рабочему пространству, чтобы спросить Falcon AI. Руководство доступно для чтения.",
    limit: "Сократите вопрос до 8 000 символов. Весь текст сохранён.",
    dictate: "Продиктовать вопрос", stopDictation: "Остановить диктовку", cancelDictation: "Отменить диктовку",
    recording: "Подключаем микрофон…", transcribing: "Распознаём речь…", review: "Проверьте текст перед отправкой.",
    unavailable: "Falcon AI сейчас недоступен. Вопрос сохранён здесь. Попробуйте ещё раз.",
    forbidden: "У вас больше нет доступа к этому пространству. Вопрос сохранён здесь.",
    signedOut: "Войдите в аккаунт ещё раз, чтобы спросить Falcon AI. Вопрос сохранён здесь.",
    limited: "Достигнут лимит запросов к AI. Попробуйте позже. Вопрос сохранён здесь.",
    invalid: "Не удалось подготовить ответ. Попробуйте уточнить вопрос.",
  },
} as const;
export type GuideChatCopy = typeof guideChatCopy["en"] | typeof guideChatCopy["ru"];
