const labels: Record<string, readonly [string, string]> = {
  "company.created": ["Компания создана", "Company created"],
  "company.details_changed": ["Изменены данные компании", "Company details updated"],
  "company.capacity_changed": ["Изменены лимиты и возможности", "Capacity and capabilities updated"],
  "company.owner_changed": ["Передано управление компанией", "Company ownership transferred"],
  "company.owner_access_reset": ["Восстановлен доступ главного администратора", "Primary administrator access reset"],
  "company.status_changed": ["Изменён статус компании", "Company status changed"],
  "company.retry_domain_changed": ["Повторное подключение адреса", "Domain connection retried"],
  "company.domain_activated": ["Адрес компании подключён", "Company domain connected"],
  "company.domain_check_failed": ["Адрес компании требует проверки", "Company domain needs attention"],
  "company.domain_recovered": ["Работа адреса компании восстановлена", "Company domain connection restored"],
  "company.existing_workspace_adopted": ["Компания переведена на собственный вход", "Company moved to Falcon sign-in"],
  "identity.existing_member_adopted": ["Сотруднику подключён вход Falcon", "Falcon sign-in enabled for person"],
  "member.adopted": ["Сотруднику подключён вход Falcon", "Falcon sign-in enabled for person"],
  "member.created": ["Добавлен сотрудник", "Person added"],
  "member.details": ["Изменены данные сотрудника", "Person details updated"],
  "member.role": ["Изменена роль сотрудника", "Person role updated"],
  "member.ownership": ["Передано управление компанией", "Company ownership transferred"],
  "member.status": ["Изменён доступ сотрудника", "Person access updated"],
  "member.reset_password": ["Выдан временный пароль", "Temporary password issued"],
  "member.revoke_sessions": ["Завершены сеансы сотрудника", "Person sessions ended"],
  "profile.details_changed": ["Изменён профиль", "Profile updated"],
  "profile.password_changed": ["Изменён пароль", "Password changed"],
  "profile.avatar_changed": ["Изменена фотография", "Profile photo updated"],
  "profile.avatar_removed": ["Фотография удалена", "Profile photo removed"],
  "profile.session_revoked": ["Завершён сеанс", "Session ended"],
  "access.login": ["Вход в Falcon", "Signed in to Falcon"],
  "access.logout": ["Выход из Falcon", "Signed out of Falcon"],
  "access.password_changed": ["Установлен пароль", "Password set"],
  "access.mfa_enrolled": ["Подключён второй фактор", "Two-step sign-in enabled"],
  "access.mfa_prepared": ["Начата настройка второго фактора", "Two-step sign-in setup started"],
  "identity.session_reauthenticated": ["Повторно подтверждён вход", "Identity confirmed again"],
  "access.mfa_verified": ["Подтверждён второй фактор", "Second factor verified"],
  "platform.operator_create": ["Создан оператор Falcon", "Falcon operator created"],
  "platform.operator_recover": ["Восстановлен доступ оператора", "Operator access recovered"],
};
export function administrationEventLabel(action: string, locale: "ru" | "en"): string {
  return labels[action]?.[locale === "ru" ? 0 : 1] ?? (locale === "ru" ? "Обновление доступа" : "Access updated");
}
