import { articles, bullets, note, paragraph, section, steps, table, warning, type DocArticle } from "../../model/article";
import { customFieldsWalkthrough } from "../walkthroughs/fields/catalog";

export const customFieldsArticle: DocArticle = {
  id: "custom-fields", title: "Custom test case fields", group: "cases",
  description: "Configure project fields: data types, single or multiple values, and required values.",
  keywords: ["custom fields", "custom fields", "catalog", "product group", "product", "regression", "required", "identifier", "String", "Boolean", "Number", "Integer"],
  related: ["custom-field-values", "create-test-case", "edit-test-case", "organize-cases"],
  sections: [
    section("walkthrough", "Field catalog walkthrough", customFieldsWalkthrough),
    section("open", "Open the project's field catalog", paragraph("Select a project and open **Custom fields** in the sidebar. If contextual mode hides it, find it through **All sections**. The catalog belongs to the selected project; fields and values from another project are not included."),
      paragraph("The table shows the name, identifier, type, whether multiple values are allowed, whether the field is required, and when and by whom it was changed. Click a name to open field settings. Search matches names and identifiers; **Show archived** includes archived entries. Use **Show more** if the list continues.")),
    section("builtins", "Three built-in fields", table(["Field", "Usage"],
      ["Product group · product_group", "A single-value string field. For example, Mobile apps."],
      ["Product · product", "A single-value string field linked to a product group. Choose a group before creating a product."],
      ["Regression · regression", "A single-value Boolean field: true or false. If no value is selected, false is used when saving."]),
      paragraph("These fields appear automatically in each project. By default, they do not require manual entry. You cannot change a built-in field's identifier, type, or Single/Multiple mode, or archive it. The **Required** switch is available to users with field configuration permission."),
      note("The former Component field", "Existing values are preserved as products without a group. Falcon does not split the old text into groups and products at slashes or other characters. You can continue selecting these products with no group specified; creating a new product requires a group.")),
    section("create", "Create a field", steps(
      ["Click Create field", "A dedicated settings screen opens. Enter a name your team will understand, such as Platform."],
      ["Set the identifier", "For example, platform. Start with a lowercase Latin letter. After that, use lowercase Latin letters, digits, periods, hyphens, or underscores, up to 64 characters in total. The identifier must be unique within the project, including archived fields."],
      ["Choose the type and number of values", "Choose String, Boolean, Number, or Integer. Single allows one value per case; Multiple allows several values for the same field."],
      ["Make it required if needed", "Enable Required if cases must not be saved without this field. Prepare suitable catalog values before enabling it."],
      ["Save the field", "Click Save. After the first save, Field values becomes available on the same screen."]),
      articles("custom-field-values")),
    section("types", "Choose the right type", table(["Type", "Allowed value", "Example"],
      ["String", "Nonempty text up to 500 characters.", "Android"],
      ["Boolean", "true or false; the add form offers Yes and No.", "true"],
      ["Number", "A number from −10¹⁵ to 10¹⁵, including decimals. Use a period as the decimal separator.", "2.5"],
      ["Integer", "An integer from −10¹⁵ to 10¹⁵.", "3"]),
      paragraph("Every field type is selected from catalog values in the case details. A numeric type does not become a free-entry number input in each case. If you have permission, you can add a new value directly from the dropdown.")),
    section("required", "Required fields", paragraph("The **Required** switch is available in the table and field settings. Required fields have an asterisk in the case editor. The server validates them on save: clearing a required field prevents the case from being saved."),
      paragraph("Making a field required does not populate existing cases or rewrite their earlier revisions. Fill in the new required field the next time you save a case. For a Boolean field, false is a valid value, not a missing answer.")),
    section("edit", "Changes and restrictions", bullets(
      "You can change a regular active field's name and required setting. Previously saved case revisions retain their field names and values.",
      "You can change the identifier and type only before any values have been registered or case revisions reference the field.",
      "A regular field can be expanded from a single value to multiple values. The reverse change is blocked if case revisions already reference it.",
      "If another employee changed the field first, refresh the page and apply your edit to the latest data.")),
    section("archive", "Archive a field", paragraph("For a regular field, open **⋯ → Archive**. Archiving is available only when no case revisions use the field. References from earlier revisions also count: archiving a case does not free its fields."),
      paragraph("To restore a field, enable **Show archived**, open its menu, and choose **Restore**. Archived fields cannot be edited until restored. Built-in fields cannot be archived, and this screen offers no permanent catalog deletion."),
      warning("If an action is rejected", "A message that a field already exists or is in use does not mean data was lost. Check identifier uniqueness and where the field is used. Do not create renamed copies just to bypass the restriction.")),
    section("permissions", "Who can configure fields", table(["Action", "Access"],
      ["View the catalog", "Employees with read access to the project."],
      ["Create or edit field definitions, required settings, and archive state", "Workspace administrators and QA managers with project management permission."],
      ["Add or edit values, including from a case", "Employees with test case management permission; standard roles also include testers."]),
      paragraph("If Create or Save is unavailable, check the selected project, connection, and your permissions. Read access does not grant permission to change the catalog's structure.")),
  ],
};
