import { walkthrough } from "../../../model/visual/walkthrough";
import { screenshotStep as shot } from "../media/screenshot-step";

export const workspaceWalkthrough = walkthrough("Project, environment and run context", [
  shot("workspace-03-project-20260913-en-20260928",
    "Select projects",
    "In the repository, click the project name in the top bar. Under **Projects**, select one or more projects and choose **Apply**. Search narrows the available list.",
    "Payments is selected in this example, with Personal project and Customer Portal also available. Your selection determines the repository view; cases retain their own project keys and folders.",
    "Repository project picker with the existing Payments project selected."),
  shot("workspace-04-portfolio-20260913-en-20260928",
    "Open an entire portfolio's repository",
    "Switch to **Portfolios**, find a name and select the portfolio. Choose **Apply** to view cases from its projects.",
    "Northstar Banking is available but not selected in this screenshot, so Apply is disabled. Select it before applying. A portfolio combines the viewing scope without moving cases between projects.",
    "Portfolios tab showing Northstar Banking unselected, Selected: 0 and a disabled Apply button."),
  shot("workspace-v2-01-settings-20260928-en-20260928",
    "Check the project's environments",
    "In **Settings**, open **Environments**. Verify the project in the top bar. Use an existing environment or select **New environment**.",
    "Payments has a saved Staging environment with key STAGING marked **Default**. The build version under test is specified separately.",
    "Payments environment settings with Staging marked Default and controls to edit it or create a New environment."),
  shot("workspace-v2-02-environment-20260913-en-20260928",
    "Add an environment",
    "In Payments, select **New environment** and enter a name, key and base URL. This example uses **Guide environment**, **GUIDE** and **https://staging.example.com**. Replace these with your own details before choosing **Save**.",
    "This is an unsaved form in Payments; no Guide environment was created for the capture. Saving valid details adds an environment to the selected project's list.",
    "Unsaved Payments environment form with Guide environment, key GUIDE and https://staging.example.com."),
  shot("run-03-target-20260928-en-20260928",
    "Review run parameters",
    "In **New run**, the description and case selection appear immediately. In **Assignment** on the right, set tags, the run owner and release version. Case executors are assigned separately. Android and iOS appear below; Android requires a build file.",
    "The screenshot selects PAY-TC-34, owner Anna Taylor and release 3.0.0-guide, with iOS 3.0.0 (128) and no Android file. The run is not created yet. Check these values before selecting **Create run**.",
    "English guide walkthrough creation form with PAY-TC-34, Anna Taylor as Run owner, and Android and iOS fields."),
]);

export const dashboardWalkthrough = walkthrough("Customize the dashboard and inspect metrics", [
  shot("dashboard-01-empty-20260913-en-20260928",
    "Start with the right project",
    "Open **Dashboard** and check the project in the header. This example uses the existing **Release 2.8** board in **Payments**. Select **Customize**, then **Add widgets** to review its widget library.",
    "The existing Run outcomes widget shows four completed runs: three passed and one failed. Run activity shows nine launches. These widgets already belong to the saved board.",
    "Existing Payments Release 2.8 dashboard with Run outcomes, Run activity and the Customize control."),
  shot("dashboard-02-catalog-20260913-en-20260928",
    "Choose metrics",
    "Use categories or search in the widget library. Select a widget card to open its details and view data from the selected project.",
    "The catalog explains what each widget measures. A zero value means no matching records, not that adding the widget failed.",
    "Falcon widget library with categories, cards and a preview panel."),
  shot("dashboard-03-preview-20260913-en-20260928",
    "Check what the metric means",
    "Select **Run activity** to review its description and Payments preview. The **Added** label means it is already on this board. For a missing widget, use **Add widget**.",
    "The preview shows launches for the selected period, with Launches and Results tabs. Opening a preview does not add a second copy of an existing widget. Save any layout changes back on the dashboard.",
    "Run activity preview for Payments in the widget library, marked Added, with its launches chart."),
  shot("dashboard-04-edit-20260913-en-20260928",
    "Arrange the layout",
    "Select **Done** to return to the dashboard. Adjust titles and drag widgets by their handles if needed. **All sections** shows the entire layout.",
    "Changes remain a draft until you save the dashboard. Removing a widget with its close icon preserves the project's data.",
    "Payments Release 2.8 in customization mode, with existing Run outcomes and Run activity widgets and a Save button."),
  shot("dashboard-05-size-20260913-en-20260928",
    "Choose a width",
    "Open the width menu in the **Run activity** top bar. The screenshot shows **Half width** selected, with **Compact** and **Full width** also available. Choose the layout you need.",
    "Size changes the widget's layout. Its data selection and run results remain unchanged.",
    "Run activity width menu with Half width selected on the Payments dashboard."),
  shot("dashboard-06-overview-20260913-en-20260928",
    "Save the dashboard",
    "Select **Save** and wait for normal viewing mode. **Customize** returns to editing the widget selection and arrangement.",
    "Normal viewing mode shows Customize again. Run outcomes still reports four completed runs and three passes; changing the layout does not change those results.",
    "Payments Release 2.8 dashboard in normal viewing mode with Run outcomes and Run activity."),
  shot("dashboard-07-context-20260913-en-20260928",
    "Check context and time period",
    "Expand **Current work**: environment and build refine the current metrics. The period is set separately and applies to history and run coverage.",
    "Check widget labels before comparing values. The current work selection and history for a period answer different questions.",
    "Expanded Current work section with environment and build selection on the dashboard."),
  shot("dashboard-08-records-20260928-en-20260928",
    "Open the records behind a number",
    "In normal viewing mode, select the **Passed** count. In the details, choose product group, product and regression values as needed. Select a run name or its right arrow to open its checks.",
    "Payments shows three passed runs: English guide walkthrough · 1 and Guide walkthrough · 1 each have one completed check, while Payment regression · rc.2 has twelve. Filters on the left refine this selection.",
    "Payments Passed details showing three runs, with Product group, Product and Regression filters on the left."),
]);
