import { bullets, note, paragraph, section, steps, table } from "../../model/article";

export const dashboardCustomizationSections = [
  section("customization", "Your first dashboard: choose widgets",
    paragraph("Each project has a shared team layout. A new dashboard is empty even if the project already contains cases, runs, and defects. Check the project name in the top bar before configuring it."),
    steps(
      ["Open the library", "On the empty screen, click **Add widgets**. A full-screen library of **29 widgets** opens immediately. You do not need to create or name a dashboard first."],
      ["Review data and contents", "Select a card. Its details show the purpose, section, contents, and a preview using the selected project's data. Labels explain the metric's context and how it overlaps with other widgets."],
      ["Add the widgets you need", "Click **Add widget**. The **Added** indicator and counter reflect your current selection. **Add all** adds only missing widgets."],
      ["Return to customization", "Click **Back to dashboard** or **Done**. Selected widgets appear in their sections. Change the title, order, or width as needed, then click **Save**."]),
    note("Your selection is still a draft", "Returning from the library does not save changes. The team sees the new set after you save it. **Cancel** restores the previous layout, or the empty screen if the dashboard has never been saved.")),
  section("add-widgets", "Add widgets to an existing dashboard",
    steps(
      ["Enter customization mode", "Click the **Customize** pencil in the header, then **Add widgets**. On an empty dashboard, Add widgets opens the library directly."],
      ["Find the metric you need", "Use the library's search and categories. Select a card to inspect its preview, data context, and related widgets. If there are no results, clear the search and choose **All widgets**."],
      ["Compare contents", "Expand **Included in this widget** if available. For example, Test freshness already contains seven current-work indicators, while Defect statuses combines statuses. Separate available counters can provide extra emphasis."],
      ["Add and save", "Click **Add widget**, return **Back to dashboard**, review the layout, and click **Save**. A widget already added is not duplicated."]),
    note("Previews use project data", "Zero means no matching records; a dash means the value is unavailable. The preview helps you evaluate a widget before adding it. Open underlying records from the dashboard after leaving customization mode.")),
  section("editing", "Title, order, and width",
    paragraph("The **Customize** pencil opens the editor. The title becomes a text field, and widgets gain drag handles, removal controls, and available width settings. In normal view, widget contents open records and layout controls are hidden."),
    steps(
      ["Change the title", "Enter a meaningful team title, such as Release quality. You cannot save an empty title."],
      ["Reorder a widget within its section", "Drag the dotted handle in the top strip. Neighboring widgets move aside. Each widget belongs to a fixed section, so dragging changes its order within that section. **All sections** lets you review the entire layout at once."],
      ["Choose a width", "For charts and lists, open the width menu: **Compact**, **Half width**, or **Full width**. Height depends on content; numeric cards have their designated widths."],
      ["Apply or cancel", "Click **Save** to apply the title, widget selection, order, and sizes. **Cancel** restores the entire last saved layout."]),
    bullets("To move a widget with the keyboard, focus its handle, press Space, use the arrow keys, then press Space again. Escape cancels the current move.",
      "On narrow screens, widgets rearrange into fewer columns. Their saved order within each section stays the same.")),
  section("remove-widgets", "Remove and restore a widget",
    steps(
      ["Remove it from the draft", "Enter **Customize** mode and click the cross in the widget's top strip."],
      ["Restore an accidentally removed widget", "Open **Add widgets**, find the card, and add it again. Set its position and width again. To undo all changes at once, click **Cancel**."],
      ["Save the new selection", "Click **Save**. You can remove all widgets: the empty screen will offer **Add widgets**, which opens the library directly."]),
    note("Project records are preserved", "Removing a widget changes only the dashboard. Cases, run results, defects, and history remain in the project. A restored widget shows current data.")),
  section("saving", "Shared layout and personal context",
    table(["What is saved", "Where it applies"],
      ["Title, widget selection, order, and width", "Saved to the project on the server when you click Save. The team sees the shared layout, including when opening the project on another device."],
      ["Section, period, environment, and build", "Saved in this browser for your account and project. Your viewing context is restored when you return."],
      ["Work queue tab and freshness page", "Also saved in this browser. A colleague may have a different tab or page selected."],
      ["Another browser or device", "The saved project layout is available, but personal viewing context does not transfer between devices."],
      ["Browser blocks preference storage", "Your choices work for the current session. You may need to set the context again next time."]),
    paragraph("Changing the section, period, or filters does not require **Save** and does not alter the shared layout. Before switching projects, finish editing by saving or canceling the draft."),
    table(["Situation", "Next action"],
      ["Saving failed because of the network", "Stay in the editor and click Retry. Wait for the result before making more changes."],
      ["A colleague already changed the dashboard", "Falcon reports a conflict and keeps your draft on screen. Note your changes, click Load saved version, and apply them again."],
      ["No Customize button", "Ask your project administrator or QA manager about report management permission."]),
    note("Previously saved dashboards", "The seven former individual current-work cards are automatically combined into Test freshness. Other widgets are preserved, and Awaiting verification remains a separate card. Saving the layout again stores the updated selection in the project.")),
  section("choose-widgets", "Choose an initial set",
    table(["Team task", "Useful widgets"],
      ["Choose the next task", "Work queue, Awaiting verification, Test freshness."],
      ["Review results and risks", "Run trends, Run results, Components and risks, Defect statuses."],
      ["Maintain the test repository", "Total test cases, New test cases, Repository composition, Test case tags, Coverage."]),
    paragraph("Start with metrics your team uses to make decisions. Before reading the numbers, check the project, period, and widget context: current work, history, and the full project repository may use different selections.")),
];
