import { walkthrough } from "../../../model/visual/walkthrough";
import { screenshotStep as shot } from "../media/screenshot-step";
export const sharedStepsWalkthrough = walkthrough("Create a shared procedure and use it in a case", [
  shot("shared-01-library-20260914-en-20260928",
    "Find the procedure in the project",
    "Open **Shared steps** and check the selected project. Search for a procedure by name or select **Shared step** to prepare a new one.",
    "The row shows its revision, step count and usage count. The saved Open the Falcon guide procedure contains one action and has no usages yet.",
    "Payments shared-step library with Open the Falcon guide, revision 1, one step and zero usages."),
  shot("shared-02-editor-assets-20260914-en-20260928",
    "Open the actions and expected results",
    "Select **Open the Falcon guide**. Review the action Open Help from the sidebar and its expected result, The article list and search are visible. **Add step** extends the procedure.",
    "The example contains one step and no attachments. Use Attach file when supporting material is needed. Changes become a saved revision only after you select **Save**.",
    "Open the Falcon guide shared procedure with one action, its expected result and an Attach file control."),
  shot("shared-03-edit-action-20260914-en-20260928",
    "Review and edit the action",
    "Select the action text or its pencil. The field supports formatting, Falcon AI and highlighting. Check the expected result as well.",
    "Save the procedure after reviewing all actions. **Cancel** returns to the library without saving your changes.",
    "Shared procedure with its action and expected result in reading mode and Save and Cancel controls."),
  shot("shared-04-insert-menu-20260914-en-20260928",
    "Choose a shared step in a case",
    "Create a case named **Guide check with reusable steps**. In the **Scenario** section, open **Add step** and choose **Open the Falcon guide** under Shared step. Review the step order before saving.",
    "The shared block is added to the scenario with its actions and materials. You do not need to copy its text manually.",
    "New Guide check with reusable steps form with the Add step menu offering Open the Falcon guide."),
  shot("shared-05-in-case-20260914-en-20260928",
    "Review the inserted block before saving",
    "Expand **Open the Falcon guide** and check the inherited action and expected result. The screenshot still has the initial empty step above the shared block; remove or complete it before selecting **Create**.",
    "The procedure is inserted into an unsaved case draft. Its one action and expected result are visible, with no attachments. The screenshot does not show a created case or an assigned case key.",
    "Unsaved Guide check with reusable steps draft with an empty first step and the expanded Open the Falcon guide block."),
]);
