import { assistantWalkthrough } from "../walkthroughs/writing/tools";
import { paragraph, section, steps, type DocArticle } from "../../model/article";

export const writingAssistantArticle: DocArticle = {
  id: "falcon-ai-writing", title: "Falcon AI: working with text", group: "cases",
  description: "Type or dictate a request, move the window, and review the answer before replacing text.",
  keywords: ["Falcon AI", "dictation", "microphone", "move window", "drag and drop", "hold", "fix errors", "improve text", "Markdown", "selection", "orb", "highlight", "writing", "improve", "H1", "H2", "H3", "headings"],
  related: ["colored-marker", "create-test-case", "edit-test-case", "portfolios"],
  sections: [
    section("guide-chat", "Questions about Falcon", paragraph("For instructions about Falcon itself, open Help → Falcon AI chat. That chat explains procedures from this guide and links to the relevant articles. The editor assistant described below works on the text you select; it does not open the guide chat.")),
    section("walkthrough", "Walkthrough", assistantWalkthrough),
    section("open", "Select text and open Falcon AI", paragraph("Start editing a description, preconditions, action, or expected result. The same tools are available in project and portfolio descriptions and test plans. The blue **Ask Falcon AI** orb is first on the Markdown toolbar, to the left of Undo."),
      paragraph("Select a letter, word, sentence, paragraph, or all text, including lists and special characters. The selection stays highlighted while you type, dictate, or move the window. Without a selection, Falcon AI highlights and processes the entire current field. The window identifies the scope as **Selected text** or **Entire field**. Highlighting disappears when you close the window or apply a response and is not saved in the document.")),
    section("move", "Move the window to see the source text", paragraph("Press and briefly hold the **Ask Falcon AI** heading, then drag the window with your mouse or finger. Release it in a convenient position. The request field and buttons work normally; dragging starts only from the heading."),
      paragraph("You can move the window while typing, dictating, or waiting for a response. Your request, selected text, and response are preserved. It stays in place while the page scrolls; resizing the screen or receiving a response moves it only if it would otherwise leave the visible area. Closing and reopening places it beside the Falcon AI button again."),
      paragraph("With the keyboard, Tab to the window heading and move it with arrow keys. Shift+arrow uses a larger step. Escape closes the window.")),
    section("request", "Describe the change", steps(
      ["Choose an action", "Click **Improve text** or **Fix errors**. Or write your own request: “Format headings and nested lists in Markdown,” “Shorten the description while preserving its conditions,” or “Turn this text into a sequence of actions.”"],
      ["Send the request", "Click the arrow beside the request or press Ctrl+Enter / ⌘Enter. A loading indicator appears while the response is prepared. **Stop** stops waiting."],
      ["Review the suggestion", "The response appears with Markdown formatting. Check its meaning, test conditions, and expected result. **Try another** generates an alternative."])),
    section("dictation", "Dictate a request", paragraph("Click the microphone beside the send arrow and allow microphone access. Wait for **Recording**, which appears after the first microphone data arrives. Speak your request and click **Stop dictation**. Bars beside the counter show incoming audio levels; the timer measures recorded audio to a tenth of a second. After transcription, the text is added to your existing request. Review it, edit if needed, and click the send arrow. Dictation itself does not change the document."),
      paragraph("If the indicator does not react to speech, check your selected microphone and browser permission. If the stream is interrupted, recording is canceled so a partial request is not inserted. Previously typed text is preserved."),
      paragraph("A recording lasts up to five minutes, then stops automatically. Language is detected from speech independently of the interface language and keyboard layout; you do not need to switch either. During transcription, the microphone button cancels waiting. Closing the window, switching workspaces, or leaving the tab turns off the microphone and cancels unfinished dictation. Errors or cancellation do not change the typed request. Dictation is inserted in full. If the request exceeds 16,000 characters, shorten it before sending; text is not truncated automatically. You can type your request if the microphone is unavailable or the dictation limit is reached.")),
    section("replace", "Apply the result", paragraph("Click **Replace selection** or **Replace text**. The suggestion is inserted into the selected field's draft. Closing the window keeps the original text. If you edited the field after sending the request, Falcon asks you to start a new request to preserve your edits."),
      paragraph("Restore text with **Undo**, Ctrl+Z, or ⌘Z. In a scenario field, return to editing first and use the shortcut. Then save the case, project, or portfolio with its normal save control. Scenario text changes inside the selected field; use **Add step** for new standalone steps.")),
    section("headings", "H1, H2, and H3 headings", paragraph("Place the cursor in a paragraph and select **H1**, **H2**, or **H3** on the Markdown toolbar. Clicking the same level again restores normal text. In a scenario, the button changes the current or selected lines. Heading levels have different sizes and remain when the field is reopened."),
      paragraph("Falcon AI uses actual Markdown headings when you ask it to structure text. **Fix errors** preserves existing heading levels.")),
  ],
};
