import { walkthrough } from "../../../model/visual/walkthrough";
import { screenshotStep as shot } from "../media/screenshot-step";

export const portfoliosWalkthrough = walkthrough("From the catalog to the test repository", [
  shot("organization-01-catalog-20260913-en-20260928", "Find a portfolio or project",
    "Open **Portfolios and projects**. The **All** tab shows portfolios and individual projects. Search by name or use **Portfolios** and **Without portfolio** to narrow the catalog.",
    "The example lists Northstar Banking with two projects, plus Payments, Personal project and Customer Portal. Project rows retain their permanent keys; a project can exist without a portfolio.",
    "Portfolio catalog listing Northstar Banking, Payments, Personal project and Customer Portal."),
  shot("organization-05-portfolio-create-20260913-en-20260928", "Preview a new portfolio",
    "Select **New portfolio** and enter a name in the heading. Edit **Description** and choose **Responsible** if needed. The round blue checkmark creates the portfolio; the adjacent cross cancels.",
    "Falcon guide is an unsaved creation preview with New status and no responsible person. This example was canceled, so the following steps use the existing Northstar Banking portfolio.",
    "Unsaved Falcon guide portfolio creation page with New status, Responsible set to Not assigned, and save and cancel controls."),
  shot("organization-02-portfolio-20260913-en-20260928", "Review an existing portfolio",
    "Open **Northstar Banking → Projects**. **Create project** opens a new project page with this portfolio selected; **Add existing project** lets you attach a project without a portfolio.",
    "Northstar Banking already contains Payments and Customer Portal. Select a project name to open its page, or use About portfolio to view the portfolio's own details.",
    "Northstar Banking Projects tab with Payments and Customer Portal, Create project and Add existing project."),
  shot("organization-03-project-dialog-20260913-en-20260928", "Preview the new project page",
    "Select **Create project** and enter **Guide app** with key **GUIDE**. Description and **Testing plan** can be edited in place. Check **Portfolio** and **Responsible** below the plan before creating your own project.",
    "The screenshot is an unsaved project form with Northstar Banking selected and no responsible person. The key becomes permanent after creation. This preview was not created; the remaining steps return to Payments.",
    "Unsaved Guide app creation page with key GUIDE, Northstar Banking selected, and empty description and testing plan fields."),
  shot("organization-04-project-overview-20260913-en-20260928", "Work in the existing project context",
    "Open **Payments → Overview** to read its description, attachments and **Testing plan**. The **Test cases** tab opens the repository and standard case editor within this project.",
    "Payments already has key PAY, the Release 2.8 testing plan, In progress status and Anna Taylor as Responsible. These belong to the existing project, not the unsaved Guide app preview.",
    "Existing Payments overview with its Release 2.8 testing plan, attached files, Northstar Banking portfolio and Anna Taylor."),
  shot("organization-06-markdown-edit-20260913-en-20260928", "Edit a saved project's description",
    "Select the **Description** text or pencil in Payments. Use the Markdown toolbar for headings, highlighting, lists and links. **Save** below this field applies the edit; **Cancel** preserves the saved text.",
    "Only the description editor is open in this screenshot; the testing plan stays in reading mode below it. Opening the editor does not save a change or create another project.",
    "Payments description Markdown editor with Save and Cancel controls above the existing Release 2.8 testing plan."),
  shot("organization-07-workflow-20260913-en-20260928", "Review the project's workflow status",
    "Below the testing plan, open **Status**. Payments is currently **In progress**; the menu also offers **New**, **In review**, **Done** and **On hold**. Choose a status when you intend to update the saved project.",
    "This screenshot shows the status menu only, with In progress still selected. Selecting a different status saves that property separately from discussion text; simply opening the menu changes nothing.",
    "Payments status dropdown showing In progress selected, with New, In review, Done and On hold options above Discussion."),
]);
