export const enCaseMessages = {
  "cases.title": "Cases",
  "cases.new": "New case",
  "cases.create": "Create test case",
  "cases.createFolder": "Create folder",
  "cases.filter": "Filter",
  "cases.filterAria": "Filter test cases",
  "cases.repositoryActions": "Repository actions",
  "cases.resetFilters": "Reset",
  "cases.priority": "Priority",
  "cases.allPriorities": "All priorities",
  "cases.lifecycle": "Lifecycle",
  "cases.allStates": "All states",
  "cases.tagContains": "Tag contains",
  "cases.includeArchived": "Include archived",
  "cases.createProject": "Create project",
  "cases.createProjectHint": "Start a separate QA repository",
  "cases.expandAll": "Expand all folders",
  "cases.expandAllHint": "Show every test case",
  "cases.collapseAll": "Collapse all folders",
  "cases.collapseAllHint": "Show repository structure",
  "cases.searchAria": "Search repository test cases",
  "cases.searchPlaceholder": "Search test cases",
  "cases.nothingFound": "Nothing found",
  "cases.nothingFoundHint": "Try another search or create a case.",
  "cases.expand": "Expand",
  "cases.collapse": "Collapse",
  "cases.addFirst": "Add the first test case",
  "cases.select": "Select a test case",
  "cases.emptyFolder": "This folder is ready. Add the first repeatable verification.",
  "cases.selectHint": "Choose a case from the repository to see its steps and history.",
  "cases.run": "Run case",
  "cases.clone": "Clone",
  "cases.restore": "Restore",
  "cases.archive": "Archive",
  "cases.revision": "Revision {revision}",
  "cases.component": "Component",
  "cases.estimate": "Estimate",
  "cases.type": "Type",
  "cases.preconditions": "Preconditions",
  "cases.testData": "Test data",
  "cases.checklist": "Checklist",
  "cases.testSteps": "Test steps",
  "cases.number": "#",
  "cases.check": "Check",
  "cases.action": "Action",
  "cases.expected": "Expected result",
  "cases.evidenceLinks": "Evidence & links",
  "cases.activity": "Activity",
  "cases.runs": "Runs",
  "cases.files": "Files",
  "cases.latestRuns": "Latest runs",
  "cases.notExecuted": "Not executed yet",
  "cases.revisionHistory": "Revision history",
  "cases.noFiles": "No files attached",
  "cases.noDescription": "No description",
  "cases.noPreconditions": "No preconditions specified.",
  "cases.createInFolder": "Create a test case in {folder}",
  "cases.evidenceAndLinks": "Evidence and links",
  "cases.details": "Details",
  "cases.showDetails": "Show case details",
  "cases.hideDetails": "Hide case details",
  "cases.resizeRepository": "Resize the test case list",
  "caseDialog.editTitle": "Edit test case",
  "caseDialog.createTitle": "Create test case",
  "caseDialog.editSubtitle": "Saving creates a new immutable revision.",
  "caseDialog.createSubtitle": "A guided flow for a repeatable manual verification.",
  "caseDialog.basics": "1. Basics",
  "caseDialog.procedure": "2. Procedure",
  "caseDialog.review": "3. Review",
  "caseDialog.blankManual": "Blank manual",
  "caseDialog.blankManualHint": "Start with one empty step",
  "caseDialog.smokeCheck": "Smoke check",
  "caseDialog.smokeCheckHint": "Critical and ready to run",
  "caseDialog.checklistTemplate": "Checklist",
  "caseDialog.checklistTemplateHint": "Fast repeated verification",
  "caseDialog.title": "Test case title",
  "caseDialog.titlePlaceholder": "User can complete checkout",
  "caseDialog.folder": "Repository folder",
  "caseDialog.description": "Description",
  "caseDialog.descriptionPlaceholder": "What behavior and risk does this test cover?",
  "caseDialog.priority": "Priority",
  "caseDialog.lifecycle": "Lifecycle",
  "caseDialog.owner": "Owner",
  "caseDialog.component": "Component",
  "caseDialog.estimate": "Estimate, minutes",
  "caseDialog.tags": "Tags",
  "caseDialog.tagsPlaceholder": "smoke, regression",
  "caseDialog.preconditions": "Preconditions",
  "caseDialog.preconditionsPlaceholder": "State required before the tester starts",
  "caseDialog.testData": "Test data",
  "caseDialog.testDataPlaceholder": "Accounts, payloads, feature flags, or fixtures",
  "caseDialog.checklistItems": "Checklist items",
  "caseDialog.checklistHint": "Each required item must be confirmed before the case can pass.",
  "caseDialog.addItem": "Add item",
  "caseDialog.itemPlaceholder": "Condition to verify",
  "caseDialog.required": "Required",
  "caseDialog.removeItem": "Remove checklist item",
  "caseDialog.steps": "Execution steps",
  "caseDialog.stepsHint": "Write one action and one observable result per row.",
  "caseDialog.addStep": "Add step",
  "caseDialog.actionPlaceholder": "Tester action",
  "caseDialog.expectedPlaceholder": "Observable expected result",
  "caseDialog.removeStep": "Remove execution step",
  "caseDialog.attachments": "Add screenshots, video, or supporting files",
  "caseDialog.removeAttachment": "Remove attachment",
  "caseDialog.revisionNote": "Revision note",
  "caseDialog.revisionNotePlaceholder": "What changed?",
  "caseDialog.continue": "Continue",
  "caseDialog.saveRevision": "Save revision",
  "suite.title": "Test suites",
  "suite.subtitle": "Reusable release scopes",
  "suite.new": "New suite",
  "suite.searchAria": "Search test suites",
  "suite.searchPlaceholder": "Search suites",
  "suite.notFound": "No suites found",
  "suite.empty": "No suites",
  "suite.emptyHint": "Build a reusable set of test cases.",
  "suite.create": "Create suite",
  "suite.run": "Run suite",
  "suite.staticSelection": "Static selection",
  "suite.key": "Key",
  "suite.testCase": "Test case",
  "suite.priority": "Priority",
  "suite.owner": "Owner",
  "suiteDialog.configureTitle": "Configure test suite",
  "suiteDialog.createTitle": "Create test suite",
  "suiteDialog.subtitle": "Define a reusable scope now; every run can still adjust its final case selection.",
  "suiteDialog.name": "Suite name",
  "suiteDialog.description": "Description",
  "suiteDialog.selectionMode": "Selection mode",
  "suiteDialog.static": "Static case selection",
  "suiteDialog.dynamic": "Dynamic by tags",
  "suiteDialog.requiredTags": "Required tags",
  "suiteDialog.tagsPlaceholder": "smoke, mobile",
  "suiteDialog.scopeCount": "Test cases in scope: {count}",
  "suiteDialog.dynamicHint": "Updates automatically when matching tags change",
  "suiteDialog.staticHint": "Exact list maintained by this suite",
  "suiteDialog.selectVisible": "Select visible",
  "suiteDialog.clearVisible": "Clear visible",
  "suiteDialog.searchAria": "Search cases for suite",
  "suiteDialog.searchPlaceholder": "Search by key, title, folder, or tag",
  "suiteDialog.noMatches": "No matching test cases",
  "suiteDialog.save": "Save suite",
} as const;

export type CaseMessages = typeof enCaseMessages;
