import type { CaseMessages } from "./en";

export const ruCaseMessages = {
  "cases.title": "Тест-кейсы",
  "cases.new": "Новый кейс",
  "cases.create": "Создать тест-кейс",
  "cases.createFolder": "Создать папку",
  "cases.filter": "Фильтр",
  "cases.filterAria": "Фильтр тест-кейсов",
  "cases.repositoryActions": "Действия с репозиторием",
  "cases.resetFilters": "Сбросить",
  "cases.priority": "Приоритет",
  "cases.allPriorities": "Все приоритеты",
  "cases.lifecycle": "Состояние",
  "cases.allStates": "Все состояния",
  "cases.tagContains": "Тег содержит",
  "cases.includeArchived": "Показывать архивные",
  "cases.createProject": "Создать проект",
  "cases.createProjectHint": "Начать отдельный QA-репозиторий",
  "cases.expandAll": "Развернуть все папки",
  "cases.expandAllHint": "Показать каждый тест-кейс",
  "cases.collapseAll": "Свернуть все папки",
  "cases.collapseAllHint": "Показать структуру репозитория",
  "cases.searchAria": "Поиск по репозиторию тест-кейсов",
  "cases.searchPlaceholder": "Поиск тест-кейсов",
  "cases.nothingFound": "Ничего не найдено",
  "cases.nothingFoundHint": "Измените запрос или создайте новый кейс.",
  "cases.expand": "Развернуть",
  "cases.collapse": "Свернуть",
  "cases.addFirst": "Добавить первый тест-кейс",
  "cases.select": "Выберите тест-кейс",
  "cases.emptyFolder": "Папка готова. Добавьте первую повторяемую проверку.",
  "cases.selectHint": "Выберите кейс в репозитории, чтобы увидеть шаги и историю.",
  "cases.run": "Запустить кейс",
  "cases.clone": "Клонировать",
  "cases.restore": "Восстановить",
  "cases.archive": "В архив",
  "cases.revision": "Ревизия {revision}",
  "cases.component": "Компонент",
  "cases.estimate": "Оценка",
  "cases.type": "Тип",
  "cases.preconditions": "Предусловия",
  "cases.testData": "Тестовые данные",
  "cases.checklist": "Чек-лист",
  "cases.testSteps": "Шаги теста",
  "cases.number": "№",
  "cases.check": "Проверка",
  "cases.action": "Действие",
  "cases.expected": "Ожидаемый результат",
  "cases.evidenceLinks": "Материалы и ссылки",
  "cases.activity": "Активность",
  "cases.runs": "Раны",
  "cases.files": "Файлы",
  "cases.latestRuns": "Последние раны",
  "cases.notExecuted": "Ещё не запускался",
  "cases.revisionHistory": "История ревизий",
  "cases.noFiles": "Нет прикреплённых файлов",
  "cases.noDescription": "Описание не указано",
  "cases.noPreconditions": "Предусловия не указаны.",
  "cases.createInFolder": "Создать тест-кейс в папке {folder}",
  "cases.evidenceAndLinks": "Доказательства и ссылки",
  "cases.details": "Сведения",
  "cases.showDetails": "Показать сведения о кейсе",
  "cases.hideDetails": "Скрыть сведения о кейсе",
  "cases.resizeRepository": "Изменить ширину списка тест-кейсов",
  "caseDialog.editTitle": "Изменить тест-кейс",
  "caseDialog.createTitle": "Создать тест-кейс",
  "caseDialog.editSubtitle": "Сохранение создаст новую неизменяемую ревизию.",
  "caseDialog.createSubtitle": "Пошаговое создание повторяемого тест-кейса.",
  "caseDialog.basics": "1. Основное",
  "caseDialog.procedure": "2. Процедура",
  "caseDialog.review": "3. Проверка",
  "caseDialog.blankManual": "Пустой ручной кейс",
  "caseDialog.blankManualHint": "Начать с одного пустого шага",
  "caseDialog.smokeCheck": "Смоук-проверка",
  "caseDialog.smokeCheckHint": "Критический кейс, готовый к запуску",
  "caseDialog.checklistTemplate": "Чек-лист",
  "caseDialog.checklistTemplateHint": "Быстрая повторяемая проверка",
  "caseDialog.title": "Название тест-кейса",
  "caseDialog.titlePlaceholder": "Пользователь может завершить оформление заказа",
  "caseDialog.folder": "Папка репозитория",
  "caseDialog.description": "Описание",
  "caseDialog.descriptionPlaceholder": "Какое поведение и риск покрывает этот тест?",
  "caseDialog.priority": "Приоритет",
  "caseDialog.lifecycle": "Состояние",
  "caseDialog.owner": "Ответственный",
  "caseDialog.component": "Компонент",
  "caseDialog.estimate": "Оценка, минуты",
  "caseDialog.tags": "Теги",
  "caseDialog.tagsPlaceholder": "smoke, regression",
  "caseDialog.preconditions": "Предусловия",
  "caseDialog.preconditionsPlaceholder": "Состояние системы перед началом проверки",
  "caseDialog.testData": "Тестовые данные",
  "caseDialog.testDataPlaceholder": "Аккаунты, payload, feature flags или фикстуры",
  "caseDialog.checklistItems": "Пункты чек-листа",
  "caseDialog.checklistHint": "Для прохождения кейса нужно подтвердить каждый обязательный пункт.",
  "caseDialog.addItem": "Добавить пункт",
  "caseDialog.itemPlaceholder": "Условие для проверки",
  "caseDialog.required": "Обязательный",
  "caseDialog.removeItem": "Удалить пункт чек-листа",
  "caseDialog.steps": "Шаги выполнения",
  "caseDialog.stepsHint": "В каждой строке укажите одно действие и один наблюдаемый результат.",
  "caseDialog.addStep": "Добавить шаг",
  "caseDialog.actionPlaceholder": "Действие тестировщика",
  "caseDialog.expectedPlaceholder": "Наблюдаемый ожидаемый результат",
  "caseDialog.removeStep": "Удалить шаг",
  "caseDialog.attachments": "Добавить скриншоты, видео или другие материалы",
  "caseDialog.removeAttachment": "Удалить вложение",
  "caseDialog.revisionNote": "Комментарий к ревизии",
  "caseDialog.revisionNotePlaceholder": "Что изменилось?",
  "caseDialog.continue": "Продолжить",
  "caseDialog.saveRevision": "Сохранить ревизию",
  "suite.title": "Тест-сьюты",
  "suite.subtitle": "Повторно используемые наборы проверок",
  "suite.new": "Новый сьют",
  "suite.searchAria": "Поиск тест-сьютов",
  "suite.searchPlaceholder": "Поиск сьютов",
  "suite.notFound": "Сьюты не найдены",
  "suite.empty": "Нет тест-сьютов",
  "suite.emptyHint": "Соберите повторно используемый набор тест-кейсов.",
  "suite.create": "Создать сьют",
  "suite.run": "Запустить сьют",
  "suite.staticSelection": "Статический набор",
  "suite.key": "Ключ",
  "suite.testCase": "Тест-кейс",
  "suite.priority": "Приоритет",
  "suite.owner": "Ответственный",
  "suiteDialog.configureTitle": "Настроить тест-сьют",
  "suiteDialog.createTitle": "Создать тест-сьют",
  "suiteDialog.subtitle": "Определите повторно используемый набор; перед запуском состав кейсов всё ещё можно изменить.",
  "suiteDialog.name": "Название сьюта",
  "suiteDialog.description": "Описание",
  "suiteDialog.selectionMode": "Режим выбора",
  "suiteDialog.static": "Статический выбор кейсов",
  "suiteDialog.dynamic": "Динамически по тегам",
  "suiteDialog.requiredTags": "Обязательные теги",
  "suiteDialog.tagsPlaceholder": "smoke, mobile",
  "suiteDialog.scopeCount": "Тест-кейсов в наборе: {count}",
  "suiteDialog.dynamicHint": "Обновляется автоматически при изменении тегов",
  "suiteDialog.staticHint": "Точный список поддерживается внутри сьюта",
  "suiteDialog.selectVisible": "Выбрать видимые",
  "suiteDialog.clearVisible": "Снять выбор с видимых",
  "suiteDialog.searchAria": "Поиск кейсов для сьюта",
  "suiteDialog.searchPlaceholder": "Поиск по ключу, названию, папке или тегу",
  "suiteDialog.noMatches": "Подходящих тест-кейсов нет",
  "suiteDialog.save": "Сохранить сьют",
} satisfies Record<keyof CaseMessages, string>;
