export const enViewMessages = {
  "dashboard.eyebrow": "Umbrella Home / Work",
  "dashboard.title": "Quality dashboard",
  "dashboard.description": "One place for release readiness, manual execution, and defects.",
  "dashboard.create": "Create dashboard",
  "dashboard.testCases": "Test cases",
  "dashboard.readyCases": "Ready in repository",
  "dashboard.activeRuns": "Active runs",
  "dashboard.smokeRegression": "Smoke and regression",
  "dashboard.passRate": "Pass rate",
  "dashboard.executedCases": "Across executed cases",
  "dashboard.openDefects": "Open defects",
  "dashboard.needAttention": "Need attention",
  "dashboard.recentRuns": "Recent test runs",
  "dashboard.releaseStatus": "Release execution status",
  "dashboard.openAll": "Open all",
  "dashboard.noRuns": "No test runs yet",
  "dashboard.noRunsHint": "Start a smoke or regression run from a suite.",
  "dashboard.activity": "Activity",
  "dashboard.latestChanges": "Latest workspace changes",
  "dashboard.workspace": "Workspace",
  "config.eyebrow": "Workspace configuration",
  "config.title": "Environments",
  "config.description": "Reusable runtime targets captured with every test result.",
  "config.newEnvironment": "New environment",
  "config.copyBaseUrl": "Copy base URL",
  "config.executionDefaults": "Execution defaults",
  "config.executionDefaultsHint": "Browser, platform, build, and assignee are snapshotted into every run.",
  "integrations.eyebrow": "Cross-system quality",
  "integrations.title": "Integration testing",
  "integrations.description": "Model source-to-target contracts separately, then run them with the same immutable evidence trail.",
  "integrations.new": "New integration test",
  "integrations.checkCount": "Integration checks: {count}",
  "integrations.coverageTypes": "API, events, deep links, and data contracts",
  "integrations.systemCount": "Systems in coverage: {count}",
  "integrations.coverageHint": "Visible dependency coverage",
  "integrations.readyCount": "Ready for runs: {count}",
  "integrations.readyHint": "Available for test runs",
  "integrations.contracts": "Integration contracts",
  "integrations.contractsHint": "Every row is an executable manual contract with source and target context.",
  "integrations.searchAria": "Search integration tests",
  "integrations.searchPlaceholder": "Search integrations",
  "integrations.empty": "No integration tests yet",
  "integrations.emptyHint": "Create the first source-to-target contract and add it to a run.",
  "integrations.create": "Create integration test",
  "integrations.testCase": "Test case",
  "integrations.source": "Source",
  "integrations.target": "Target",
  "integrations.contract": "Contract",
  "integrations.status": "Status",
  "integrations.notSet": "Not set",
  "reports.eyebrow": "Defects and results",
  "reports.title": "Reports",
  "reports.description": "Issues created during manual execution retain their run and test case context.",
  "reports.newBug": "New bug report",
  "reports.openDefects": "Open defects: {count}",
  "reports.criticalDefects": "Critical defects: {count}",
  "reports.completedRuns": "Completed runs: {count}",
  "reports.empty": "No defects reported",
  "reports.emptyHint": "When a test fails, use Report bug to capture evidence and the execution snapshot.",
  "reports.key": "Key",
  "reports.summary": "Summary",
  "reports.severity": "Severity",
  "reports.status": "Status",
  "reports.assignee": "Assignee",
  "hooks.title": "Hooks are prepared",
  "hooks.description": "The extension point is visible now; CI, webhooks, and automation hooks will be connected in a later iteration.",
  "hooks.addLater": "Add hook · coming later",
} as const;

export type ViewMessages = typeof enViewMessages;
