export const enViewMessages = {
  "dashboard.eyebrow": "Umbrella Home / Work",
  "dashboard.title": "Quality dashboard",
  "dashboard.description": "One place for release readiness, manual execution, and defects.",
  "dashboard.create": "Create dashboard",
  "dashboard.testCases": "Test cases",
  "dashboard.readyCases": "Ready in repository",
  "dashboard.activeRuns": "Active runs",
  "dashboard.smokeRegression": "Smoke and regression",
  "dashboard.passRate": "Pass rate",
  "dashboard.executedCases": "Across executed cases",
  "dashboard.openDefects": "Open defects",
  "dashboard.needAttention": "Need attention",
  "dashboard.recentRuns": "Recent test runs",
  "dashboard.releaseStatus": "Release execution status",
  "dashboard.openAll": "Open all",
  "dashboard.noRuns": "No test runs yet",
  "dashboard.noRunsHint": "Start a smoke or regression run from a suite.",
  "dashboard.activity": "Activity",
  "dashboard.latestChanges": "Latest workspace changes",
  "dashboard.workspace": "Workspace",
  "dashboard.ledgerTitle": "Quality Operations Ledger",
  "dashboard.ledgerDescription": "A precise view of product quality and test operations.",
  "dashboard.last30Days": "Last 30 days",
  "dashboard.updatedAt": "Data as of {date}",
  "dashboard.summaryAria": "Current project quality summary",
  "dashboard.runsStarted": "Runs started",
  "dashboard.failures": "Failures",
  "dashboard.createdInWindow": "+{count} created in 30 days",
  "dashboard.startedInWindow": "+{count} started in 30 days",
  "dashboard.failedInWindow": "{count} recorded in 30 days",
  "dashboard.defectsInWindow": "+{count} created in 30 days",
  "dashboard.executedCount": "{count} executed results",
  "dashboard.qualityTrend": "30-day quality trend",
  "dashboard.qualityTrendHint": "Pass rate and recorded outcomes from available project runs.",
  "dashboard.qualityTrendAria": "Chart of pass rate, failures, defects, and runs started over 30 days",
  "dashboard.failureDistribution": "Failure distribution",
  "dashboard.currentResults": "Current loaded run results",
  "dashboard.failureDistributionAria": "Distribution of failed, blocked, and skipped results",
  "dashboard.results": "Results",
  "dashboard.noFailureResults": "No failed, blocked, or skipped results recorded.",
  "dashboard.run": "Release / Run",
  "dashboard.environment": "Environment",
  "dashboard.passed": "Passed",
  "dashboard.status": "Status",
  "dashboard.noActivity": "No activity recorded yet",
  "config.eyebrow": "Workspace configuration",
  "config.title": "Environments",
  "config.description": "Reusable runtime targets captured with every test result.",
  "config.newEnvironment": "New environment",
  "config.copyBaseUrl": "Copy base URL",
  "config.projectSettings": "Project settings",
  "config.projectKey": "Project key",
  "config.environmentsCount": "Environments: {count}",
  "config.environmentName": "Environment",
  "config.environmentKey": "Key",
  "config.baseUrl": "Base URL",
  "config.emptyEnvironments": "No environments yet",
  "config.emptyEnvironmentsHint": "Add the first runtime target for test runs.",
  "config.executionDefaults": "Execution defaults",
  "config.executionDefaultsHint": "Browser, platform, build, and assignee are snapshotted into every run.",
  "config.interface": "Interface and account",
  "config.appearance": "Appearance",
  "config.appearanceHint": "Choose the theme used on this device.",
  "config.lightMode": "Light",
  "config.darkMode": "Dark",
  "config.language": "Language",
  "config.languageHint": "Choose the interface language.",
  "config.session": "Session",
  "config.sessionHint": "Sign out of this TMS account.",
  "config.exchangeTitle": "Test-case exchange",
  "config.exchangeHint": "Export the current project or import a validated, repeatable TMS JSON package.",
  "config.exchangeExport": "Export JSON",
  "config.exchangeChoose": "Choose JSON",
  "config.exchangeImport": "Import cases",
  "config.exchangeImportCount": "Import {count} cases",
  "config.exchangeReady": "{count} cases are validated and ready to import.",
  "config.exchangeExporting": "Preparing the project export…",
  "config.exchangeExported": "Exported {count} cases.",
  "config.exchangeImporting": "Starting the import…",
  "config.exchangeProgress": "Imported or replayed {completed} of {total} cases.",
  "config.exchangeImported": "Imported or replayed {count} cases successfully.",
  "config.exchangePartial": "Import finished with {failed} failures. First failed source: {key}.",
  "config.exchangeInvalid": "The selected exchange file is invalid.",
  "config.exchangeFailed": "The test-case exchange failed.",
  "config.exchangeFileTooLarge": "The file is larger than the 5 MB import limit.",
  "config.exchangeConnectedOnly": "Import and export are available when TMS is connected.",
  "config.exchangeFormat": "Format: saturnusgo.tms.test-cases.v2 · v1 import supported · up to 2,000 cases.",
  "integrations.eyebrow": "Cross-system quality",
  "integrations.title": "Integration testing",
  "integrations.description": "Model source-to-target contracts separately, then run them with the same immutable evidence trail.",
  "integrations.new": "New integration test",
  "integrations.checkCount": "Integration checks: {count}",
  "integrations.coverageTypes": "API, events, deep links, and data contracts",
  "integrations.systemCount": "Systems in coverage: {count}",
  "integrations.coverageHint": "Visible dependency coverage",
  "integrations.readyCount": "Ready for runs: {count}",
  "integrations.readyHint": "Available for test runs",
  "integrations.contracts": "Integration contracts",
  "integrations.contractsHint": "Every row is an executable manual contract with source and target context.",
  "integrations.searchAria": "Search integration tests",
  "integrations.searchPlaceholder": "Search integrations",
  "integrations.empty": "No integration tests yet",
  "integrations.emptyHint": "Create the first source-to-target contract and add it to a run.",
  "integrations.noResults": "No matching integration tests",
  "integrations.noResultsHint": "Try a different key, title, or tag.",
  "integrations.create": "Create integration test",
  "integrations.testCase": "Test case",
  "integrations.source": "Source",
  "integrations.target": "Target",
  "integrations.contract": "Contract",
  "integrations.status": "Status",
  "integrations.notSet": "Not set",
  "apiTesting.title": "API Testing",
  "apiTesting.loading": "Loading Swagger documentation",
  "apiTesting.frameTitle": "Umbrella API Swagger documentation",
  "apiTesting.toolsLabel": "API testing tools",
  "reports.eyebrow": "Defects and results",
  "reports.title": "Reports",
  "reports.description": "Issues created during manual execution retain their run and test case context.",
  "reports.newBug": "New bug report",
  "reports.openDefects": "Open defects: {count}",
  "reports.openDefectsLabel": "Open defects",
  "reports.criticalDefects": "Critical defects: {count}",
  "reports.criticalDefectsLabel": "Critical defects",
  "reports.completedRuns": "Completed runs: {count}",
  "reports.completedRunsLabel": "Completed runs",
  "reports.empty": "No defects reported",
  "reports.emptyHint": "When a test fails, use Report bug to capture evidence and the execution snapshot.",
  "reports.key": "Key",
  "reports.summary": "Summary",
  "reports.component": "Component",
  "reports.severity": "Severity",
  "reports.status": "Status",
  "reports.assignee": "Assignee",
  "reports.backToList": "Back to reports",
  "reports.noDescription": "No additional description was provided.",
  "reports.priority": "Priority",
  "reports.reproducibility": "Reproducibility",
  "reports.expectedResult": "Expected result",
  "reports.actualResult": "Actual result",
  "reports.notProvided": "Not provided",
  "reports.executionContext": "Execution context",
  "reports.run": "Test run",
  "reports.runItem": "Run case",
  "reports.step": "Failed step",
  "reports.created": "Reported",
  "reports.noRunContext": "This defect was created without a linked test run.",
  "reports.openRun": "Open in test run",
  "reports.evidence": "Evidence and links",
  "reports.noEvidence": "No files or external links were attached.",
  "reports.labels": "Labels",
  "reports.noLabels": "No labels",
  "reports.searchPlaceholder": "Search by key, title, component, or label",
  "reports.openShort": "open",
  "reports.criticalShort": "critical",
  "reports.runsShort": "runs completed",
  "reports.defectsCount": "bug reports",
  "reports.emptySearch": "No bug reports match this search.",
  "reports.overview": "Overview",
  "reports.attachments": "Attachments",
  "reports.descriptionHeading": "Description",
  "reports.properties": "Properties",
  "reports.location": "Location",
  "reports.integration": "Integration",
  "reports.issueLink": "Issue link",
  "reports.noIssueLink": "No YouTrack issue has been created.",
  "reports.evidenceHint": "Screenshots, videos, documents, and external links from this bug report.",
  "hooks.loading": "Loading YouTrack status",
  "hooks.loadError": "YouTrack status is unavailable.",
  "hooks.retry": "Retry",
  "hooks.integration": "Issue integration",
  "hooks.openYouTrack": "Open YouTrack",
  "hooks.linked": "Linked defects",
  "hooks.pending": "Pending sync",
  "hooks.failed": "Failed",
  "hooks.lastSync": "Last sync",
  "hooks.routing": "Project routing",
  "hooks.routingHint": "Bug reports are sent only to the explicitly selected project.",
  "hooks.refresh": "Refresh",
} as const;

export type ViewMessages = typeof enViewMessages;
