import type { ViewMessages } from "./en";

export const ruViewMessages = {
  "dashboard.eyebrow": "Umbrella Home / Work",
  "dashboard.title": "Дашборд качества",
  "dashboard.description": "Готовность релиза, ручные прогоны и дефекты в одном месте.",
  "dashboard.create": "Создать дашборд",
  "dashboard.testCases": "Тест-кейсы",
  "dashboard.readyCases": "Готовы в репозитории",
  "dashboard.activeRuns": "Активные раны",
  "dashboard.smokeRegression": "Смоук и регресс",
  "dashboard.passRate": "Процент прохождения",
  "dashboard.executedCases": "Среди выполненных кейсов",
  "dashboard.openDefects": "Открытые дефекты",
  "dashboard.needAttention": "Требуют внимания",
  "dashboard.recentRuns": "Последние тест-раны",
  "dashboard.releaseStatus": "Статус проверки релиза",
  "dashboard.openAll": "Открыть все",
  "dashboard.noRuns": "Тест-ранов ещё нет",
  "dashboard.noRunsHint": "Запустите смоук- или регресс-ран из сьюта.",
  "dashboard.activity": "Активность",
  "dashboard.latestChanges": "Последние изменения рабочего пространства",
  "dashboard.workspace": "Рабочая область",
  "config.eyebrow": "Настройки рабочего пространства",
  "config.title": "Окружения",
  "config.description": "Повторно используемые цели, которые фиксируются с каждым результатом теста.",
  "config.newEnvironment": "Новое окружение",
  "config.copyBaseUrl": "Скопировать базовый URL",
  "config.executionDefaults": "Настройки выполнения",
  "config.executionDefaultsHint": "Браузер, платформа, сборка и исполнитель фиксируются в каждом ране.",
  "integrations.eyebrow": "Качество взаимодействия систем",
  "integrations.title": "Интеграционное тестирование",
  "integrations.description": "Описывайте контракты между системами отдельно и запускайте их с неизменяемой историей материалов.",
  "integrations.new": "Новый интеграционный тест",
  "integrations.checkCount": "Интеграционных проверок: {count}",
  "integrations.coverageTypes": "API, события, диплинки и контракты данных",
  "integrations.systemCount": "Систем в покрытии: {count}",
  "integrations.coverageHint": "Видимое покрытие зависимостей",
  "integrations.readyCount": "Готово к запускам: {count}",
  "integrations.readyHint": "Можно включать в тест-раны",
  "integrations.contracts": "Интеграционные контракты",
  "integrations.contractsHint": "Каждая строка — исполняемый ручной контракт с контекстом исходной и целевой системы.",
  "integrations.searchAria": "Поиск интеграционных тестов",
  "integrations.searchPlaceholder": "Поиск интеграций",
  "integrations.empty": "Интеграционных тестов ещё нет",
  "integrations.emptyHint": "Создайте первый контракт между системами и добавьте его в ран.",
  "integrations.create": "Создать интеграционный тест",
  "integrations.testCase": "Тест-кейс",
  "integrations.source": "Источник",
  "integrations.target": "Цель",
  "integrations.contract": "Контракт",
  "integrations.status": "Статус",
  "integrations.notSet": "Не указано",
  "reports.eyebrow": "Дефекты и результаты",
  "reports.title": "Отчёты",
  "reports.description": "Дефекты, созданные во время ручного прогона, сохраняют контекст рана и тест-кейса.",
  "reports.newBug": "Новый баг-репорт",
  "reports.openDefects": "Открытых дефектов: {count}",
  "reports.criticalDefects": "Критических дефектов: {count}",
  "reports.completedRuns": "Завершённых ранов: {count}",
  "reports.empty": "Дефектов нет",
  "reports.emptyHint": "Если тест провален, используйте «Завести баг», чтобы сохранить материалы и снимок выполнения.",
  "reports.key": "Ключ",
  "reports.summary": "Описание",
  "reports.severity": "Серьёзность",
  "reports.status": "Статус",
  "reports.assignee": "Исполнитель",
  "hooks.title": "Хуки подготовлены",
  "hooks.description": "Точка расширения уже видна; CI, вебхуки и хуки автоматизации будут подключены в следующей итерации.",
  "hooks.addLater": "Добавить хук · позже",
} satisfies Record<keyof ViewMessages, string>;
