import type { ViewMessages } from "./en";

export const ruViewMessages = {
  "dashboard.eyebrow": "Umbrella Home / Work",
  "dashboard.title": "Дашборд качества",
  "dashboard.description": "Готовность релиза, ручные прогоны и дефекты в одном месте.",
  "dashboard.create": "Создать дашборд",
  "dashboard.testCases": "Тест-кейсы",
  "dashboard.readyCases": "Готовы в репозитории",
  "dashboard.activeRuns": "Активные раны",
  "dashboard.smokeRegression": "Смоук и регресс",
  "dashboard.passRate": "Процент прохождения",
  "dashboard.executedCases": "Среди выполненных кейсов",
  "dashboard.openDefects": "Открытые дефекты",
  "dashboard.needAttention": "Требуют внимания",
  "dashboard.recentRuns": "Последние тест-раны",
  "dashboard.releaseStatus": "Статус проверки релиза",
  "dashboard.openAll": "Открыть все",
  "dashboard.noRuns": "Тест-ранов ещё нет",
  "dashboard.noRunsHint": "Запустите смоук- или регресс-ран из сьюта.",
  "dashboard.activity": "Активность",
  "dashboard.latestChanges": "Последние изменения рабочего пространства",
  "dashboard.workspace": "Рабочая область",
  "dashboard.ledgerTitle": "Реестр качества",
  "dashboard.ledgerDescription": "Точная картина качества продукта и процессов тестирования.",
  "dashboard.last30Days": "Последние 30 дней",
  "dashboard.updatedAt": "Обновлено {date}",
  "dashboard.summaryAria": "Сводка качества текущего проекта",
  "dashboard.runsStarted": "Запущено прогонов",
  "dashboard.failures": "Провалы",
  "dashboard.createdInWindow": "+{count} создано за 30 дней",
  "dashboard.startedInWindow": "+{count} запущено за 30 дней",
  "dashboard.failedInWindow": "{count} зафиксировано за 30 дней",
  "dashboard.defectsInWindow": "+{count} создано за 30 дней",
  "dashboard.executedCount": "{count} выполненных результатов",
  "dashboard.qualityTrend": "Тренд качества за 30 дней",
  "dashboard.qualityTrendHint": "Процент прохождения и результаты доступных прогонов проекта.",
  "dashboard.qualityTrendAria": "График прохождения, провалов, дефектов и запусков за 30 дней",
  "dashboard.failureDistribution": "Распределение провалов",
  "dashboard.currentResults": "Текущие загруженные результаты прогонов",
  "dashboard.failureDistributionAria": "Распределение проваленных, заблокированных и пропущенных результатов",
  "dashboard.results": "Результаты",
  "dashboard.noFailureResults": "Проваленных, заблокированных или пропущенных результатов нет.",
  "dashboard.run": "Релиз / Прогон",
  "dashboard.environment": "Среда",
  "dashboard.passed": "Пройдено",
  "dashboard.status": "Статус",
  "dashboard.noActivity": "Активности пока нет",
  "config.eyebrow": "Настройки рабочего пространства",
  "config.title": "Окружения",
  "config.description": "Повторно используемые цели, которые фиксируются с каждым результатом теста.",
  "config.newEnvironment": "Новое окружение",
  "config.copyBaseUrl": "Скопировать базовый URL",
  "config.projectSettings": "Настройки проекта",
  "config.projectKey": "Ключ проекта",
  "config.environmentsCount": "Окружения: {count}",
  "config.environmentName": "Окружение",
  "config.environmentKey": "Ключ",
  "config.baseUrl": "Базовый URL",
  "config.emptyEnvironments": "Окружений пока нет",
  "config.emptyEnvironmentsHint": "Добавьте первое окружение для тест-ранов.",
  "config.executionDefaults": "Настройки выполнения",
  "config.executionDefaultsHint": "Браузер, платформа, сборка и исполнитель фиксируются в каждом ране.",
  "config.interface": "Интерфейс и аккаунт",
  "config.appearance": "Оформление",
  "config.appearanceHint": "Выберите тему для этого устройства.",
  "config.lightMode": "Светлая",
  "config.darkMode": "Тёмная",
  "config.language": "Язык",
  "config.languageHint": "Выберите язык интерфейса.",
  "config.session": "Сессия",
  "config.sessionHint": "Выйти из этого аккаунта TMS.",
  "config.exchangeTitle": "Импорт и экспорт тест-кейсов",
  "config.exchangeHint": "Экспортируйте текущий проект или импортируйте проверенный повторяемый пакет TMS JSON.",
  "config.exchangeExport": "Экспортировать JSON",
  "config.exchangeChoose": "Выбрать JSON",
  "config.exchangeImport": "Импортировать кейсы",
  "config.exchangeImportCount": "Импортировать {count} кейсов",
  "config.exchangeReady": "Проверено и готово к импорту: {count} кейсов.",
  "config.exchangeExporting": "Подготавливаю экспорт проекта…",
  "config.exchangeExported": "Экспортировано кейсов: {count}.",
  "config.exchangeImporting": "Запускаю импорт…",
  "config.exchangeProgress": "Импортировано или повторено: {completed} из {total}.",
  "config.exchangeImported": "Успешно импортировано или повторено кейсов: {count}.",
  "config.exchangePartial": "Импорт завершён с ошибками: {failed}. Первый источник: {key}.",
  "config.exchangeInvalid": "Выбранный файл обмена некорректен.",
  "config.exchangeFailed": "Не удалось выполнить импорт или экспорт тест-кейсов.",
  "config.exchangeFileTooLarge": "Файл превышает лимит импорта 5 МБ.",
  "config.exchangeConnectedOnly": "Импорт и экспорт доступны при подключении к TMS.",
  "config.exchangeFormat": "Формат: saturnusgo.tms.test-cases.v1 · до 2000 кейсов · повторный импорт безопасен.",
  "integrations.eyebrow": "Качество взаимодействия систем",
  "integrations.title": "Интеграционное тестирование",
  "integrations.description": "Описывайте контракты между системами отдельно и запускайте их с неизменяемой историей материалов.",
  "integrations.new": "Новый интеграционный тест",
  "integrations.checkCount": "Интеграционных проверок: {count}",
  "integrations.coverageTypes": "API, события, диплинки и контракты данных",
  "integrations.systemCount": "Систем в покрытии: {count}",
  "integrations.coverageHint": "Видимое покрытие зависимостей",
  "integrations.readyCount": "Готово к запускам: {count}",
  "integrations.readyHint": "Можно включать в тест-раны",
  "integrations.contracts": "Интеграционные контракты",
  "integrations.contractsHint": "Каждая строка — исполняемый ручной контракт с контекстом исходной и целевой системы.",
  "integrations.searchAria": "Поиск интеграционных тестов",
  "integrations.searchPlaceholder": "Поиск интеграций",
  "integrations.empty": "Интеграционных тестов ещё нет",
  "integrations.emptyHint": "Создайте первый контракт между системами и добавьте его в ран.",
  "integrations.noResults": "Ничего не найдено",
  "integrations.noResultsHint": "Попробуйте другой ключ, название или тег.",
  "integrations.create": "Создать интеграционный тест",
  "integrations.testCase": "Тест-кейс",
  "integrations.source": "Источник",
  "integrations.target": "Цель",
  "integrations.contract": "Контракт",
  "integrations.status": "Статус",
  "integrations.notSet": "Не указано",
  "apiTesting.title": "API Testing",
  "apiTesting.description": "Изучайте контракт Umbrella API и запускайте запросы прямо в Swagger.",
  "apiTesting.authHint": "Swagger использует собственный вход. Сессия TMS ему не передаётся.",
  "apiTesting.openExternal": "Открыть Swagger",
  "apiTesting.reload": "Перезагрузить",
  "apiTesting.signOut": "Выйти из Swagger",
  "apiTesting.loading": "Загрузка документации Swagger",
  "apiTesting.frameTitle": "Документация Umbrella API в Swagger",
  "apiTesting.toolsLabel": "Инструменты API-тестирования",
  "apiTesting.postmanDescription": "Создавайте и запускайте API-запросы в Postman Web.",
  "apiTesting.postmanAuthHint": "Postman использует собственный аккаунт. Сессия TMS ему не передаётся.",
  "apiTesting.openPostman": "Открыть Postman",
  "apiTesting.postmanExternalOnly": "Postman запрещает встраивать полноценное веб-приложение во фрейм. Оно открывается в защищённой вкладке и самостоятельно выполняет вход.",
  "reports.eyebrow": "Дефекты и результаты",
  "reports.title": "Отчёты",
  "reports.description": "Дефекты, созданные во время ручного прогона, сохраняют контекст рана и тест-кейса.",
  "reports.newBug": "Новый баг-репорт",
  "reports.openDefects": "Открытых дефектов: {count}",
  "reports.openDefectsLabel": "Открытые дефекты",
  "reports.criticalDefects": "Критических дефектов: {count}",
  "reports.criticalDefectsLabel": "Критические дефекты",
  "reports.completedRuns": "Завершённых ранов: {count}",
  "reports.completedRunsLabel": "Завершённые раны",
  "reports.empty": "Дефектов нет",
  "reports.emptyHint": "Если тест провален, используйте «Завести баг», чтобы сохранить материалы и снимок выполнения.",
  "reports.key": "Ключ",
  "reports.summary": "Описание",
  "reports.component": "Компонент",
  "reports.severity": "Серьёзность",
  "reports.status": "Статус",
  "reports.assignee": "Исполнитель",
  "reports.backToList": "Назад к отчётам",
  "reports.noDescription": "Дополнительное описание не указано.",
  "reports.priority": "Приоритет",
  "reports.reproducibility": "Воспроизводимость",
  "reports.expectedResult": "Ожидаемый результат",
  "reports.actualResult": "Фактический результат",
  "reports.notProvided": "Не указано",
  "reports.executionContext": "Контекст выполнения",
  "reports.run": "Тест-ран",
  "reports.runItem": "Кейс в ране",
  "reports.step": "Проваленный шаг",
  "reports.created": "Создан",
  "reports.noRunContext": "Этот дефект создан без привязки к тест-рану.",
  "reports.openRun": "Открыть в тест-ране",
  "reports.evidence": "Материалы и ссылки",
  "reports.noEvidence": "Файлы и внешние ссылки не прикреплены.",
  "reports.labels": "Метки",
  "reports.noLabels": "Меток нет",
  "hooks.title": "Хуки подготовлены",
  "hooks.description": "Точка расширения уже видна; CI, вебхуки и хуки автоматизации будут подключены в следующей итерации.",
  "hooks.addLater": "Добавить хук · позже",
} satisfies Record<keyof ViewMessages, string>;
