import { bullets, note, paragraph, section, steps, table, type DocArticle } from "../../model/article";
import { settingsWalkthrough } from "../walkthroughs/settings/access";
export const referenceArticles: DocArticle[] = [
  { id: "permissions", title: "Access and settings", group: "reference", description: "Check your role, project access, and interface settings before changing data.",
    keywords: ["permissions", "role", "admin", "403", "theme", "language", "access", "sign in"], related: ["company-access", "company-administration", "workspace", "integration-overview"],
    sections: [
      section("permissions", "If an action is unavailable", steps(
        ["Check the context", "Verify your account and selected project. A record link does not grant permission to view it."],
        ["Read the reason", "An unavailable button may indicate missing permissions, unsaved changes, or an unsuitable record state."],
        ["Contact your administrator", "Provide the project, action, and message text. Integration changes require a workspace administrator or QA manager; external permissions are checked separately."])),
      section("roles", "Who manages access", table(["Role", "Admin panel", "Hook configuration"], ["Administrator", "Available", "Available"], ["QA manager", "Unavailable", "Available"], ["Tester", "Unavailable", "Unavailable"], ["Viewer", "Unavailable", "Unavailable"])),
      section("settings", "Settings sections", paragraph("Open **Settings** in the global sidebar. Under **Project**, choose **General** for the project name and key, **Environments** for test environments, or **Import and export** to transfer cases. The **Personal settings** group contains **Appearance and language**, **Notifications**, and **Account and session**. Notification categories and Telegram/browser connections are configured here; the sidebar bell opens the event feed."),
        paragraph("Import opens a dedicated **Import test cases** page with JSON, project, and folder selection and source file history. Continue a partial import there before leaving or reloading. History lets you open and download the source file; deleting it does not delete cases already created. JSON export transfers case contents and folders, but is not a complete project backup.")),
      section("settings-walkthrough", "Settings walkthrough", settingsWalkthrough),
      section("appearance", "Theme and language", paragraph("In **Settings → Appearance and language**, choose a light or dark theme from its preview card, then Russian or English as the application language. Changes apply immediately. This guide is written in English and uses English control labels.")),
      section("session", "Sign-in problems", bullets("If your session expires, sign in again and return through the record link.",
        "If a project appears empty, check the selector and filters.", "For a loading error, use the available retry action and share the error text with your administrator without secrets.")),
    ] },
  { id: "glossary", title: "Falcon terminology", group: "reference", description: "A short glossary of the entities and states used in TMS.",
    keywords: ["dictionary", "terms", "glossary", "snapshot", "revision", "defect", "status"], related: ["quick-start", "dashboard"],
    sections: [
      section("entities", "Core entities", table(["Term", "Meaning"],
        ["Test case", "A test description with conditions, a scenario, and an expected result."],
        ["Revision", "A saved version of a case or shared procedure's contents."],
        ["Shared step", "A reusable procedure inserted into project cases."],
        ["Suite", "A collection of cases selected manually or by tags."],
        ["Run", "A specific execution of a selection in an environment and build."],
        ["Snapshot", "The captured test contents used in a particular run."],
        ["Defect / bug", "A recorded difference between actual and expected behavior."],
        ["Retest", "A new test after a problem has been fixed."])),
      section("states", "Different kinds of status", table(["Status of", "What it describes"],
        ["A repository case", "The readiness of the scenario itself, such as draft."], ["Case execution", "The result: passed, failed, blocked, and other execution states."],
        ["A defect", "The fix stage: open, in progress, ready for retest, verified, closed."],
        ["Delivery", "Whether an event reached an external service or is awaiting processing or recovery."]),
        note("Keep these meanings separate", "A draft case says nothing about a run result. Completing a run does not mean every test passed. Delivering a notification does not mean a defect was fixed.")),
      section("integration", "Integration terminology", table(["Term", "Meaning"],
        ["Webhook", "An incoming service event sent to a configured URL."], ["API token", "Falcon's access to an external service's API."],
        ["Signing secret", "A secret for authenticating incoming webhooks; separate from an API token."],
        ["Linked record", "An external issue, card, message, or report associated with a Falcon record."],
        ["Testing rule", "Maps a GitHub event to the required suite, environment, and filters."])),
    ] },
];
