"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useTheme } from "next-themes";
import useReveal from "../../../../../shared/lib/useReveal";
import {
  computeMethodology,
  fmMoney,
  type Horizon,
} from "../../../services/methodology-calculator";

type ValueRow = {
  label: string;
  text: string;
  value: string;
};

type FormulaRow = {
  code: string;
  label: string;
  text: string;
};

const HORIZONS: Horizon[] = ["3", "5", "10"];
const BASE_NONRIDE_Y3_M = 43.6;

function ValueRows({ rows }: { rows: readonly ValueRow[] }) {
  return (
    <div className="md-value-rows">
      {rows.map((row) => (
        <article className="md-value-row reveal" key={row.label}>
          <span>{row.label}</span>
          <p>{row.text}</p>
          <strong>{row.value}</strong>
        </article>
      ))}
    </div>
  );
}

function FormulaRows({ rows }: { rows: readonly FormulaRow[] }) {
  return (
    <div className="md-formula-rows">
      {rows.map((row) => (
        <article className="md-formula-row reveal" key={row.label}>
          <span>{row.label}</span>
          <code>{row.code}</code>
          <p>{row.text}</p>
        </article>
      ))}
    </div>
  );
}

export default function MethodologyClient({ initialH = "3" as Horizon }) {
  const [h, setH] = useState<Horizon>(initialH);
  const sp = useSearchParams();
  const router = useRouter();
  const { resolvedTheme } = useTheme();
  const tone: "light" | "dark" = resolvedTheme === "light" ? "light" : "dark";

  useReveal();

  const data = useMemo(() => computeMethodology(h), [h]);
  const streamMultiplier = data.nonRideM / BASE_NONRIDE_Y3_M;
  const animKey = `methodology-${h}`;
  const activeHorizonIndex = HORIZONS.indexOf(h);

  useEffect(() => {
    const query = new URLSearchParams(Array.from(sp.entries()));
    if (query.get("h") === h) return;

    query.set("h", h);
    router.replace(`?${query.toString()}`, { scroll: false });
  }, [h, router, sp]);

  const summaryRows: ValueRow[] = [
    {
      label: "Selected horizon",
      text: "The active planning window used by the investor model.",
      value: `${h} years`,
    },
    {
      label: "Total revenue",
      text: "Top-line revenue target for the selected horizon.",
      value: fmMoney(data.totalUSD),
    },
    {
      label: "Ride revenue",
      text: "Taxi revenue after the non-ride layer is separated.",
      value: fmMoney(data.rideUSD),
    },
    {
      label: "Non-ride revenue",
      text: "Subscriptions, bookings, events, and B2B2C revenue combined.",
      value: fmMoney(data.nonRideUSD),
    },
  ];

  const inputRows: ValueRow[] = [
    {
      label: "Y3 active users",
      text: "Starting user base used for the three-year model.",
      value: "2.5M",
    },
    {
      label: "Y3 net ARPU",
      text: "Annual net revenue per active user in the baseline scenario.",
      value: "$74.8",
    },
    {
      label: "Maximum user bound",
      text: "Upper guardrail used to avoid unconstrained growth assumptions.",
      value: "20M",
    },
  ];

  const sourceRows: ValueRow[] = [
    {
      label: "Baseline split",
      text: "Y3 total revenue is fixed at $187M, with $43.6M assigned to non-ride revenue.",
      value: "23.3% non-ride",
    },
    {
      label: "Planning targets",
      text: "Five-year and ten-year totals are planning targets, not generated by a hidden formula.",
      value: "$400M / $1B",
    },
    {
      label: "Non-ride share",
      text: "Non-ride share increases as the product expands beyond the taxi layer.",
      value: "35% / 40%",
    },
  ];

  const formulaRows: FormulaRow[] = [
    {
      label: "Total revenue",
      code: "Users(h) × ARPU_net(h) × TakeRate = Total(h)",
      text: "ARPU is already net in this model, so TakeRate remains explicit but equals one.",
    },
    {
      label: "Non-ride revenue",
      code: "NonRide(h) = Share(h) × Total(h)",
      text: "The share is 23.3% for Y3, 35% for Y5, and 40% for Y10.",
    },
    {
      label: "Ride revenue",
      code: "Ride(h) = Total(h) − NonRide(h)",
      text: "Ride revenue is calculated as the remaining part of the selected total.",
    },
    {
      label: "Stream allocation",
      code: "Stream(h) = Stream(Y3) × NonRide(h) / NonRide(Y3)",
      text: "Each non-ride stream keeps the same baseline proportion unless the model is changed.",
    },
  ];

  return (
    <main className="md-root" data-tone={tone}>
      <section className="md-page-head" aria-labelledby="methodology-title">
        <div className="md-page-head-copy reveal">
          <span className="md-kicker">Methodology</span>
          <h1 id="methodology-title">How the investor model is calculated.</h1>
          <p>
            This page explains the assumptions, formulas, revenue split, and
            stream allocation behind the investor numbers. No narrative effects,
            no hidden steps — only the calculation path.
          </p>
        </div>

        <div
          className="md-toggle"
          role="tablist"
          aria-label="Projection horizon"
          data-active-index={activeHorizonIndex}
        >
          <div className="md-toggle-thumb" aria-hidden="true" />
          {HORIZONS.map((option) => (
            <button
              key={option}
              type="button"
              role="tab"
              aria-selected={option === h}
              className="md-toggle-btn"
              onClick={() => setH(option)}
            >
              {option}y
            </button>
          ))}
        </div>
      </section>

      <section
        className="md-summary-section"
        aria-label="Selected model output"
      >
        <ValueRows rows={summaryRows} />
      </section>

      <section className="md-section md-split-section" id="composition">
        <div className="md-section-copy reveal">
          <span className="md-kicker">Revenue composition</span>
          <h2>Selected horizon output.</h2>
          <p>
            The chart is only a visual aid. The values on the right are the
            auditable output of the formula for the selected horizon.
          </p>
        </div>

        <div className="md-data-panel" key={animKey}>
          <div className="md-total-row">
            <span>Total</span>
            <strong>{fmMoney(data.totalUSD)}</strong>
          </div>

          <div
            className="md-comp-bar"
            aria-label="Ride and non-ride revenue composition"
          >
            <div
              className="md-seg md-seg-ride"
              style={{ width: data.ridePct }}
            />
            <div
              className="md-seg md-seg-nonride"
              style={{ width: data.nonRidePct }}
            />
          </div>

          <div className="md-chart-row">
            <svg
              width="104"
              height="104"
              viewBox="0 0 104 104"
              role="img"
              aria-label={`Non-ride ${data.nonRidePct}`}
            >
              <defs>
                <linearGradient
                  id="methodology-ring"
                  x1="0"
                  y1="0"
                  x2="1"
                  y2="1"
                >
                  <stop offset="0%" stopColor="var(--cream)" />
                  <stop offset="100%" stopColor="var(--accent-soft)" />
                </linearGradient>
              </defs>
              <g transform="translate(52,52)">
                <circle
                  r="40"
                  fill="none"
                  stroke="var(--line-strong)"
                  strokeWidth="12"
                />
                <circle
                  r="40"
                  fill="none"
                  stroke="url(#methodology-ring)"
                  strokeWidth="12"
                  strokeLinecap="round"
                  strokeDasharray={`${data.nonRideShare * 2 * Math.PI * 40} ${2 * Math.PI * 40}`}
                  strokeDashoffset="0"
                  transform="rotate(-90)"
                >
                  <animate
                    attributeName="stroke-dasharray"
                    dur="620ms"
                    fill="freeze"
                    from={`0 ${2 * Math.PI * 40}`}
                    to={`${data.nonRideShare * 2 * Math.PI * 40} ${2 * Math.PI * 40}`}
                  />
                </circle>
              </g>
            </svg>

            <div className="md-split-values">
              <article>
                <span>Ride</span>
                <strong>{data.ridePct}</strong>
                <p>{fmMoney(data.rideUSD)}</p>
              </article>
              <article>
                <span>Non-ride</span>
                <strong>{data.nonRidePct}</strong>
                <p>{fmMoney(data.nonRideUSD)}</p>
              </article>
            </div>
          </div>
        </div>
      </section>

      <section className="md-section" id="formulas">
        <div className="md-section-copy reveal">
          <span className="md-kicker">Formulas</span>
          <h2>The model is intentionally readable.</h2>
          <p>
            These are the formulas used by the page. They are short on purpose:
            the goal is to let an investor challenge the assumptions without
            reverse-engineering the UI.
          </p>
        </div>
        <FormulaRows rows={formulaRows} />
      </section>

      <section className="md-section md-split-section">
        <div className="md-section-copy reveal">
          <span className="md-kicker">Inputs and guardrails</span>
          <h2>What the calculation depends on.</h2>
          <p>
            Inputs are separated from outputs so the model can be reviewed or
            adjusted without mixing assumptions with results.
          </p>
        </div>
        <div className="md-source-stack">
          <ValueRows rows={inputRows} />
          <ValueRows rows={sourceRows} />
        </div>
      </section>

      <section className="md-section md-stream-section" id="streams">
        <div className="md-section-copy reveal">
          <span className="md-kicker">Non-ride streams</span>
          <h2>Allocation of the non-ride layer.</h2>
          <p>
            Stream values are derived from the Y3 stream mix and scaled to match
            the selected non-ride total. The audit row confirms that the stream
            sum reconciles with the non-ride value.
          </p>
        </div>

        <div className="md-stream-rows" key={animKey}>
          {data.streamsM.map((stream) => {
            const width = `${Math.min(100, (stream.vM / Math.max(1, data.nonRideM)) * 100)}%`;
            return (
              <article className="md-stream-row" key={stream.id}>
                <div>
                  <span>{stream.label}</span>
                  <p>Multiplier {streamMultiplier.toFixed(2)}×</p>
                </div>
                <div className="md-stream-measure" aria-hidden>
                  <i style={{ width }} />
                </div>
                <strong>
                  $
                  {stream.vM.toLocaleString("en-US", {
                    maximumFractionDigits: 1,
                  })}
                  M
                </strong>
              </article>
            );
          })}

          <div className="md-audit-row">
            <span>Streams total</span>
            <strong>${data.sumStreamsM.toFixed(1)}M</strong>
            <span>Non-ride total</span>
            <strong>${data.nonRideM.toFixed(1)}M</strong>
            <span>Difference</span>
            <strong>
              {data.deltaStreamsM === 0
                ? "$0.0M"
                : `$${data.deltaStreamsM.toFixed(1)}M`}
            </strong>
          </div>
        </div>
      </section>
    </main>
  );
}
