import type { TmsLocale } from "../../../localization/model/locale";

const en = {
  editTitle: "Edit test case",
  createTitle: "Create test case",
  editSubtitle: "Saving creates a new immutable revision.",
  createSubtitle: "A guided flow for a repeatable manual verification.",
  basics: "Basics",
  procedure: "Procedure",
  review: "Review",
  blankManual: "Blank manual",
  blankManualHint: "Start with one empty step",
  smokeCheck: "Smoke check",
  smokeCheckHint: "Critical and ready to run",
  checklist: "Checklist",
  checklistHint: "Fast repeated verification",
  title: "Test case title",
  titlePlaceholder: "User can complete checkout",
  folder: "Repository folder",
  folderPlaceholder: "/Checkout",
  description: "Description",
  descriptionPlaceholder: "What behavior and risk does this test cover?",
  priority: "Priority",
  lifecycle: "Lifecycle",
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
  draft: "Draft",
  ready: "Ready",
  deprecated: "Deprecated",
  archived: "Archived",
  owner: "Owner",
  component: "Component",
  estimate: "Estimate, minutes",
  tags: "Tags",
  tagsPlaceholder: "smoke, regression",
  preconditions: "Preconditions",
  preconditionsPlaceholder: "State required before the tester starts",
  testData: "Test data",
  testDataPlaceholder: "Accounts, payloads, feature flags, or fixtures",
  checklistItems: "Checklist items",
  checklistItemsHint: "Each required item must be confirmed before the case can pass.",
  addItem: "Add item",
  itemPlaceholder: "Condition to verify",
  required: "Required",
  removeChecklistItem: "Remove checklist item",
  executionSteps: "Execution steps",
  executionStepsHint: "Write one action and one observable result per row.",
  addStep: "Add step",
  actionPlaceholder: "Tester action",
  expectedPlaceholder: "Observable expected result",
  removeExecutionStep: "Remove execution step",
  noDescription: "No description",
  minuteShort: "min",
  attachments: "Add screenshots, video, or supporting files",
  removeAttachment: "Remove attachment",
  revisionNote: "Revision note",
  revisionNotePlaceholder: "What changed?",
  cancel: "Cancel",
  back: "Back",
  continue: "Continue",
  saveRevision: "Save revision",
  verifyExpectedCondition: "Verify the expected condition",
} as const;

const ru = {
  editTitle: "Редактировать тест-кейс",
  createTitle: "Создать тест-кейс",
  editSubtitle: "При сохранении будет создана новая неизменяемая ревизия.",
  createSubtitle: "Пошаговое создание повторяемой ручной проверки.",
  basics: "Основное",
  procedure: "Шаги",
  review: "Проверка",
  blankManual: "Пустой ручной кейс",
  blankManualHint: "Начните с одного пустого шага",
  smokeCheck: "Смоук-проверка",
  smokeCheckHint: "Критическая и готовая к запуску",
  checklist: "Чек-лист",
  checklistHint: "Быстрая повторяемая проверка",
  title: "Название тест-кейса",
  titlePlaceholder: "Пользователь может завершить оформление заказа",
  folder: "Папка репозитория",
  folderPlaceholder: "/Оформление заказа",
  description: "Описание",
  descriptionPlaceholder: "Какое поведение и риск покрывает эта проверка?",
  priority: "Приоритет",
  lifecycle: "Состояние",
  low: "Низкий",
  medium: "Средний",
  high: "Высокий",
  critical: "Критический",
  draft: "Черновик",
  ready: "Готов",
  deprecated: "Устарел",
  archived: "В архиве",
  owner: "Ответственный",
  component: "Компонент",
  estimate: "Оценка, минуты",
  tags: "Теги",
  tagsPlaceholder: "smoke, regression",
  preconditions: "Предусловия",
  preconditionsPlaceholder: "Состояние системы до начала проверки",
  testData: "Тестовые данные",
  testDataPlaceholder: "Аккаунты, payload, feature flags или фикстуры",
  checklistItems: "Пункты чек-листа",
  checklistItemsHint: "Для прохождения кейса нужно подтвердить каждый обязательный пункт.",
  addItem: "Добавить пункт",
  itemPlaceholder: "Условие для проверки",
  required: "Обязательно",
  removeChecklistItem: "Удалить пункт чек-листа",
  executionSteps: "Шаги выполнения",
  executionStepsHint: "Для каждой строки укажите действие и наблюдаемый результат.",
  addStep: "Добавить шаг",
  actionPlaceholder: "Действие тестировщика",
  expectedPlaceholder: "Ожидаемый наблюдаемый результат",
  removeExecutionStep: "Удалить шаг выполнения",
  noDescription: "Описание не указано",
  minuteShort: "мин",
  attachments: "Добавить скриншоты, видео или другие файлы",
  removeAttachment: "Удалить вложение",
  revisionNote: "Комментарий к ревизии",
  revisionNotePlaceholder: "Что изменилось?",
  cancel: "Отмена",
  back: "Назад",
  continue: "Продолжить",
  saveRevision: "Сохранить ревизию",
  verifyExpectedCondition: "Подтвердить ожидаемое условие",
} satisfies Record<keyof typeof en, string>;

export const getCaseDialogCopy = (locale: TmsLocale) =>
  locale === "ru" ? ru : en;
