export const ruHooksCopy = {
  workspaceSettings: "Настройки рабочего пространства",
  integrations: "Интеграции",
  integrationsHint: "Подключите сервисы команды. Каждое подключение настраивается для текущего пространства.",
  groups: { api: "API и контракты", tracker: "Задачи и планирование", delivery: "Код и сборки", communication: "Коммуникация и знания" },
  groupHints: { api: "Спецификации и интерактивная документация", tracker: "Дефекты и рабочие процессы", delivery: "Репозитории и CI", communication: "Уведомления и документация" },
  statuses: { connected: "Подключён", available: "Доступен", attention: "Требует внимания", checking: "Проверяем", planned: "Скоро" },
  refresh: "Обновить",
  retry: "Повторить",
  back: "Назад к интеграциям",
  loading: "Загрузка настроек YouTrack",
  loadError: "Не удалось открыть настройки YouTrack",
  loadErrorHint: "Повторите запрос. Если ошибка останется, проверьте доступ к рабочему пространству.",
  openYouTrack: "Открыть YouTrack",
  save: "Сохранить",
  saving: "Сохраняем…",
  saved: "Настройки сохранены",
  stale: "Настройки изменились в другой вкладке. Мы загрузили свежую версию.",
  saveFailure: "Не удалось сохранить настройки",
  disconnectFailure: "Не удалось отключить YouTrack",
  disconnectBusy: "Синхронизация ещё выполняется. Подождите немного и повторите отключение.",
  disconnected: (count: number) => `YouTrack отключён. Старые связи больше не синхронизируются: ${count}.`,
  changeConnection: "Сменить YouTrack",
  disconnectTitle: "Сменить подключение YouTrack?",
  disconnectText: "Falcon перестанет синхронизировать уже связанные задачи. Сами задачи в YouTrack останутся без изменений.",
  disconnectConfirm: "Отключить и продолжить",
  cancel: "Отмена",
  connectionSuccess: (count: number) => count === 1
    ? "Подключение установлено. Найден 1 проект."
    : `Подключение установлено. Найдено проектов: ${count}.`,
  connectionFailure: "Не удалось подключиться. Проверьте адрес, токен и права пользователя.",
  discoveryUnsupported: "YouTrack не вернул проекты и поля. Проверьте адрес сервера и доступ к API.",
  connection: "Подключение",
  connectionHint: "Укажите адрес YouTrack и токен пользователя с доступом к нужным проектам.",
  enabled: "Синхронизировать с YouTrack",
  enabledHint: "Новые баг-репорты можно будет отправлять в выбранные проекты.",
  baseUrl: "Адрес YouTrack",
  apiToken: "Постоянный токен",
  tokenStored: "Токен уже сохранён",
  tokenPlaceholder: "perm:…",
  tokenHint: "Falcon не показывает сохранённый токен повторно.",
  tokenHelpLabel: "Как получить постоянный токен",
  tokenHelpTitle: "Постоянный токен YouTrack",
  tokenHelpSteps: [
    "Откройте аватар в YouTrack и выберите «Профиль».",
    "Перейдите в «Безопасность аккаунта» → «Токены».",
    "Нажмите «Новый токен», задайте имя Falcon и выберите область YouTrack.",
    "Создайте токен и сразу скопируйте его — позже YouTrack его не покажет.",
  ],
  tokenHelpNote: "Falcon увидит только проекты и задачи, доступные владельцу токена.",
  tokenHelpLink: "Открыть инструкцию YouTrack",
  showToken: "Показать токен",
  hideToken: "Скрыть токен",
  connect: "Подключить",
  reconnect: "Обновить доступ",
  connecting: "Подключаемся…",
  connectedProjects: (count: number) => `Доступно проектов: ${count}`,
  routing: "Куда создавать задачи",
  routingHint: "Выберите основной проект. Для других направлений добавьте правила.",
  defaultProject: "Проект по умолчанию",
  chooseProject: "Выберите проект",
  rules: "Правила",
  noRules: "Все задачи будут создаваться в основном проекте.",
  addRule: "Добавить правило",
  routeLimit: "Можно добавить не больше 50 маршрутов.",
  removeRule: "Удалить правило",
  ruleEnabled: "Правило активно",
  when: "Если",
  matcherFields: { component: "компонент", tag: "тег" },
  matcherPlaceholder: "например, Web client",
  sendTo: "Проект назначения",
  workflow: "Статусы",
  workflowEmpty: "Сначала подключите YouTrack и выберите проект в разделе «Проекты и правила». Здесь появятся его статусы и сопоставления с этапами Falcon.",
  workflowHint: "Значения загружены из YouTrack отдельно для каждого проекта.",
  loadingProject: "Загружаем поля проекта…",
  stateField: "Поле статуса",
  chooseStateField: "Выберите поле",
  readyStatuses: "Готово к проверке",
  readyStatusesHint: "При этих статусах дефект вернётся тестировщику.",
  acceptedStatuses: "Завершено",
  acceptedStatusesHint: "При этих статусах дефект будет закрыт в Falcon.",
  chooseStatuses: "Выберите статусы",
  selectedStatuses: (count: number) => `Выбрано: ${count}`,
  advancedMapping: "Остальные переходы",
  advancedMappingHint: "Необязательно. Настройте, если Falcon должен менять статус задачи.",
  inboundGroups: { backlog: "Новая / в очереди", inProgress: "В работе" },
  outboundStates: { open: "Открыт", triaged: "Разобран", inProgress: "В работе",
    readyForRetest: "Готов к проверке", verified: "Проверен", closed: "Закрыт", reopened: "Переоткрыт" },
  notMapped: "Не менять",
  webhook: "Обновления из YouTrack",
  webhookHint: "Добавьте webhook в нужные проекты, чтобы Falcon получал изменения и удаления задач.",
  webhookLoading: "Готовим параметры webhook…",
  webhookUnavailable: "Сохраните подключение, чтобы получить параметры webhook.",
  webhookUrl: "URL webhook",
  webhookHeader: "HTTP-заголовок",
  webhookToken: "Токен webhook",
  webhookSteps: [
    "В YouTrack подключите приложение Webhook Triggers к нужным проектам.",
    "В настройках приложения укажите URL, название заголовка и токен из Falcon.",
    "Добавьте URL для событий изменения и удаления задач.",
  ],
  webhookSecurity: "Токен меняется после отключения YouTrack. Не сохраняйте его в документах или чатах.",
  webhookGuide: "Инструкция YouTrack",
  copyValue: "Скопировать",
  copiedValue: "Скопировано",
  syncSummary: (linked: number | string, lastSync: string) => `Связано задач: ${linked} · Последняя синхронизация: ${lastSync}`,
  syncErrors: (count: number) => `Ошибок: ${count}`,
  never: "ещё не было",
  readOnly: "Только просмотр.",
  readOnlyHint: "Изменять интеграции могут администратор пространства и QA-менеджер.",
  validation: {
    baseUrl: "Укажите HTTPS-адрес YouTrack. Адрес с путём, например /youtrack/, поддерживается.",
    token: "Для первого подключения нужен постоянный токен YouTrack.",
    connection: "Сначала подключитесь к YouTrack, чтобы загрузить проекты и статусы.",
    defaultProject: "Выберите доступный проект по умолчанию для каждого активного маршрута.",
    routeMatch: "Заполните условие в каждом правиле маршрутизации.",
    routeDuplicate: "Два одинаковых правила маршрутизации использовать нельзя.",
    stateField: "Выберите поле статуса для каждого проекта.",
    readyStatuses: "Выберите хотя бы один статус «Готово к проверке».",
    acceptedStatuses: "Выберите хотя бы один завершающий статус.",
    statusConflict: "Один статус нельзя одновременно отнести к разным этапам.",
    statusUnavailable: "Выбранный статус больше недоступен. Обновите доступ и выберите актуальный.",
    outboundStatus: "Статус перехода сначала отнесите к этапу. «Проверен» должен входить в «Завершено».",
    disconnectFirst: "Сначала отключите текущее подключение, затем укажите другой YouTrack или проект.",
  },
};
