export const enHooksCopy = {
  workspaceSettings: "Workspace settings",
  integrations: "Integrations",
  integrationsHint: "Connect the services your team uses. Each connection belongs to this workspace.",
  groups: { api: "API & contracts", tracker: "Issues and planning", delivery: "Code and builds", communication: "Communication and knowledge" },
  groupHints: { api: "Specifications and interactive documentation", tracker: "Defects and workflows", delivery: "Repositories and CI", communication: "Notifications and documentation" },
  statuses: { connected: "Connected", available: "Available", attention: "Needs attention", checking: "Checking", planned: "Coming soon" },
  refresh: "Refresh",
  retry: "Try again",
  back: "Back to integrations",
  loading: "Loading YouTrack settings",
  loadError: "Could not open YouTrack settings",
  loadErrorHint: "Retry the request. If it still fails, check your workspace access.",
  openYouTrack: "Open YouTrack",
  save: "Save",
  saving: "Saving…",
  saved: "Settings saved",
  stale: "These settings changed in another tab. The latest version has been loaded.",
  saveFailure: "Could not save the settings",
  disconnectFailure: "Could not disconnect YouTrack",
  disconnectBusy: "A sync is still running. Wait a moment and try disconnecting again.",
  disconnected: (count: number) => `YouTrack disconnected. Existing links no longer sync: ${count}.`,
  changeConnection: "Change YouTrack",
  disconnectTitle: "Change the YouTrack connection?",
  disconnectText: "Falcon will stop syncing issues that are already linked. The issues themselves stay unchanged in YouTrack.",
  disconnectConfirm: "Disconnect and continue",
  cancel: "Cancel",
  connectionSuccess: (count: number) => count === 1
    ? "Connected. 1 project found."
    : `Connected. ${count} projects found.`,
  connectionFailure: "Could not connect. Check the address, token, and user permissions.",
  discoveryUnsupported: "YouTrack did not return projects and fields. Check the server address and API access.",
  connection: "Connection",
  connectionHint: "Enter your YouTrack address and a token from a user who can access the required projects.",
  enabled: "Sync with YouTrack",
  enabledHint: "New bug reports can be sent to the selected projects.",
  baseUrl: "YouTrack address",
  apiToken: "Permanent token",
  tokenStored: "Token already saved",
  tokenPlaceholder: "perm:…",
  tokenHint: "Falcon never displays a saved token again.",
  tokenHelpLabel: "How to get a permanent token",
  tokenHelpTitle: "YouTrack permanent token",
  tokenHelpSteps: [
    "Open your avatar in YouTrack and choose Profile.",
    "Go to Account Security → Tokens.",
    "Choose New token, name it Falcon, and select the YouTrack scope.",
    "Create and copy the token immediately — YouTrack will not show it again.",
  ],
  tokenHelpNote: "Falcon can only access projects and issues visible to the token owner.",
  tokenHelpLink: "Open the YouTrack guide",
  showToken: "Show token",
  hideToken: "Hide token",
  connect: "Connect",
  reconnect: "Refresh access",
  connecting: "Connecting…",
  connectedProjects: (count: number) => `${count} projects available`,
  routing: "Issue destination",
  routingHint: "Choose a default project. Add rules for other destinations.",
  defaultProject: "Default project",
  chooseProject: "Choose a project",
  rules: "Rules",
  noRules: "Every issue will use the default project.",
  addRule: "Add rule",
  routeLimit: "You can add up to 50 routes.",
  removeRule: "Remove rule",
  ruleEnabled: "Rule enabled",
  when: "If",
  matcherFields: { component: "component", tag: "tag" },
  matcherPlaceholder: "for example, Web client",
  sendTo: "Destination project",
  workflow: "Statuses",
  workflowEmpty: "Connect YouTrack and select a project under Projects & rules. Its statuses and mappings to Falcon stages will appear here.",
  workflowHint: "Values are loaded from YouTrack separately for each project.",
  loadingProject: "Loading project fields…",
  stateField: "State field",
  chooseStateField: "Choose a field",
  readyStatuses: "Ready for testing",
  readyStatusesHint: "These statuses return the defect to a tester.",
  acceptedStatuses: "Completed",
  acceptedStatusesHint: "These statuses close the defect in Falcon.",
  chooseStatuses: "Choose statuses",
  selectedStatuses: (count: number) => `${count} selected`,
  advancedMapping: "Other transitions",
  advancedMappingHint: "Optional. Configure when Falcon should change an issue state.",
  inboundGroups: { backlog: "New / queued", inProgress: "In progress" },
  outboundStates: { open: "Open", triaged: "Triaged", inProgress: "In progress",
    readyForRetest: "Ready for retest", verified: "Verified", closed: "Closed", reopened: "Reopened" },
  notMapped: "Do not change",
  webhook: "Updates from YouTrack",
  webhookHint: "Add a webhook to the required projects so Falcon receives issue updates and deletions.",
  webhookLoading: "Preparing webhook settings…",
  webhookUnavailable: "Save the connection to get webhook settings.",
  webhookUrl: "Webhook URL",
  webhookHeader: "HTTP header",
  webhookToken: "Webhook token",
  webhookSteps: [
    "Attach the Webhook Triggers app to the required YouTrack projects.",
    "In the app settings, enter the URL, header name, and token from Falcon.",
    "Add the URL for issue update and issue deletion events.",
  ],
  webhookSecurity: "The token changes after disconnecting YouTrack. Do not store it in documents or chats.",
  webhookGuide: "YouTrack instructions",
  copyValue: "Copy",
  copiedValue: "Copied",
  syncSummary: (linked: number | string, lastSync: string) => `Linked issues: ${linked} · Last sync: ${lastSync}`,
  syncErrors: (count: number) => `${count} errors`,
  never: "not yet",
  readOnly: "Read only.",
  readOnlyHint: "Workspace administrators and QA managers can change integrations.",
  validation: {
    baseUrl: "Enter an HTTPS YouTrack address. A server path such as /youtrack/ is supported.",
    token: "A YouTrack permanent token is required for the first connection.",
    connection: "Connect to YouTrack first to load projects and statuses.",
    defaultProject: "Choose an available default project for every active route.",
    routeMatch: "Complete the condition in every routing rule.",
    routeDuplicate: "Duplicate routing rules are not allowed.",
    stateField: "Choose a state field for every project.",
    readyStatuses: "Choose at least one ready-for-testing state.",
    acceptedStatuses: "Choose at least one completed state.",
    statusConflict: "A status cannot belong to more than one stage.",
    statusUnavailable: "A selected status is no longer available. Refresh access and choose a current value.",
    outboundStatus: "Assign every transition status to a stage first. Verified must belong to Completed.",
    disconnectFirst: "Disconnect the current connection before changing the YouTrack service or project.",
  },
};
